import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { useClientLookup } from "@/hooks/useClients";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { isUnauthorizedError } from "@/lib/authUtils";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Skeleton } from "@/components/ui/skeleton";
import { 
  Plus, 
  Search,
  FileText,
  Clock,
  Zap,
  CheckCircle2,
  AlertCircle,
  Mail,
  Send,
} from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import type { Invoice, Client, TimeEntry } from "@shared/schema";
import { WorkspaceLayout } from "@/components/workspace-layout";

export default function Invoices() {
  const { toast } = useToast();
  const [searchQuery, setSearchQuery] = useState("");
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isGenerateDialogOpen, setIsGenerateDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    clientId: "",
    dueDate: "",
    subtotal: "",
    taxRate: "0",
  });
  const [generateFormData, setGenerateFormData] = useState({
    clientId: "",
    dueDate: "",
    taxRate: "8.5",
    selectedTimeEntries: [] as string[],
  });
  const [isReviewDialogOpen, setIsReviewDialogOpen] = useState(false);
  const [invoicePreview, setInvoicePreview] = useState<{
    lineItems: Array<{
      description: string;
      hours: number;
      rate: number;
      amount: number;
      date: string;
    }>;
    subtotal: number;
    taxAmount: number;
    platformFeePercent: number;
    platformFeeAmount: number;
    total: number;
  } | null>(null);

  const { data: invoices = [], isLoading } = useQuery<Invoice[]>({
    queryKey: ["/api/invoices"],
  });

  const [autoGenerateDialogOpen, setAutoGenerateDialogOpen] = useState(false);
  const [autoGenerateResults, setAutoGenerateResults] = useState<{
    generated: number;
    invoices: any[];
    errors: any[];
  } | null>(null);

  const autoGenerateMutation = useMutation({
    mutationFn: async (): Promise<{ generated: number; invoices: any[]; errors: any[] }> => {
      const response = await apiRequest("POST", "/api/invoices/auto-generate");
      return response as unknown as { generated: number; invoices: any[]; errors: any[] };
    },
    onSuccess: (data) => {
      setAutoGenerateResults(data);
      setAutoGenerateDialogOpen(true);
      queryClient.invalidateQueries({ queryKey: ["/api/invoices"] });
      if (data.generated > 0) {
        toast({
          title: "Invoices Auto-Generated",
          description: `Successfully generated ${data.generated} draft invoice(s)`,
        });
      } else {
        toast({
          title: "No Invoices Generated",
          description: "No clients are currently due for billing",
        });
      }
    },
    onError: (error: Error) => {
      toast({
        title: "Auto-Generation Failed",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const { data: clients = [] } = useClientLookup();

  const { data: unbilledTimeEntries = [] } = useQuery<TimeEntry[]>({
    queryKey: ["/api/time-entries/unbilled", generateFormData.clientId],
    enabled: !!generateFormData.clientId && isGenerateDialogOpen,
  });

  const createInvoiceMutation = useMutation({
    mutationFn: async (data: any) => {
      return await apiRequest("POST", "/api/invoices", data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/invoices"] });
      toast({
        title: "Success",
        description: "Invoice created successfully",
      });
      setIsCreateDialogOpen(false);
      setFormData({
        clientId: "",
        dueDate: "",
        subtotal: "",
        taxRate: "0",
      });
    },
    onError: (error: Error) => {
      if (isUnauthorizedError(error)) {
        toast({
          title: "Unauthorized",
          description: "You are logged out. Logging in again...",
          variant: "destructive",
        });
        setTimeout(() => {
          window.location.href = "/api/login";
        }, 500);
        return;
      }
      toast({
        title: "Error",
        description: error.message || "Failed to create invoice",
        variant: "destructive",
      });
    },
  });

  const generateInvoiceMutation = useMutation({
    mutationFn: async (data: any) => {
      return await apiRequest("POST", "/api/invoices/generate-from-time", data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/invoices"] });
      queryClient.invalidateQueries({ queryKey: ["/api/time-entries/unbilled", generateFormData.clientId] });
      toast({
        title: "Success",
        description: "Invoice generated from time entries successfully",
      });
      setIsGenerateDialogOpen(false);
      setGenerateFormData({
        clientId: "",
        dueDate: "",
        taxRate: "8.5",
        selectedTimeEntries: [],
      });
    },
    onError: (error: Error) => {
      if (isUnauthorizedError(error)) {
        toast({
          title: "Unauthorized",
          description: "You are logged out. Logging in again...",
          variant: "destructive",
        });
        setTimeout(() => {
          window.location.href = "/api/login";
        }, 500);
        return;
      }
      toast({
        title: "Error",
        description: error.message || "Failed to generate invoice",
        variant: "destructive",
      });
    },
  });

  const handleSubmit = () => {
    if (!formData.clientId || !formData.dueDate || !formData.subtotal) {
      toast({
        title: "Validation Error",
        description: "Please fill in all required fields",
        variant: "destructive",
      });
      return;
    }

    const subtotal = parseFloat(formData.subtotal);
    const taxRate = parseFloat(formData.taxRate) || 0;
    const tax = subtotal * (taxRate / 100);
    const total = subtotal + tax;

    createInvoiceMutation.mutate({
      clientId: formData.clientId,
      dueDate: new Date(formData.dueDate).toISOString(),
      subtotal,
      tax,
      total,
      status: "draft",
    });
  };

  const handleGenerateFromTime = () => {
    if (!generateFormData.clientId || !generateFormData.dueDate) {
      toast({
        title: "Validation Error",
        description: "Please select a client and due date",
        variant: "destructive",
      });
      return;
    }

    if (generateFormData.selectedTimeEntries.length === 0) {
      toast({
        title: "Validation Error",
        description: "Please select at least one time entry",
        variant: "destructive",
      });
      return;
    }

    // Calculate invoice preview
    const selectedEntries = unbilledTimeEntries.filter(entry => 
      generateFormData.selectedTimeEntries.includes(entry.id)
    );

    const lineItems = selectedEntries.map(entry => ({
      description: entry.notes || `Work on ${new Date(entry.clockIn).toLocaleDateString()}`,
      hours: parseFloat(entry.totalHours as string || "0"),
      rate: parseFloat(entry.hourlyRate as string || "0"),
      amount: parseFloat(entry.totalAmount as string || "0"),
      date: new Date(entry.clockIn).toLocaleDateString(),
    }));

    const subtotal = lineItems.reduce((sum, item) => sum + item.amount, 0);
    const taxRate = parseFloat(generateFormData.taxRate);
    const taxAmount = (subtotal * taxRate) / 100;
    // Note: Platform fee is calculated on backend, using 5% as display estimate
    // Actual fee will be applied based on workspace settings
    const platformFeePercent = 5; 
    const platformFeeAmount = ((subtotal + taxAmount) * platformFeePercent) / 100;
    const total = subtotal + taxAmount;

    setInvoicePreview({
      lineItems,
      subtotal,
      taxAmount,
      platformFeePercent,
      platformFeeAmount,
      total,
    });

    // Close generate dialog and open review dialog
    setIsGenerateDialogOpen(false);
    setIsReviewDialogOpen(true);
  };

  const handleConfirmInvoice = () => {
    generateInvoiceMutation.mutate({
      clientId: generateFormData.clientId,
      timeEntryIds: generateFormData.selectedTimeEntries,
      dueDate: new Date(generateFormData.dueDate).toISOString(), // Convert to ISO format
      taxRate: parseFloat(generateFormData.taxRate),
    });
    setIsReviewDialogOpen(false);
  };

  const toggleTimeEntry = (id: string) => {
    setGenerateFormData(prev => ({
      ...prev,
      selectedTimeEntries: prev.selectedTimeEntries.includes(id)
        ? prev.selectedTimeEntries.filter(entryId => entryId !== id)
        : [...prev.selectedTimeEntries, id],
    }));
  };

  const calculateTimeEntryTotal = () => {
    return unbilledTimeEntries
      .filter(entry => generateFormData.selectedTimeEntries.includes(entry.id))
      .reduce((sum, entry) => sum + parseFloat(entry.totalAmount as string || "0"), 0);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'paid': return 'default';
      case 'sent': return 'secondary';
      case 'overdue': return 'destructive';
      default: return 'outline';
    }
  };

  const getClientName = (clientId: string) => {
    const client = clients.find(c => c.id === clientId);
    return client ? `${client.firstName} ${client.lastName}` : "Unknown";
  };

  const filteredInvoices = invoices.filter(inv =>
    inv.invoiceNumber.toLowerCase().includes(searchQuery.toLowerCase()) ||
    getClientName(inv.clientId).toLowerCase().includes(searchQuery.toLowerCase())
  );

  const draftInvoices = invoices.filter(inv => inv.status === "draft");

  const sendEmailMutation = useMutation({
    mutationFn: async (invoiceId: string) => {
      const response = await apiRequest("POST", `/api/invoices/${invoiceId}/send-email`);
      return response;
    },
    onSuccess: () => {
      toast({
        title: "Invoice Sent",
        description: "Invoice email sent successfully to client",
      });
      queryClient.invalidateQueries({ queryKey: ["/api/invoices"] });
    },
    onError: (error: Error) => {
      toast({
        title: "Send Failed",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  return (
    <WorkspaceLayout maxWidth="7xl">
      <div className="w-full">
        <div className="space-y-4 sm:space-y-6">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <h2 className="text-2xl sm:text-3xl font-bold mb-1" data-testid="text-invoices-title">
                Invoices
              </h2>
              <p className="text-sm sm:text-base text-[hsl(var(--cad-text-secondary))]" data-testid="text-invoices-subtitle">
                Generate and track customer invoices
              </p>
            </div>
          
          <div className="flex flex-wrap gap-3">
            <Button 
              variant="outline" 
              onClick={() => autoGenerateMutation.mutate()}
              disabled={autoGenerateMutation.isPending}
              data-testid="button-auto-generate"
            >
              <Zap className="mr-2 h-4 w-4" />
              {autoGenerateMutation.isPending ? "Auto-Generating..." : "Auto-Generate Invoices"}
            </Button>
            
            {draftInvoices.length > 0 && (
              <Badge variant="secondary" className="py-1 px-3">
                {draftInvoices.length} Draft{draftInvoices.length !== 1 ? 's' : ''} Pending Review
              </Badge>
            )}

            <Dialog open={isGenerateDialogOpen} onOpenChange={setIsGenerateDialogOpen}>
              <DialogTrigger asChild>
                <Button variant="outline" data-testid="button-generate-from-time">
                  <Clock className="mr-2 h-4 w-4" />
                  Generate from Time
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle>Generate Invoice from Time Entries</DialogTitle>
                  <DialogDescription>
                    Select unbilled time entries to create an invoice
                  </DialogDescription>
                </DialogHeader>
                <div className="space-y-4 py-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label>Client *</Label>
                      <Select value={generateFormData.clientId} onValueChange={(value) => setGenerateFormData({ ...generateFormData, clientId: value, selectedTimeEntries: [] })}>
                        <SelectTrigger data-testid="select-generate-client">
                          <SelectValue placeholder="Select client" />
                        </SelectTrigger>
                        <SelectContent>
                          {clients.map((client) => (
                            <SelectItem key={client.id} value={client.id}>
                              {client.firstName} {client.lastName}
                              {client.companyName && ` - ${client.companyName}`}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-2">
                      <Label>Due Date *</Label>
                      <Input 
                        type="date" 
                        value={generateFormData.dueDate}
                        onChange={(e) => setGenerateFormData({ ...generateFormData, dueDate: e.target.value })}
                        data-testid="input-generate-duedate" 
                      />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <Label>Tax Rate (%)</Label>
                    <Input 
                      type="number" 
                      step="0.1" 
                      value={generateFormData.taxRate}
                      onChange={(e) => setGenerateFormData({ ...generateFormData, taxRate: e.target.value })}
                      data-testid="input-generate-tax" 
                    />
                  </div>

                  {generateFormData.clientId && (
                    <div className="space-y-3">
                      <Label>Select Time Entries</Label>
                      {unbilledTimeEntries.length === 0 ? (
                        <p className="text-sm text-muted-foreground py-4">
                          No unbilled time entries for this client
                        </p>
                      ) : (
                        <div className="space-y-2 max-h-[300px] overflow-y-auto border rounded-md p-3">
                          {unbilledTimeEntries.map((entry) => (
                            <div key={entry.id} className="flex items-start gap-3 p-3 rounded-md hover-elevate">
                              <Checkbox
                                checked={generateFormData.selectedTimeEntries.includes(entry.id)}
                                onCheckedChange={() => toggleTimeEntry(entry.id)}
                                data-testid={`checkbox-time-entry-${entry.id}`}
                              />
                              <div className="flex-1 space-y-1">
                                <div className="flex justify-between items-start">
                                  <div>
                                    <p className="text-sm font-medium">
                                      {new Date(entry.clockIn).toLocaleDateString()} - {entry.totalHours} hrs
                                    </p>
                                    {entry.notes && (
                                      <p className="text-xs text-muted-foreground mt-1">{entry.notes}</p>
                                    )}
                                  </div>
                                  <p className="text-sm font-semibold">${entry.totalAmount}</p>
                                </div>
                              </div>
                            </div>
                          ))}
                        </div>
                      )}
                      {generateFormData.selectedTimeEntries.length > 0 && (
                        <div className="flex justify-between items-center p-3 bg-muted rounded-md">
                          <span className="font-medium">Total Selected:</span>
                          <span className="text-lg font-semibold">${calculateTimeEntryTotal().toFixed(2)}</span>
                        </div>
                      )}
                    </div>
                  )}
                </div>
                <DialogFooter>
                  <Button variant="outline" onClick={() => setIsGenerateDialogOpen(false)}>
                    Cancel
                  </Button>
                  <Button 
                    onClick={handleGenerateFromTime}
                    disabled={generateInvoiceMutation.isPending || generateFormData.selectedTimeEntries.length === 0}
                    data-testid="button-generate-invoice"
                  >
                    {generateInvoiceMutation.isPending ? "Generating..." : "Generate Invoice"}
                  </Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>

            {/* Invoice Review Dialog */}
            <Dialog open={isReviewDialogOpen} onOpenChange={setIsReviewDialogOpen}>
              <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle>Review Invoice</DialogTitle>
                  <DialogDescription>
                    Review the invoice details before creating
                  </DialogDescription>
                </DialogHeader>
                {invoicePreview && (
                  <div className="space-y-6 py-4">
                    {/* Client & Due Date Info */}
                    <div className="grid grid-cols-2 gap-4 p-4 bg-muted rounded-md">
                      <div>
                        <p className="text-sm text-muted-foreground">Client</p>
                        <p className="font-medium">{getClientName(generateFormData.clientId)}</p>
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground">Due Date</p>
                        <p className="font-medium">{new Date(generateFormData.dueDate).toLocaleDateString()}</p>
                      </div>
                    </div>

                    {/* Line Items Table */}
                    <div className="border rounded-md">
                      <Table>
                        <TableHeader>
                          <TableRow>
                            <TableHead>Date</TableHead>
                            <TableHead>Description</TableHead>
                            <TableHead className="text-right">Hours</TableHead>
                            <TableHead className="text-right">Rate</TableHead>
                            <TableHead className="text-right">Amount</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          {invoicePreview.lineItems.map((item, index) => (
                            <TableRow key={index}>
                              <TableCell className="text-sm">{item.date}</TableCell>
                              <TableCell className="text-sm">{item.description}</TableCell>
                              <TableCell className="text-right text-sm">{item.hours.toFixed(2)}</TableCell>
                              <TableCell className="text-right text-sm">${item.rate.toFixed(2)}</TableCell>
                              <TableCell className="text-right font-medium">${item.amount.toFixed(2)}</TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </div>

                    {/* Totals Breakdown */}
                    <div className="space-y-3">
                      <div className="flex justify-between items-center py-2 border-t">
                        <span className="text-sm">Subtotal</span>
                        <span className="font-medium">${invoicePreview.subtotal.toFixed(2)}</span>
                      </div>
                      <div className="flex justify-between items-center py-2">
                        <span className="text-sm">Tax ({generateFormData.taxRate}%)</span>
                        <span className="font-medium">${invoicePreview.taxAmount.toFixed(2)}</span>
                      </div>
                      <div className="flex justify-between items-center py-2">
                        <span className="text-sm text-muted-foreground">Platform Fee ({invoicePreview.platformFeePercent}%)</span>
                        <span className="text-sm text-muted-foreground">-${invoicePreview.platformFeeAmount.toFixed(2)}</span>
                      </div>
                      <div className="flex justify-between items-center py-3 border-t-2 border-primary/20">
                        <span className="text-lg font-semibold">Total</span>
                        <span className="text-lg font-bold">${invoicePreview.total.toFixed(2)}</span>
                      </div>
                      <p className="text-xs text-muted-foreground text-right">
                        You receive ${(invoicePreview.total - invoicePreview.platformFeeAmount).toFixed(2)} after platform fee
                      </p>
                    </div>
                  </div>
                )}
                <DialogFooter>
                  <Button variant="outline" onClick={() => {
                    setIsReviewDialogOpen(false);
                    setIsGenerateDialogOpen(true);
                  }} data-testid="button-back-to-edit">
                    Back to Edit
                  </Button>
                  <Button 
                    onClick={handleConfirmInvoice}
                    disabled={generateInvoiceMutation.isPending}
                    data-testid="button-confirm-invoice"
                  >
                    {generateInvoiceMutation.isPending ? "Creating..." : "Confirm & Create Invoice"}
                  </Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>

            {/* Auto-Generation Results Dialog */}
            <Dialog open={autoGenerateDialogOpen} onOpenChange={setAutoGenerateDialogOpen}>
              <DialogContent className="max-w-2xl">
                <DialogHeader>
                  <DialogTitle>Auto-Generation Results</DialogTitle>
                  <DialogDescription>
                    Summary of automated invoice generation
                  </DialogDescription>
                </DialogHeader>
                {autoGenerateResults && (
                  <div className="space-y-6 py-4">
                    {/* Summary Stats */}
                    <div className="grid grid-cols-2 gap-4">
                      <Card>
                        <CardContent className="p-4">
                          <div className="flex items-center gap-3">
                            <div className="p-2 bg-muted/10 rounded-lg">
                              <CheckCircle2 className="h-5 w-5 text-blue-500" />
                            </div>
                            <div>
                              <p className="text-2xl font-bold">{autoGenerateResults.generated}</p>
                              <p className="text-sm text-muted-foreground">Invoices Generated</p>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                      
                      {autoGenerateResults.errors && autoGenerateResults.errors.length > 0 && (
                        <Card>
                          <CardContent className="p-4">
                            <div className="flex items-center gap-3">
                              <div className="p-2 bg-red-500/10 rounded-lg">
                                <AlertCircle className="h-5 w-5 text-red-500" />
                              </div>
                              <div>
                                <p className="text-2xl font-bold">{autoGenerateResults.errors?.length || 0}</p>
                                <p className="text-sm text-muted-foreground">Errors</p>
                              </div>
                            </div>
                          </CardContent>
                        </Card>
                      )}
                    </div>

                    {/* Generated Invoices List */}
                    {autoGenerateResults.invoices && autoGenerateResults.invoices.length > 0 && (
                      <div className="space-y-2">
                        <h4 className="font-semibold">Generated Draft Invoices</h4>
                        <div className="space-y-2">
                          {autoGenerateResults.invoices?.map((item: any, index: number) => (
                            <Card key={index}>
                              <CardContent className="p-4">
                                <div className="flex justify-between items-start">
                                  <div>
                                    <p className="font-medium">
                                      {item.client.firstName} {item.client.lastName}
                                    </p>
                                    <p className="text-sm text-muted-foreground">
                                      {item.unbilledHours.toFixed(2)} hours
                                    </p>
                                  </div>
                                  <div className="text-right">
                                    <p className="font-bold">${parseFloat(item.invoice.total).toFixed(2)}</p>
                                    <Badge variant="secondary" className="mt-1">Draft</Badge>
                                  </div>
                                </div>
                              </CardContent>
                            </Card>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Errors List */}
                    {autoGenerateResults.errors && autoGenerateResults.errors.length > 0 && (
                      <div className="space-y-2">
                        <h4 className="font-semibold text-red-500">Errors</h4>
                        <div className="space-y-2">
                          {autoGenerateResults.errors?.map((error: any, index: number) => (
                            <Card key={index} className="border-red-500/20">
                              <CardContent className="p-3">
                                <p className="font-medium text-sm">{error.clientName}</p>
                                <p className="text-xs text-muted-foreground">{error.error}</p>
                              </CardContent>
                            </Card>
                          ))}
                        </div>
                      </div>
                    )}

                    {autoGenerateResults.generated === 0 && (
                      <div className="text-center py-8">
                        <p className="text-muted-foreground">
                          No clients are currently due for billing.
                        </p>
                        <p className="text-sm text-muted-foreground mt-2">
                          Invoices are generated based on billing cycles (weekly, bi-weekly, monthly).
                        </p>
                      </div>
                    )}
                  </div>
                )}
                <DialogFooter>
                  <Button onClick={() => setAutoGenerateDialogOpen(false)} data-testid="button-close-results">
                    Close
                  </Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>

            <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
              <DialogTrigger asChild>
                <Button data-testid="button-create-invoice">
                  <Plus className="mr-2 h-4 w-4" />
                  Create Invoice
                </Button>
              </DialogTrigger>
            <DialogContent className="max-w-3xl">
              <DialogHeader>
                <DialogTitle>Create Invoice</DialogTitle>
                <DialogDescription>
                  Generate a new invoice for a client
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="client">Client *</Label>
                    <Select value={formData.clientId} onValueChange={(value) => setFormData({ ...formData, clientId: value })}>
                      <SelectTrigger id="client" data-testid="select-invoice-client">
                        <SelectValue placeholder="Select client" />
                      </SelectTrigger>
                      <SelectContent>
                        {clients.length === 0 ? (
                          <SelectItem value="none">No clients available</SelectItem>
                        ) : (
                          clients.map((client) => (
                            <SelectItem key={client.id} value={client.id}>
                              {client.firstName} {client.lastName}
                            </SelectItem>
                          ))
                        )}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="dueDate">Due Date *</Label>
                    <Input 
                      id="dueDate" 
                      type="date" 
                      value={formData.dueDate}
                      onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                      data-testid="input-invoice-duedate" 
                    />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="subtotal">Subtotal *</Label>
                    <Input 
                      id="subtotal" 
                      type="number" 
                      step="0.01" 
                      placeholder="0.00"
                      value={formData.subtotal}
                      onChange={(e) => setFormData({ ...formData, subtotal: e.target.value })}
                      data-testid="input-invoice-subtotal" 
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="taxRate">Tax Rate (%)</Label>
                    <Input 
                      id="taxRate" 
                      type="number" 
                      step="0.01" 
                      placeholder="0"
                      value={formData.taxRate}
                      onChange={(e) => setFormData({ ...formData, taxRate: e.target.value })}
                      data-testid="input-invoice-tax" 
                    />
                  </div>
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setIsCreateDialogOpen(false)}>
                  Cancel
                </Button>
                <Button 
                  onClick={handleSubmit}
                  disabled={createInvoiceMutation.isPending || clients.length === 0}
                  data-testid="button-save-invoice"
                >
                  {createInvoiceMutation.isPending ? "Creating..." : "Create Invoice"}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
          </div>
        </div>

        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search invoices..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-9"
            data-testid="input-search-invoices"
          />
        </div>

        {isLoading ? (
          <Card>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Invoice #</TableHead>
                  <TableHead>Client</TableHead>
                  <TableHead>Due Date</TableHead>
                  <TableHead>Amount</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {[1, 2, 3, 4, 5].map((i) => (
                  <TableRow key={i}>
                    <TableCell><Skeleton className="h-5 w-24" /></TableCell>
                    <TableCell><Skeleton className="h-5 w-32" /></TableCell>
                    <TableCell><Skeleton className="h-5 w-24" /></TableCell>
                    <TableCell><Skeleton className="h-5 w-20" /></TableCell>
                    <TableCell><Skeleton className="h-5 w-16" /></TableCell>
                    <TableCell><Skeleton className="h-8 w-16" /></TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </Card>
        ) : filteredInvoices.length === 0 && !searchQuery ? (
          <Card data-testid="card-no-invoices">
            <CardContent className="flex flex-col items-center justify-center py-16">
              <FileText className="h-16 w-16 text-muted-foreground opacity-20 mb-4" />
              <h3 className="text-lg font-medium mb-2">No invoices yet</h3>
              <p className="text-sm text-muted-foreground mb-6 text-center max-w-md">
                Create your first invoice to start billing clients
              </p>
              <Button onClick={() => setIsCreateDialogOpen(true)} data-testid="button-create-first-invoice">
                <Plus className="mr-2 h-4 w-4" />
                Create First Invoice
              </Button>
            </CardContent>
          </Card>
        ) : (
          <Card>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Invoice #</TableHead>
                  <TableHead>Client</TableHead>
                  <TableHead>Due Date</TableHead>
                  <TableHead>Amount</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredInvoices.map((invoice) => (
                  <TableRow key={invoice.id} data-testid={`invoice-row-${invoice.id}`}>
                    <TableCell className="font-medium">{invoice.invoiceNumber}</TableCell>
                    <TableCell>{getClientName(invoice.clientId)}</TableCell>
                    <TableCell>{invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : 'N/A'}</TableCell>
                    <TableCell>${parseFloat(String(invoice.total || 0)).toFixed(2)}</TableCell>
                    <TableCell>
                      <Badge variant={getStatusColor(invoice.status || 'draft')}>
                        {invoice.status || 'draft'}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-2">
                        {invoice.status === 'draft' && (
                          <Button 
                            variant="ghost" 
                            size="sm"
                            onClick={() => sendEmailMutation.mutate(invoice.id)}
                            disabled={sendEmailMutation.isPending}
                            data-testid={`button-send-invoice-${invoice.id}`}
                          >
                            <Send className="h-4 w-4 mr-1" />
                            Send
                          </Button>
                        )}
                        {invoice.status === 'sent' && (
                          <Badge variant="outline" className="gap-1">
                            <Mail className="h-3 w-3" />
                            Sent
                          </Badge>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </Card>
        )}
        </div>
      </div>
    </WorkspaceLayout>
  );
}
