import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { UniversalModal, UniversalModalHeader, UniversalModalTitle, UniversalModalFooter, UniversalModalContent } from '@/components/ui/universal-modal';
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import { FileText, Plus, Sparkles, Eye, DollarSign, CheckCircle, Clock } from "lucide-react";
import { format } from "date-fns";
import {
  DsPageWrapper,
  DsPageHeader,
  DsStatCard,
  DsSectionCard,
  DsDataRow,
  DsBadge,
  DsButton,
  DsEmptyState
} from "@/components/ui/ds-components";

const STATUS_COLORS: Record<string, "gold" | "info" | "success" | "muted" | "warning"> = {
  intake: "muted", 
  proposal_drafted: "info", 
  under_review: "warning",
  submitted: "gold", 
  won: "success", 
  lost: "muted", 
  cancelled: "muted",
};

function timeAgo(ts: string) {
  if (!ts) return "—";
  try { return format(new Date(ts), "MMM d, yyyy"); } catch { return ts; }
}

export default function RFPManager() {
  const { user } = useAuth();
  const workspaceId = user?.currentWorkspaceId;
  const { toast } = useToast();
  const [showNewRFP, setShowNewRFP] = useState(false);
  const [viewRFP, setViewRFP] = useState<any>(null);
  const [generateId, setGenerateId] = useState<string | null>(null);

  const rfps = useQuery<any>({ queryKey: ["/api/rfp", { workspaceId }], enabled: !!workspaceId });

  function invalidate() { queryClient.invalidateQueries({ queryKey: ["/api/rfp"] }); }

  const createRFP = useMutation({
    mutationFn: (data) => apiRequest("POST", "/api/rfp", { ...data, workspaceId, createdBy: user?.id }),
    onSuccess: () => { invalidate(); setShowNewRFP(false); toast({ title: "RFP created" }); },
    onError: (e) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const generateProposal = useMutation({
    mutationFn: (id: string) => apiRequest("POST", `/api/rfp/${id}/generate-proposal`, { workspaceId }),
    onSuccess: (d) => {
      invalidate();
      if (viewRFP) setViewRFP({ ...viewRFP, ...d });
      setGenerateId(null);
      toast({ title: "Proposal generated by AI" });
    },
    onError: (e) => { toast({ title: "Error", description: e.message, variant: "destructive" }); setGenerateId(null); },
  });

  const updateStatus = useMutation({
    mutationFn: ({ id, status, winLoss }: any) => apiRequest("PATCH", `/api/rfp/${id}`, { status, winLoss, workspaceId }),
    onSuccess: () => { invalidate(); toast({ title: "Status updated" }); },
  });

  function NewRFPForm() {
    const [f, setF] = useState({ rfpTitle: "", clientName: "", clientContactName: "", clientContactEmail: "", rfpDescription: "", deadline: "", estimatedValue: "", officerCountRequired: "", coverageHoursRequired: "", specialRequirements: "" });
    return (
      <div className="space-y-4 max-h-[60vh] overflow-y-auto pr-2">
        <Input data-testid="input-rfp-title" placeholder="RFP title *" value={f.rfpTitle} onChange={e => setF(p => ({ ...p, rfpTitle: e.target.value }))} className="bg-transparent border-[var(--ds-border)]" />
        <Input data-testid="input-rfp-client" placeholder="Client / company name *" value={f.clientName} onChange={e => setF(p => ({ ...p, clientName: e.target.value }))} className="bg-transparent border-[var(--ds-border)]" />
        <div className="grid grid-cols-2 gap-4">
          <Input placeholder="Contact name" value={f.clientContactName} onChange={e => setF(p => ({ ...p, clientContactName: e.target.value }))} className="bg-transparent border-[var(--ds-border)]" />
          <Input type="email" placeholder="Contact email" value={f.clientContactEmail} onChange={e => setF(p => ({ ...p, clientContactEmail: e.target.value }))} className="bg-transparent border-[var(--ds-border)]" />
        </div>
        <Textarea placeholder="RFP description / overview" value={f.rfpDescription} onChange={e => setF(p => ({ ...p, rfpDescription: e.target.value }))} className="bg-transparent border-[var(--ds-border)] min-h-[80px]" />
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1">
            <label className="text-[10px] uppercase opacity-50 font-bold tracking-widest">Submission deadline</label>
            <Input type="date" value={f.deadline} onChange={e => setF(p => ({ ...p, deadline: e.target.value }))} className="bg-transparent border-[var(--ds-border)]" />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] uppercase opacity-50 font-bold tracking-widest">Estimated value ($)</label>
            <Input type="number" placeholder="0" value={f.estimatedValue} onChange={e => setF(p => ({ ...p, estimatedValue: e.target.value }))} className="bg-transparent border-[var(--ds-border)]" />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] uppercase opacity-50 font-bold tracking-widest">Officers required</label>
            <Input type="number" placeholder="0" value={f.officerCountRequired} onChange={e => setF(p => ({ ...p, officerCountRequired: e.target.value }))} className="bg-transparent border-[var(--ds-border)]" />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] uppercase opacity-50 font-bold tracking-widest">Coverage hours</label>
            <Input placeholder="e.g. 24/7" value={f.coverageHoursRequired} onChange={e => setF(p => ({ ...p, coverageHoursRequired: e.target.value }))} className="bg-transparent border-[var(--ds-border)]" />
          </div>
        </div>
        <Textarea placeholder="Special requirements" value={f.specialRequirements} onChange={e => setF(p => ({ ...p, specialRequirements: e.target.value }))} className="bg-transparent border-[var(--ds-border)] min-h-[80px]" />
        <div className="flex justify-end gap-2 pt-4">
          <DsButton variant="ghost" onClick={() => setShowNewRFP(false)}>Cancel</DsButton>
          <DsButton data-testid="button-submit-rfp" onClick={() => createRFP.mutate({ ...f, estimatedValue: f.estimatedValue ? Number(f.estimatedValue) : null, officerCountRequired: f.officerCountRequired ? Number(f.officerCountRequired) : null })}
            disabled={!f.rfpTitle || !f.clientName || createRFP.isPending}>
            {createRFP.isPending ? "Creating…" : "Create RFP"}
          </DsButton>
        </div>
      </div>
    );
  }

  return (
    <DsPageWrapper className="max-w-5xl mx-auto">
      <DsPageHeader 
        title="RFP Automation" 
        subtitle="AI-powered proposal generation — draft to signature"
        data-testid="text-rfp-title"
        actions={<DsButton size="sm" data-testid="button-new-rfp" onClick={() => setShowNewRFP(true)}><Plus size={14} className="mr-1" />New RFP</DsButton>}
      />

      <div className="space-y-6">
        {rfps.isLoading ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : rfps.data?.rfps?.length === 0 ? (
          <DsEmptyState
            icon={FileText}
            title="No RFPs yet"
            subtitle="Create your first RFP to generate AI-powered proposals."
            action={<DsButton onClick={() => setShowNewRFP(true)}>Start First RFP</DsButton>}
            data-testid="empty-state-rfps"
          />
        ) : (
          <div className="space-y-1">
            {rfps.data?.rfps?.map((rfp) => (
              <DsDataRow key={rfp.id} data-testid={`card-rfp-${rfp.id}`} interactive onClick={() => setViewRFP(rfp)}>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-mono text-[10px] opacity-70 tracking-tighter">#{rfp.rfp_number}</span>
                    <DsBadge color={STATUS_COLORS[rfp.status] || "muted"}>
                      {rfp.status.replace(/_/g, " ")}
                    </DsBadge>
                    {rfp.win_loss === "won" && <DsBadge color="success"><CheckCircle size={10} className="mr-1" />Won</DsBadge>}
                    {rfp.win_loss === "lost" && <DsBadge color="muted">Lost</DsBadge>}
                  </div>
                  <p className="font-bold text-sm">{rfp.rfp_title}</p>
                  <p className="text-xs opacity-60 uppercase tracking-widest">{rfp.client_name}</p>
                  <div className="flex flex-wrap gap-x-4 gap-y-1 mt-2">
                    {rfp.estimated_value && <span className="text-[10px] opacity-50 flex items-center gap-1"><DollarSign size={10} />${Number(rfp.estimated_value).toLocaleString()}</span>}
                    {rfp.deadline && <span className="text-[10px] opacity-50 flex items-center gap-1"><Clock size={10} />Due {timeAgo(rfp.deadline)}</span>}
                    {rfp.proposal_generated_at && <span className="text-[10px] text-[var(--ds-success)] font-bold flex items-center gap-1"><Sparkles size={10} />AI Proposal Ready</span>}
                  </div>
                </div>
                <div className="flex gap-2">
                  {rfp.status === "intake" && (
                    <DsButton size="sm" variant="outline" data-testid={`button-generate-proposal-${rfp.id}`}
                      onClick={(e) => { e.stopPropagation(); setGenerateId(rfp.id); generateProposal.mutate(rfp.id); }}
                      disabled={generateProposal.isPending && generateId === rfp.id}>
                      <Sparkles size={14} className="mr-1.5" />
                      {generateProposal.isPending && generateId === rfp.id ? "Drafting…" : "Draft AI Proposal"}
                    </DsButton>
                  )}
                  <DsButton size="sm" variant="ghost">
                    <Eye size={16} />
                  </DsButton>
                </div>
              </DsDataRow>
            ))}
          </div>
        )}
      </div>

      <UniversalModal open={showNewRFP} onOpenChange={setShowNewRFP}>
        <UniversalModalContent className="max-w-lg bg-[var(--ds-navy-mid)] border-[var(--ds-border)] text-[var(--ds-text-primary)]">
          <UniversalModalHeader>
            <UniversalModalTitle style={{ fontFamily: 'var(--ds-font-display)' }}>New RFP Intake</UniversalModalTitle>
          </UniversalModalHeader>
          <div className="pt-4">
            <NewRFPForm />
          </div>
        </UniversalModalContent>
      </UniversalModal>

      <UniversalModal open={!!viewRFP} onOpenChange={v => !v && setViewRFP(null)}>
        <UniversalModalContent className="max-w-2xl bg-[var(--ds-navy-mid)] border-[var(--ds-border)] text-[var(--ds-text-primary)]">
          <UniversalModalHeader>
            <UniversalModalTitle style={{ fontFamily: 'var(--ds-font-display)' }}>{viewRFP?.rfp_title}</UniversalModalTitle>
          </UniversalModalHeader>
          {viewRFP && (
            <div className="space-y-6 pt-4 max-h-[70vh] overflow-y-auto pr-2">
              <div className="flex gap-2 flex-wrap">
                <DsBadge color={STATUS_COLORS[viewRFP.status] || "muted"}>{viewRFP.status.replace(/_/g, " ")}</DsBadge>
                <span className="text-xs opacity-60 uppercase tracking-widest px-1">{viewRFP.client_name}</span>
                {viewRFP.estimated_value && <DsBadge color="gold">${Number(viewRFP.estimated_value).toLocaleString()}</DsBadge>}
              </div>

              {viewRFP.rfp_description && (
                <div className="space-y-1">
                  <p className="text-[10px] font-bold uppercase tracking-widest opacity-50">Description</p>
                  <p className="text-sm opacity-90 leading-relaxed">{viewRFP.rfp_description}</p>
                </div>
              )}

              {viewRFP.proposal_draft ? (
                <div className="space-y-2">
                  <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--ds-gold)] flex items-center gap-1">
                    <Sparkles size={10} /> AI-Generated Proposal Draft
                  </p>
                  <div className="rounded-lg bg-black/20 border border-[var(--ds-border)] p-5 text-xs whitespace-pre-wrap leading-relaxed opacity-90 font-mono">
                    {viewRFP.proposal_draft}
                  </div>
                </div>
              ) : (
                <div className="rounded-lg bg-[var(--ds-navy-light)] p-8 text-center border border-[var(--ds-border)]">
                  <p className="text-sm opacity-60 mb-4">No proposal generated yet.</p>
                  <DsButton onClick={() => { generateProposal.mutate(viewRFP.id); }} disabled={generateProposal.isPending}>
                    <Sparkles size={16} className="mr-2" />{generateProposal.isPending ? "Generating…" : "Generate with AI"}
                  </DsButton>
                </div>
              )}

              {viewRFP.proposal_draft && viewRFP.status === "proposal_drafted" && (
                <div className="flex gap-3 pt-4 border-t border-[var(--ds-border)]">
                  <DsButton size="sm" variant="outline" className="flex-1" onClick={() => updateStatus.mutate({ id: viewRFP.id, status: "submitted" })}>Mark Submitted</DsButton>
                  <DsButton size="sm" className="flex-1" onClick={() => updateStatus.mutate({ id: viewRFP.id, status: "won", winLoss: "won" })}>
                    <CheckCircle size={14} className="mr-1.5" />Won
                  </DsButton>
                  <DsButton size="sm" variant="ghost" className="flex-1 text-[var(--ds-danger)]" onClick={() => updateStatus.mutate({ id: viewRFP.id, status: "lost", winLoss: "lost" })}>Lost</DsButton>
                </div>
              )}
              
              <div className="flex justify-end">
                <DsButton variant="ghost" onClick={() => setViewRFP(null)}>Close</DsButton>
              </div>
            </div>
          )}
        </UniversalModalContent>
      </UniversalModal>
    </DsPageWrapper>
  );
}
