import { sanitizeError } from '../middleware/errorHandler';
import { Router } from "express";
import { db } from "../db";
import { sql, eq, and, desc, gte, inArray } from "drizzle-orm";
import { workspaces, employees, shifts, trinityEmailConversations, staffingClaimTokens, clients, invoices, emailUnsubscribes, emailEvents, resendWebhookEvents, notificationDeliveries } from "@shared/schema";
import { universalAudit } from "../services/universalAuditService";
import { trinityStaffingOrchestrator } from "../services/trinityStaffing/orchestrator";
import { inboundOpportunityAgent } from "../services/inboundOpportunityAgent";
import { parseOrgCodeFromEmail, lookupWorkspaceByOrgCode, lookupWorkspaceByEmailSlug } from "../utils/orgCodeValidator";
import { emailService } from "../services/emailService";
import { meteredGemini } from "../services/billing/meteredGeminiClient";
import { officerScoreService } from "../services/officerScoreService";
import crypto from "crypto";
import { typedExec, typedQuery } from '../lib/typedSql';
import { EMAIL, PLATFORM } from '../config/platformConfig';
import { createLogger } from '../lib/logger';
import { scheduleNonBlocking } from '../lib/scheduleNonBlocking';
const log = createLogger('ResendWebhooks');


/**
 * Extract a Trinity reference number from an email subject or body.
 * Matches patterns like [Ref: TRN-XXXXXXXX] or Ref: TRN-XXXXXXXX
 */
function extractTrinityRefNumber(subject: string, body: string): string | null {
  const combined = `${subject || ''} ${body || ''}`;
  // Match our pre-reference format: SR-XXXXXXXXX-XXXX (generated by generatePreRef())
  const match = combined.match(/\[?Ref(?:erence)?:\s*(SR-[A-Z0-9]{4,12}-[A-Z0-9]{2,8})\]?/i);
  return match?.[1] ?? null;
}

/**
 * Detect if email body contains a complaint about service or officer
 * Returns true if the content is likely a complaint.
 */
function isLikelyComplaint(body: string): boolean {
  const lower = body.toLowerCase();
  const complaintSignals = [
    'complaint', 'complain', 'unacceptable', 'unprofessional', 'rude', 'late', 'no show',
    'did not show', 'didn\'t show', 'not satisfied', 'terrible', 'horrible', 'awful',
    'disrespectful', 'not happy', 'very upset', 'disappointed', 'issue with',
    'problem with the officer', 'problem with your officer', 'i want to report',
    'sleeping on duty', 'on the phone', 'was not there', 'wasn\'t there',
  ];
  return complaintSignals.some((sig) => lower.includes(sig));
}

/**
 * Detect if an inbound email is an officer shift-offer acceptance reply
 * Looks for pattern: YES [Full Name] [Phone] (case-insensitive, permissive spacing)
 */
function parseOfficerAcceptanceReply(body: string): { isAcceptance: boolean; name?: string; phone?: string } {
  const text = body.trim().replace(/\s+/g, ' ');
  const match = text.match(/^yes\s+([a-z'\-\s]{3,40})\s+([\d\s\(\)\-\+\.]{7,20})/i);
  if (!match) return { isAcceptance: false };
  const name = match[1].trim();
  const phone = match[2].replace(/[^\d\+]/g, '').slice(0, 15);
  return { isAcceptance: true, name, phone };
}

/**
 * Look up workspace name + license number for initial greeting
 */
async function getWorkspaceDetails(workspaceId: string): Promise<{ name: string; licenseNumber?: string }> {
  try {
    const [ws] = await db.select({
      name: workspaces.name,
      stateLicenseNumber: workspaces.stateLicenseNumber,
    }).from(workspaces).where(eq(workspaces.id, workspaceId)).limit(1);
    return { name: ws?.name || 'Our Team', licenseNumber: ws?.stateLicenseNumber || undefined };
  } catch {
    return { name: 'Our Team' };
  }
}

/**
 * Generate a short reference number for pre-pipeline tracking
 */
function generatePreRef(): string {
  return `SR-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`;
}

const router = Router();

// Resend webhook signing secret for signature verification
const RESEND_WEBHOOK_SECRET = process.env.RESEND_WEBHOOK_SECRET;

/**
 * Verify Resend webhook signature using HMAC-SHA256 per Svix specification.
 *
 * Svix signed-content format (required):
 *   "{svix-id}.{svix-timestamp}.{rawBody}"
 *
 * The webhook signing secret is stored as a base64-encoded string (with an
 * optional "whsec_" prefix that must be stripped before decoding).
 */
function verifyResendSignature(
  payload: string,
  signature: string | undefined,
  timestamp: string | undefined,
  msgId: string | undefined
): boolean {
  // Fail-closed: if no secret is configured, REJECT all incoming webhooks.
  // This prevents unauthenticated webhook payloads from mutating platform state.
  if (!RESEND_WEBHOOK_SECRET) {
    log.error("[Resend Webhook] RESEND_WEBHOOK_SECRET is not set — rejecting webhook to prevent unauthenticated mutations. Configure the secret to enable webhook processing.");
    return false;
  }

  if (!signature || !timestamp || !msgId) {
    log.warn("[Resend Webhook] Missing svix-signature, svix-timestamp, or svix-id headers");
    return false;
  }

  // Replay protection: reject webhooks older than 5 minutes
  const timestampMs = parseInt(timestamp, 10) * 1000;
  if (isNaN(timestampMs) || Math.abs(Date.now() - timestampMs) > 5 * 60 * 1000) {
    log.warn("[Resend Webhook] Timestamp too old or invalid — possible replay attack");
    return false;
  }

  try {
    // Resend uses Svix format: v1,<base64-signature> (space-separated if multiple)
    const signatures = signature.split(" ");

    // Svix signed content: "{svix-id}.{svix-timestamp}.{rawBody}"
    const signedPayload = `${msgId}.${timestamp}.${payload}`;
    
    // Extract the actual secret (remove whsec_ prefix if present)
    const secretKey = RESEND_WEBHOOK_SECRET.startsWith("whsec_") 
      ? RESEND_WEBHOOK_SECRET.slice(6) 
      : RESEND_WEBHOOK_SECRET;
    
    // Svix stores the signing secret as base64-encoded bytes
    const secretBuffer = Buffer.from(secretKey, "base64");
    
    const expectedSig = crypto
      .createHmac("sha256", secretBuffer)
      .update(signedPayload)
      .digest("base64");
    
    for (const sig of signatures) {
      const [version, sigValue] = sig.split(",");
      
      if (version !== "v1" || !sigValue) continue;
      
      // Use constant-time comparison to prevent timing attacks
      try {
        if (crypto.timingSafeEqual(Buffer.from(sigValue), Buffer.from(expectedSig))) {
          return true;
        }
      } catch (compareError) {
        // Buffer length mismatch — signatures don't match, try next candidate
      }
    }
    
    log.warn(`[Resend Webhook] No matching signature found`);
    return false;
  } catch (error) {
    log.error("[Resend Webhook] Signature verification error:", error);
    return false;
  }
}

// ============================================================================
// DELIVERABILITY RATE MONITORING
// Fires on every bounce/complaint event and logs CRITICAL alert when
// bounce rate > 2% or complaint rate > 0.1% in a 24-hour window.
// These thresholds are industry standards: Google/Yahoo require <2% bounce,
// <0.1% complaint; exceeding them triggers deferrals or blocklisting.
// ============================================================================

const RATE_CHECK_WINDOW_MS = 24 * 60 * 60 * 1000; // 24 hours

export async function checkDeliverabilityRates(): Promise<void> {
  try {
    const since = new Date(Date.now() - RATE_CHECK_WINDOW_MS);
    const rows = await db.select({
      status: emailEvents.status,
      cnt: sql<number>`COUNT(*)::int`,
    })
    .from(emailEvents)
    .where(gte(emailEvents.createdAt, since))
    .groupBy(emailEvents.status);

    const totalSent = rows.reduce((sum, r) => sum + Number(r.cnt), 0);
    const bounces = rows.find(r => r.status === 'bounced');
    const complaints = rows.find(r => r.status === 'complained');
    const bounceCount = bounces ? Number(bounces.cnt) : 0;
    const complaintCount = complaints ? Number(complaints.cnt) : 0;

    if (totalSent === 0) return;

    const bounceRate = bounceCount / totalSent;
    const complaintRate = complaintCount / totalSent;

    if (bounceRate > EMAIL.bounceRateThreshold) {
      log.error(
        `[EMAIL DELIVERABILITY ALERT] CRITICAL: Bounce rate ${(bounceRate * 100).toFixed(2)}% exceeds threshold ${(EMAIL.bounceRateThreshold * 100).toFixed(1)}% ` +
        `(${bounceCount} bounces / ${totalSent} sent in last 24h). ` +
        `Immediate action required: review suppression list, remove invalid addresses, contact support@resend.com if sustained.`
      );
    }

    if (complaintRate > EMAIL.complaintRateThreshold) {
      log.error(
        `[EMAIL DELIVERABILITY ALERT] CRITICAL: Complaint rate ${(complaintRate * 100).toFixed(3)}% exceeds threshold ${(EMAIL.complaintRateThreshold * 100).toFixed(2)}% ` +
        `(${complaintCount} complaints / ${totalSent} sent in last 24h). ` +
        `Immediate action required: audit email content, check unsubscribe flow, and verify opt-in sources.`
      );
    }

    // Always log current rates at INFO level for observability
    log.info(
      `[Email Deliverability] 24h stats: ${totalSent} sent, ` +
      `${bounceCount} bounces (${(bounceRate * 100).toFixed(2)}%), ` +
      `${complaintCount} complaints (${(complaintRate * 100).toFixed(3)}%)`
    );
  } catch (err: unknown) {
    log.error('[Email Deliverability] Rate check failed:', err instanceof Error ? err.message : String(err));
  }
}

// Configuration for staffing email address
const STAFFING_EMAIL_CONFIG = {
  address: 'staffing@coaileague.com',
  domain: 'coaileague.com',
  aliases: [
    'staffing@coaileague.com',
    'work@coaileague.com',
    'jobs@coaileague.com',
    'requests@coaileague.com',
  ],
};

// Default workspace for platform-level work requests (can be overridden per org)
const PLATFORM_WORKSPACE_ID = process.env.PLATFORM_DEFAULT_WORKSPACE_ID;

interface ResendWebhookEvent {
  type: string;
  created_at: string;
  data: {
    email_id: string;
    from: string;
    to: string[];
    subject: string;
    created_at?: string;
    headers?: Record<string, string>;
    click?: {
      link: string;
      timestamp: string;
    };
    // Inbound email fields
    text?: string;
    html?: string;
    cc?: string[];
    bcc?: string[];
    reply_to?: string;
    attachments?: Array<{
      filename: string;
      content_type: string;
      size: number;
    }>;
  };
}

interface ResendInboundEmail {
  from: string;
  to: string[];
  cc?: string[];
  bcc?: string[];
  subject: string;
  text?: string;
  html?: string;
  reply_to?: string;
  headers?: Record<string, string>;
  attachments?: Array<{
    filename: string;
    content_type: string;
    content: string;
    size: number;
  }>;
  message_id?: string;
  date?: string;
}

/**
 * Check if an email address matches staffing email configuration
 */
function isStaffingEmail(email: string): boolean {
  const normalizedEmail = email.toLowerCase().trim();
  if (normalizedEmail === STAFFING_EMAIL_CONFIG.address) return true;
  if (STAFFING_EMAIL_CONFIG.aliases.includes(normalizedEmail)) return true;
  return false;
}

/**
 * Extract email slug from subdomain format only.
 * Pattern: function@{slug}.coaileague.com → returns slug
 * All other formats (dash-alias, plus-addressing) are deprecated and not supported.
 */
function extractSlugFromEmail(email: ResendInboundEmail): string | null {
  for (const toAddr of (email.to || [])) {
    const domain = toAddr.split('@')[1] || '';
    if (domain.endsWith('.coaileague.com') && domain !== 'coaileague.com') {
      return domain.replace('.coaileague.com', '');
    }
  }
  return null;
}

/**
 * Extract workspace ID from email headers or routing (legacy support)
 */
function extractWorkspaceFromEmail(email: ResendInboundEmail): string | null {
  // Check for workspace ID in headers (X-Workspace-ID)
  if (email.headers?.['x-workspace-id']) {
    return email.headers['x-workspace-id'];
  }

  // Check for workspace-specific email pattern: staffing+workspaceId@coaileague.com (legacy UUID format)
  for (const toAddr of email.to || []) {
    const match = toAddr.match(/^staffing\+([a-f0-9-]{36})@/i);
    if (match) {
      return match[1];
    }
  }

  return null;
}

/**
 * Send rejection email when org code is invalid or not found
 */
async function sendRejectionEmail(
  toEmail: string,
  fromName: string | undefined,
  subject: string,
  reason: string,
  suggestion?: string
): Promise<void> {
  try {
    const htmlBody = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%); padding: 20px; border-radius: 12px 12px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 24px;">Email Delivery Failed</h1>
        </div>

        <div style="background: #fef2f2; padding: 20px; border: 1px solid #fecaca; border-top: none; border-radius: 0 0 12px 12px;">
          <p style="color: #991b1b; margin: 0 0 15px 0; font-size: 16px;">
            <strong>Your email could not be processed</strong>
          </p>

          <p style="color: #7f1d1d; margin: 0 0 10px 0;">
            <strong>Subject:</strong> ${subject}
          </p>

          <p style="color: #7f1d1d; margin: 0 0 15px 0;">
            <strong>Reason:</strong> ${reason}
          </p>

          ${suggestion ? `
          <div style="background: white; padding: 15px; border-radius: 8px; margin-top: 15px;">
            <p style="color: #374151; margin: 0; font-size: 14px;">
              <strong>Suggestion:</strong> ${suggestion}
            </p>
          </div>
          ` : ''}

          <div style="margin-top: 20px; padding-top: 15px; border-top: 1px solid #fecaca;">
            <p style="color: #9ca3af; margin: 0; font-size: 12px;">
              This is an automated message from ${PLATFORM.name} Staffing Platform.
            </p>
          </div>
        </div>
      </div>
    `;

    await emailService.sendCustomEmail( // infra
      toEmail,
      `Re: ${subject} - Delivery Failed`,
      htmlBody,
      'email_rejection',
      undefined // No workspace ID for system rejections
    );

  } catch (error) {
    log.error(`[Resend Inbound] Failed to send rejection email to ${toEmail}:`, error);
  }
}

/**
 * Main Resend webhook endpoint - handles all email events
 */
router.post("/api/webhooks/resend", async (req, res) => {
  try {
    // Signature verification — fail-closed: reject if no secret is configured.
    // This prevents unauthenticated actors from spoofing bounce/complaint events
    // to suppress email addresses or manipulate delivery state.
    const outboundSignature = req.headers["svix-signature"] as string | undefined;
    const outboundTimestamp = req.headers["svix-timestamp"] as string | undefined;
    const outboundMsgId = req.headers["svix-id"] as string | undefined;
    const outboundRawBody = (req as any).rawBody || JSON.stringify(req.body);

    if (!verifyResendSignature(outboundRawBody, outboundSignature, outboundTimestamp, outboundMsgId)) {
      log.error("[Resend Webhook] Signature verification failed — rejecting outbound event webhook");
      return res.status(401).json({ error: "Invalid signature" });
    }

    const event: ResendWebhookEvent = req.body;

    if (!event || typeof event.type !== 'string') {
      log.error("[Resend Webhook] Malformed payload — missing event.type (type=%s)", typeof event?.type);
      return res.status(400).json({ error: "Invalid webhook payload" });
    }

    // Idempotency guard: deduplicate Resend webhook deliveries using svix-id header
    const svixId = req.headers['svix-id'] as string | undefined;
    if (svixId) {
      try {
        // CATEGORY C — Raw SQL retained: LIMIT | Tables: resend_webhook_events | Verified: 2026-03-23
        const existing = await typedQuery(
          sql`SELECT id FROM resend_webhook_events WHERE message_id = ${svixId} LIMIT 1`
        );
        if (existing.length > 0) {
          return res.status(200).json({ received: true, processed: false, reason: 'duplicate_delivery' });
        }
        // Converted to Drizzle ORM: ON CONFLICT
        await db.insert(resendWebhookEvents).values({
          messageId: svixId,
          eventType: event.type,
        }).onConflictDoNothing();
      } catch (idempotencyErr: unknown) {
        log.warn('[Resend Webhook] Idempotency check failed (non-blocking):', (idempotencyErr instanceof Error ? idempotencyErr.message : String(idempotencyErr)));
      }
    }
    
    switch (event.type) {
      case "email.delivered": {
        // Extract invoiceId from Resend tags set at send time
        const tags: Array<{ name: string; value: string }> = (event as any).data.tags || [];
        const invoiceTag = tags.find((t) => t.name === 'invoiceId');
        if (invoiceTag?.value) {
          const invoiceId = invoiceTag.value;
          try {
            // Fetch the invoice so we can include workspaceId in the audit entry
            const [inv] = await db
              .select({ id: invoices.id, workspaceId: invoices.workspaceId, invoiceNumber: invoices.invoiceNumber })
              .from(invoices)
              .where(eq(invoices.id, invoiceId))
              .limit(1);

            if (inv) {
              // Flip delivery_confirmed = true
              await db
                .update(invoices)
                .set({ deliveryConfirmed: true })
                .where(eq(invoices.id, invoiceId));

              // Write immutable audit trail entry
              await universalAudit.log({
                workspaceId: inv.workspaceId,
                action: 'invoice.delivery_confirmed' as any,
                actorType: 'system',
                actorId: 'resend-webhook',
                changeType: 'action',
                entityType: 'invoice',
                entityId: invoiceId,
                entityName: inv.invoiceNumber,
                metadata: {
                  invoiceNumber: inv.invoiceNumber,
                  deliveredTo: event.data.to?.join(', '),
                  resendEventAt: (event as any).data.created_at || new Date().toISOString(),
                  source: 'resend_email.delivered_webhook',
                },
              });

              log.info(`[Resend Webhook] delivery_confirmed=true for invoice ${inv.invoiceNumber} (${invoiceId})`);
            } else {
              log.warn(`[Resend Webhook] email.delivered — no invoice found for id: ${invoiceId}`);
            }
          } catch (dbErr: unknown) {
            log.error(`[Resend Webhook] Failed to update delivery_confirmed for invoice ${invoiceId}:`, (dbErr instanceof Error ? dbErr.message : String(dbErr)));
          }
        } else {
          log.info(`[Resend Webhook] email.delivered — no invoiceId tag, skipping delivery_confirmed update`);
        }
        break;
      }

      case "email.bounced": {
        // Hard bounces signal invalid/dead addresses. Auto-suppress to protect sender reputation.
        const bouncedAddresses: string[] = event.data.to ?? [];
        const bounceResendId: string = (event as any).data.id || '';
        log.error(`[Resend] Hard bounce for ${bouncedAddresses.join(", ")}`);
        for (const email of bouncedAddresses) {
          try {
            await db.insert(emailUnsubscribes)
              .values({
                email,
                workspaceId: null, // bounce applies globally across all workspaces
                unsubscribeAll: true,
                unsubscribeToken: crypto.randomBytes(32).toString('hex'),
                unsubscribeSource: 'bounce',
                unsubscribeReason: `Hard bounce reported by Resend — email ID: ${(event as any).data.id}`,
              })
              .onConflictDoNothing(); // unique constraint on (email, workspaceId) may fire
          } catch (err: unknown) {
            log.error('[Resend] Failed to suppress bounced address:', email, (err instanceof Error ? err.message : String(err)));
          }
        }
        // Update emailEvents record so delivery status reflects the actual outcome
        if (bounceResendId) {
          try {
            await db.update(emailEvents)
              .set({ status: 'bounced', updatedAt: new Date() })
              .where(eq(emailEvents.resendId, bounceResendId));
          } catch (err: unknown) {
            log.error('[Resend] Failed to update emailEvents on bounce:', bounceResendId, (err instanceof Error ? err.message : String(err)));
          }
        }
        // GAP-S30-01 FIX: Sync bounce outcome back to notification_deliveries (Phase 27 delivery tracking)
        // Marks any 'sent' or 'pending' email channel delivery records for these recipients as failed.
        if (bouncedAddresses.length > 0) {
          try {
            await db.update(notificationDeliveries)
              .set({
                status: 'failed',
                lastError: `Hard bounce reported by Resend — email ID: ${bounceResendId}`,
                updatedAt: new Date(),
              })
              .where(
                and(
                  inArray(notificationDeliveries.recipientUserId, bouncedAddresses),
                  eq(notificationDeliveries.channel, 'email'),
                  inArray(notificationDeliveries.status, ['sent', 'pending'])
                )
              );
          } catch (err: unknown) {
            log.error('[Resend] Failed to sync bounce to notification_deliveries:', (err instanceof Error ? err.message : String(err)));
          }
        }
        // Fire-and-forget rate check — logs CRITICAL alert if 24h bounce rate > threshold
        checkDeliverabilityRates().catch((err: any) => log.warn('[EventBus] Publish failed (non-blocking):', err?.message));
        break;
      }
        
      case "email.complained": {
        // Spam complaints damage sender reputation. Auto-suppress immediately.
        const complainedAddresses: string[] = event.data.to ?? [];
        const complaintResendId: string = (event as any).data.id || '';
        log.error(`[Resend] Spam complaint from ${complainedAddresses.join(", ")}`);
        for (const email of complainedAddresses) {
          try {
            await db.insert(emailUnsubscribes)
              .values({
                email,
                workspaceId: null, // complaint applies globally
                unsubscribeAll: true,
                unsubscribeToken: crypto.randomBytes(32).toString('hex'),
                unsubscribeSource: 'complaint',
                unsubscribeReason: `Spam complaint reported by Resend — email ID: ${(event as any).data.id}`,
              })
              .onConflictDoNothing();
          } catch (err: unknown) {
            log.error('[Resend] Failed to suppress complained address:', email, (err instanceof Error ? err.message : String(err)));
          }
        }
        // Update emailEvents record so delivery status reflects the actual outcome
        if (complaintResendId) {
          try {
            await db.update(emailEvents)
              .set({ status: 'complained', updatedAt: new Date() })
              .where(eq(emailEvents.resendId, complaintResendId));
          } catch (err: unknown) {
            log.error('[Resend] Failed to update emailEvents on complaint:', complaintResendId, (err instanceof Error ? err.message : String(err)));
          }
        }
        // GAP-S30-01 FIX: Sync complaint outcome back to notification_deliveries (Phase 27 delivery tracking)
        if (complainedAddresses.length > 0) {
          try {
            await db.update(notificationDeliveries)
              .set({
                status: 'failed',
                lastError: `Spam complaint reported by Resend — email ID: ${complaintResendId}`,
                updatedAt: new Date(),
              })
              .where(
                and(
                  inArray(notificationDeliveries.recipientUserId, complainedAddresses),
                  eq(notificationDeliveries.channel, 'email'),
                  inArray(notificationDeliveries.status, ['sent', 'pending'])
                )
              );
          } catch (err: unknown) {
            log.error('[Resend] Failed to sync complaint to notification_deliveries:', (err instanceof Error ? err.message : String(err)));
          }
        }
        // Fire-and-forget rate check — logs CRITICAL alert if 24h complaint rate > threshold
        checkDeliverabilityRates().catch((err: any) => log.warn('[EventBus] Publish failed (non-blocking):', err?.message));
        break;
      }
        
      default:
        break;
    }
    
    res.status(200).json({ received: true });
  } catch (error) {
    log.error("[Resend Webhook] Error processing event:", error);
    res.status(500).json({ error: "Webhook processing failed" });
  }
});

/**
 * Resend Inbound Email Webhook - receives emails sent to staffing@coaileague.com
 * 
 * Configure in Resend Dashboard:
 * 1. Go to Resend Dashboard > Domains > coaileague.com
 * 2. Add MX record: 10 inbound.resend.com
 * 3. Create inbound webhook: https://coaileague.com/api/webhooks/resend/inbound
 * 4. Map staffing@coaileague.com to this webhook
 */
router.post("/api/webhooks/resend/inbound", async (req, res) => {
  try {
    // Verify webhook signature (Resend uses Svix)
    const signature = req.headers["svix-signature"] as string | undefined;
    const timestamp = req.headers["svix-timestamp"] as string | undefined;
    const msgId = req.headers["svix-id"] as string | undefined;
    // Use raw body captured by middleware for proper signature verification
    // (JSON.stringify(req.body) may produce different formatting than the original payload)
    const rawBody = (req as any).rawBody || JSON.stringify(req.body);
    
    // Fail-closed: verifyResendSignature() already rejects when no secret is configured.
    // Removing the outer `if (RESEND_WEBHOOK_SECRET &&...)` guard so we never accept
    // unauthenticated inbound payloads — even when the secret env-var is missing.
    if (!verifyResendSignature(rawBody, signature, timestamp, msgId)) {
      log.error("[Resend Inbound] Invalid webhook signature - rejecting request");
      if (RESEND_WEBHOOK_SECRET) {
        log.error(`[Resend Inbound] Secret starts with: ${RESEND_WEBHOOK_SECRET.substring(0, 15)}...`);
      }
      return res.status(401).json({ error: "Invalid signature" });
    }

    // Idempotency guard: deduplicate using svix-id header
    const svixId = req.headers['svix-id'] as string | undefined;
    if (svixId) {
      try {
        // CATEGORY C — Raw SQL retained: LIMIT | Tables: resend_webhook_events | Verified: 2026-03-23
        const existing = await typedQuery(
          sql`SELECT id FROM resend_webhook_events WHERE message_id = ${svixId} LIMIT 1`
        );
        if (existing.length > 0) {
          return res.status(200).json({ received: true, processed: false, reason: 'duplicate_delivery' });
        }
        // Converted to Drizzle ORM: ON CONFLICT
        await db.insert(resendWebhookEvents).values({
          messageId: svixId,
          eventType: 'inbound',
        }).onConflictDoNothing();
      } catch (idempotencyErr: unknown) {
        log.warn('[Resend Inbound] Idempotency check failed (non-blocking):', (idempotencyErr instanceof Error ? idempotencyErr.message : String(idempotencyErr)));
      }
    }
    
    const inboundEmail: ResendInboundEmail = req.body;

    // ─── STEP 1: Platform protected address routing ───────────────────────────
    // Check FIRST if this is addressed to a protected CoAIleague platform address.
    // These addresses never go through workspace routing.
    // trinity@, support@, info@, billing@, hello@ → all on coaileague.com root domain.
    const PLATFORM_ROOT_ADDRESSES: Record<string, string> = {
      'trinity@coaileague.com':  'trinity_direct',
      'support@coaileague.com':  'support_ticket',
      'info@coaileague.com':     'support_ticket',
      'billing@coaileague.com':  'billing_inquiry',
      'hello@coaileague.com':    'general_inquiry',
      'root@coaileague.com':     'internal_only',
      'noreply@coaileague.com':  'discard',
    };

    const toAddrs = (inboundEmail.to || []).map(a => a.toLowerCase().trim());
    const platformAddr = toAddrs.find(a => PLATFORM_ROOT_ADDRESSES[a]);

    if (platformAddr) {
      const routeType = PLATFORM_ROOT_ADDRESSES[platformAddr];

      // Silently discard noreply@ and internal-only addresses
      if (routeType === 'discard' || routeType === 'internal_only') {
        log.info(`[Resend Inbound] Discarding email to ${platformAddr} (${routeType})`);
        return res.status(200).json({ received: true, processed: false, reason: routeType });
      }

      const fromRaw = inboundEmail.from || '';
      const fromEmail = fromRaw.match(/<([^>]+)>/)?.[1]?.trim() || fromRaw.trim();
      const fromName = fromRaw.split('<')[0].trim() || undefined;
      const emailBody = inboundEmail.text || (inboundEmail.html || '').replace(/<[^>]*>/g, ' ');
      const subject = inboundEmail.subject || '(no subject)';

      log.info(`[Resend Inbound] Platform address: ${platformAddr} (${routeType}) from ${fromEmail}`);

      // Store in platform_emails as a platform-level (no workspace) email
      try {
        const { pool: rawPool } = await import('../db');
        const msgId = `<${Date.now()}.inbound@coaileague.com>`;
        await rawPool.query(`
          INSERT INTO platform_emails (
            resend_email_id, message_id, direction,
            from_address, from_name, to_addresses,
            subject, body_text, body_html, snippet,
            folder, is_read, trinity_processed, received_at
          ) VALUES ($1,$2,'inbound',$3,$4,$5,$6,$7,$8,$9,'inbox',false,false,NOW())
          ON CONFLICT (resend_email_id) DO NOTHING
        `, [
          (inboundEmail as any).id || msgId,
          msgId, fromEmail, fromName || null,
          [platformAddr], subject,
          emailBody.slice(0, 50000),
          inboundEmail.html?.slice(0, 50000) || null,
          emailBody.slice(0, 200),
        ]);
      } catch (storeErr: any) {
        log.warn('[Resend Inbound] Failed to store platform email:', storeErr.message);
      }

      // Async processing per platform address type — non-blocking
      if (routeType !== 'discard' && fromEmail) {
        scheduleNonBlocking('resend-inbound.platform-reply', async () => {
          try {
            if (platformAddr === 'trinity@coaileague.com') {
              // trinity@ is reserved for outbound marketing + reply classification.
              // Inbound replies are classified into REGULATORY or PROSPECT lanes.
              log.info(`[TrinityMarketing] Marketing reply received at trinity@ — classifying sender lane`);
              const { processTrinityMarketingReply } = await import('../services/trinityMarketingReplyProcessor');
              const { getUncachableResendClient } = await import('../services/emailCore');
              const { client } = await getUncachableResendClient();
              await processTrinityMarketingReply(
                { from: fromEmail, fromName, subject, body: emailBody },
                async ({ to, subject: replySubject, text }) => {
                  await client.emails.send({
                    from: 'Trinity <trinity@coaileague.com>',
                    to: [to],
                    replyTo: 'trinity@coaileague.com',
                    subject: replySubject,
                    text,
                  });
                }
              );
            } else {
              // support@, info@, billing@, hello@ → generic support acknowledgement
              const prompt = `You are a CoAIleague support assistant. This email to ${platformAddr} is from ${fromName || fromEmail}.\n\nSubject: ${subject}\n\n${emailBody.slice(0, 3000)}\n\nAcknowledge receipt, provide helpful information if possible, and let them know a support agent will follow up within 1 business day. Be professional and concise.`;

              const aiResp = await meteredGemini.generate({
                workspaceId: 'PLATFORM',
                feature: 'platform_support',
                prompt,
                // @ts-expect-error — TS migration: fix in refactoring sprint
                billedTo: 'platform',
              });

              if (aiResp?.text && aiResp.text.length > 30) {
                const { getUncachableResendClient } = await import('../services/emailCore');
                const { client } = await getUncachableResendClient();
                await client.emails.send({
                  from: `${PLATFORM.name} Support <support@${PLATFORM.domain}>`,
                  to: [fromEmail],
                  replyTo: 'support@coaileague.com',
                  subject: `Re: ${subject}`,
                  text: aiResp.text.trim(),
                });
                log.info(`[Platform Support] Replied to ${fromEmail} re: "${subject}"`);
              }
            }
          } catch (trinityErr: any) {
            log.warn('[Trinity Platform] Processing failed (non-blocking):', trinityErr.message);
          }
        });
      }

      return res.status(200).json({ received: true, processed: true, route: platformAddr, routeType });
    }

    // ─── STEP 2: Workspace email routing ─────────────────────────────────────
    // Single extraction path: subdomain format only.
    //   staffing@slug.coaileague.com → slug resolved to workspace_id
    // Dash-alias and plus-addressing formats are deprecated and no longer supported.

    const isRoutableEmail = toAddrs.some(addr => {
      const domain = addr.split('@')[1] || '';
      // Only subdomain format: any local part at {slug}.coaileague.com
      return domain.endsWith('.coaileague.com') && domain !== 'coaileague.com';
    });

    // Determine the email category for internal routing metadata
    const emailCategory = (() => {
      const addr = toAddrs[0] || '';
      const local = addr.split('@')[0].split(/[+-]/)[0];
      if (['calloffs', 'calloff', 'callout'].includes(local)) return 'calloff';
      if (['incidents', 'incident', 'report'].includes(local)) return 'incident';
      if (['docs', 'documents'].includes(local)) return 'document';
      if (['support', 'help'].includes(local)) return 'support';
      if (['billing'].includes(local)) return 'billing';
      return 'staffing';
    })();

    if (!isRoutableEmail) {
      return res.status(200).json({ received: true, processed: false, reason: 'Not a routable platform email' });
    }

    log.info(`[Resend Inbound] Received ${emailCategory} email from ${inboundEmail.from} → ${inboundEmail.to?.join(', ')}`);

    // Extract sender email for rejection replies
    const senderEmail = inboundEmail.from?.match(/<([^>]+)>/)?.[1] || inboundEmail.from;
    const senderName = inboundEmail.from?.split('<')[0]?.trim();

    // ============================================================================
    // WORKSPACE ROUTING — subdomain slug extraction (single path)
    // Pattern: function@{slug}.coaileague.com → slug → workspace_id
    // ============================================================================
    const slug = extractSlugFromEmail(inboundEmail);
    let workspaceId: string | null = null;
    let workspaceName: string | undefined;

    if (slug) {
      const slugLookup = await lookupWorkspaceByEmailSlug(slug);
      if (slugLookup.found) {
        workspaceId = slugLookup.workspaceId!;
        workspaceName = slugLookup.workspaceName;
        log.info(`[Resend Inbound] Subdomain routing: slug="${slug}" → workspace ${workspaceId}`);
      } else {
        log.warn(`[Resend Inbound] Subdomain slug "${slug}" not found — unresolvable address`);
        return res.status(200).json({
          received: true,
          processed: false,
          reason: 'Unresolvable slug',
          slug,
        });
      }
    } else {
      // No subdomain slug — email sent to a root @coaileague.com address not in the protected list
      log.info('[Resend Inbound] Platform-level inbound received, routing to support queue — no tenant slug detected');
      workspaceId = PLATFORM_WORKSPACE_ID || null;
    }

    if (!workspaceId) {
      log.error(`[Resend Inbound] No workspace resolved for inbound email`);
      if (senderEmail) {
        await sendRejectionEmail(
          senderEmail,
          senderName,
          inboundEmail.subject || 'Work Request',
          'Your email could not be routed to an organization.',
          'Please send your request to the correct address: function@yourorgslug.coaileague.com'
        );
      }
      return res.status(200).json({
        received: true,
        processed: false,
        reason: 'No workspace resolved',
        rejectionSent: !!senderEmail,
      });
    }

    const emailBody = inboundEmail.text || inboundEmail.html?.replace(/<[^>]*>/g, ' ') || '';

    // ============================================================================
    // TRINITY EMAIL REPLY HANDLER
    // If client replies to a Trinity email (reference number detected in subject),
    // Trinity handles the conversation using org credits. Complaints are auto-filed.
    // ============================================================================
    const inboundSubject = inboundEmail.subject || '';
    const trinityRef = extractTrinityRefNumber(inboundSubject, emailBody);

    if (trinityRef && workspaceId && senderEmail) {
      log.info(`[Trinity Liaison] Reply detected [Ref: ${trinityRef}] from ${senderEmail}`);
      try {
        // Look up or create the conversation record
        let [conversation] = await db
          .select()
          .from(trinityEmailConversations)
          .where(
            and(
              eq(trinityEmailConversations.referenceNumber, trinityRef),
              eq(trinityEmailConversations.workspaceId, workspaceId)
            )
          )
          .limit(1);

        if (!conversation) {
          // Create conversation record for first reply
          const [created] = await db.insert(trinityEmailConversations).values({
            workspaceId,
            referenceNumber: trinityRef,
            clientEmail: senderEmail,
            clientName: senderName,
            conversationType: 'staffing_inquiry',
            status: 'active',
          }).returning();
          conversation = created;
        }

        const complaintDetected = isLikelyComplaint(emailBody);

        // Build Trinity's context-aware prompt
        const wsDetails = await getWorkspaceDetails(workspaceId);
        const prompt = `You are Trinity, the AI staffing coordinator for ${wsDetails.name}, a CoAIleague member security provider.

A client has replied to your previous email regarding reference ${trinityRef}.

CLIENT EMAIL FROM: ${senderName || senderEmail}
CLIENT MESSAGE:
"""
${emailBody.substring(0, 2000)}
"""

${complaintDetected ? `IMPORTANT: This appears to contain a complaint or concern. Acknowledge it empathetically, let them know it has been logged and a case manager will follow up. Do NOT minimize or dismiss the concern.` : `Respond helpfully to their inquiry. If they are asking about staffing status, let them know the team is processing their request. If they have a small question you can answer, answer it. If they want to change requirements, acknowledge and say it will be relayed to the team.`}

ALWAYS end your response by recommending they use the Client Portal for all ongoing communication, document tracking, and issue resolution — as it provides the best tracking and fastest response times.

Keep your response concise (3-5 sentences), professional, and warm. Do NOT make promises about specific staff members or schedules. Sign off as: Trinity | AI Staffing Coordinator — ${wsDetails.name}`;

        // Generate Trinity's response using org credits
        let trinityReply = `Thank you for reaching out. Your message has been received and our team will follow up shortly. For faster response and full tracking of your request, we recommend using your Client Portal. — Trinity | AI Staffing Coordinator — ${wsDetails.name}`;

        try {
          const aiResp = await meteredGemini.generate({
            workspaceId,
            feature: 'trinity_staffing',
            prompt,
            // @ts-expect-error — TS migration: fix in refactoring sprint
            billedTo: 'org',
          });
          if (aiResp?.text && aiResp.text.length > 30) {
            trinityReply = aiResp.text.trim();
          }
        } catch (aiErr: unknown) {
          log.warn('[Trinity Liaison] AI generation failed, using fallback reply:', (aiErr instanceof Error ? aiErr.message : String(aiErr)));
        }

        // Update conversation stats
        await db.update(trinityEmailConversations).set({
          messageCount: (conversation.messageCount ?? 0) + 1,
          totalCreditsUsed: (conversation.totalCreditsUsed ?? 0) + 10,
          lastActivityAt: new Date(),
        }).where(eq(trinityEmailConversations.id, conversation.id));

        // If complaint detected, file it against the workspace (no specific officer yet)
        if (complaintDetected) {
          try {
            // Find the most recently scheduled employee in this workspace as the potential subject
            // In a real scenario, client would specify the officer. For now, we just log the complaint
            // against the workspace for manager review.
            log.info(`[Trinity Liaison] Complaint flagged from ${senderEmail} — logging for manager review`);

            // Update conversation type to complaint
            await db.update(trinityEmailConversations).set({
              conversationType: 'complaint',
            }).where(eq(trinityEmailConversations.id, conversation.id));
          } catch (complaintErr: unknown) {
            log.warn('[Trinity Liaison] Failed to log complaint:', (complaintErr instanceof Error ? complaintErr.message : String(complaintErr)));
          }
        }

        // Send Trinity's reply back to the client
        await emailService.sendCustomEmail( // infra
          senderEmail,
          `Re: Your Staffing Request — ${wsDetails.name} [Ref: ${trinityRef}]`,
          `<table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial,sans-serif;background-color:#e8edf2;">
            <tr><td align="center" style="padding:8px 6px;">
            <div style="max-width:600px;width:100%;margin:0 auto;">
            <div style="background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 50%, #1e40af 100%); padding: 20px; border-radius: 12px 12px 0 0; text-align: center;">
              <p style="color:#93c5fd;margin:0 0 4px 0;font-size:12px;letter-spacing:2px;text-transform:uppercase;">${PLATFORM.name} Staffing Network</p>
              <h2 style="color:white;margin:0;font-size:20px;font-weight:700;">${wsDetails.name}</h2>
            </div>
            <div style="padding:24px 16px;background-color:#f8fafc;border-radius:0 0 12px 12px;">
              <p style="font-size:15px;color:#1e293b;margin:0 0 16px 0;">Hello ${senderName || 'there'},</p>
              <div style="color:#334155;font-size:14px;line-height:1.8;white-space:pre-line;">${trinityReply}</div>
              <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0 16px 0;">
              <p style="color:#94a3b8;font-size:11px;margin:0;text-align:center;">
                ${wsDetails.name} | ${PLATFORM.name} Staffing Network | Ref: ${trinityRef}
              </p>
            </div>
            </div>
            </td></tr>
          </table>`,
          'trinity_email_reply',
          workspaceId
        );

        log.info(`[Trinity Liaison] Reply sent to ${senderEmail} [Ref: ${trinityRef}]`);

        return res.status(200).json({
          received: true,
          processed: true,
          type: 'trinity_liaison_reply',
          referenceNumber: trinityRef,
          complaintFlagged: complaintDetected,
        });

      } catch (liaisonErr: unknown) {
        log.error('[Trinity Liaison] Handler error:', (liaisonErr instanceof Error ? liaisonErr.message : String(liaisonErr)));
        // Don't block — fall through to regular processing
      }
    }

    // ============================================================================
    // OFFICER REPLY ACCEPTANCE DETECTION
    // If an officer replies "YES John Smith 713-555-1234", handle the acceptance
    // ============================================================================
    const acceptanceResult = parseOfficerAcceptanceReply(emailBody);

    if (acceptanceResult.isAcceptance && senderEmail) {
      log.info(`[Resend Inbound] Officer acceptance reply detected from ${senderEmail}`);
      try {
        // Find the employee by their email address
        const [officer] = await db.select()
          .from(employees)
          .where(and(
            eq(employees.workspaceId, workspaceId),
            eq(employees.email, senderEmail)
          ))
          .limit(1);

        if (officer) {
          // Find any open shift offer in this workspace — most recent pending
          const { stagedShifts } = await import('@shared/schema');
          const [openShift] = await db.select()
            // @ts-expect-error — TS migration: fix in refactoring sprint
            .where(and(
              eq(stagedShifts.workspaceId, workspaceId),
              eq(stagedShifts.status, 'offers_sent')
            ))
            .orderBy(stagedShifts.createdAt)
            .limit(1);

          if (openShift) {
            // Update the staged shift to accepted state
            await db.update(stagedShifts)
              .set({
                status: 'partially_assigned',
                updatedAt: new Date(),
              })
              .where(eq(stagedShifts.id, openShift.id));

            log.info(`[Resend Inbound] Officer ${officer.firstName} ${officer.lastName} accepted shift ${openShift.id}`);

            // Send confirmation to the officer
            await emailService.sendCustomEmail( // infra
              senderEmail,
              `Assignment Confirmed — ${workspaceName || 'Your Staffing Agency'}`,
              `<div style="font-family:Arial,sans-serif;max-width:500px;margin:0 auto;padding:30px;">
                <h2 style="color:#16a34a;">Assignment Confirmed!</h2>
                <p>Hi ${officer.firstName || acceptanceResult.name},</p>
                <p>Your acceptance has been received. You are confirmed for the assignment. Full details will follow shortly.</p>
                <p style="color:#64748b;font-size:13px;">Thank you for your prompt response.</p>
                <p style="color:#64748b;font-size:13px;">— ${workspaceName || 'Your Staffing Team'}</p>
              </div>`,
              'officer_acceptance_confirmation',
              workspaceId
            );
          }
        } else {
          log.warn(`[Resend Inbound] Officer acceptance from unknown email: ${senderEmail}`);
        }
      } catch (acceptErr: unknown) {
        log.error('[Resend Inbound] Officer acceptance error:', (acceptErr instanceof Error ? acceptErr.message : String(acceptErr)));
      }

      return res.status(200).json({
        received: true,
        processed: true,
        type: 'officer_acceptance',
        officer: acceptanceResult.name,
        workspaceId,
      });
    }

    // ============================================================================
    // TRINITY AI GREETING — ai-written first-response before pipeline
    // Gemini generates a job summary from the raw email body; Trinity signs off.
    // ============================================================================
    const preRef = generatePreRef();
    try {
      const wsDetails = await getWorkspaceDetails(workspaceId);
      const orgEmailAddress = inboundEmail.to?.[0] || `staffing@coaileague.com`;
      const rawBody = inboundEmail.text || inboundEmail.html?.replace(/<[^>]*>/g, ' ') || '';

      // Generate concise job summary with Gemini (non-blocking fallback on error)
      let jobSummary = rawBody.length > 20 ? rawBody.substring(0, 600) : 'No additional details were provided in the request.';
      try {
        const geminiResp = await meteredGemini.generate({
          workspaceId,
          feature: 'trinity_staffing',
          prompt: `You are Trinity, an AI staffing coordinator for a security company. A client just sent the following staffing request email. Write a short, professional 3–5 sentence summary of what they need. Include: the type of officer requested (armed/unarmed/etc), location if mentioned, date(s) and hours if mentioned, number of officers, and any special requirements. Be factual and concise. Do NOT add any headers or salutations — just the summary paragraph.

Client email:
"""
${rawBody.substring(0, 2000)}
"""`,
          // @ts-expect-error — TS migration: fix in refactoring sprint
          billedTo: 'system',
        });
        if (geminiResp?.text && geminiResp.text.length > 20) {
          jobSummary = geminiResp.text.trim();
        }
      } catch (gemErr: unknown) {
        log.warn('[Resend Inbound] Gemini job summary generation failed (using raw body):', (gemErr instanceof Error ? gemErr.message : String(gemErr)));
      }

      await emailService.sendTrinityAIGreeting({ // infra
        workspaceId,
        senderEmail,
        senderName,
        workspaceName: wsDetails.name,
        licenseNumber: wsDetails.licenseNumber,
        referenceNumber: preRef,
        orgEmail: orgEmailAddress,
        jobSummary,
      });
      log.info(`[Resend Inbound] Trinity AI greeting sent to ${senderEmail} [Ref: ${preRef}]`);
    } catch (greetErr: unknown) {
      log.warn('[Resend Inbound] Failed to send Trinity AI greeting:', (greetErr instanceof Error ? greetErr.message : String(greetErr)));
    }

    // Process as inbound opportunity (work request)
    // Map Resend fields to the expected agent format
    const result = await inboundOpportunityAgent.processInboundEmail(workspaceId, {
      messageId: inboundEmail.message_id || `resend-${Date.now()}`,
      fromEmail: inboundEmail.from || 'unknown@unknown.com',
      fromName: senderName || undefined,
      toEmail: inboundEmail.to?.[0],
      subject: inboundEmail.subject || 'No Subject',
      bodyText: inboundEmail.text || inboundEmail.html?.replace(/<[^>]*>/g, ' ') || '',
      bodyHtml: inboundEmail.html,
      hasAttachments: (inboundEmail.attachments?.length || 0) > 0,
      attachmentCount: inboundEmail.attachments?.length || 0,
    });

    // ============================================================================
    // TRINITY PROACTIVE NEW CLIENT DETECTION
    // If the sender is not an existing client, create a prospect and notify owner.
    // Trinity will surface this in the next owner/manager chat session.
    // ============================================================================
    let isNewProspect = false;
    let prospectTempCode: string | null = null;
    try {
      if (senderEmail && workspaceId) {
        const normalizedSenderEmail = senderEmail.toLowerCase();
        const existingClient = await db.query.clients.findFirst({
          where: and(
            eq(clients.workspaceId, workspaceId),
            sql`LOWER(${clients.email}) = ${normalizedSenderEmail}`,
          ),
        });

        if (!existingClient) {
          const { clientProspectService } = await import('../services/clientProspectService');
          const { prospect, isNew, tempCode } = await clientProspectService.getOrCreateFromEmail({
            workspaceId,
            email: normalizedSenderEmail,
            contactName: senderName || undefined,
            sourceEmailId: inboundEmail.message_id || undefined,
          });
          isNewProspect = isNew;
          prospectTempCode = tempCode;

          if (isNew) {
            const { universalNotificationEngine } = await import('../services/universalNotificationEngine');
            await universalNotificationEngine.sendNotification({
              workspaceId,
              type: 'new_staffing_inquiry',
              title: 'New Client Inquiry — Trinity Action Required',
              message: `${senderName || senderEmail} submitted a staffing request. They are not yet in your client list. Trinity can create their client record and send a portal invite — open Trinity chat to review.`,
              metadata: {
                senderEmail: normalizedSenderEmail,
                senderName: senderName || null,
                subject: inboundEmail.subject || null,
                tempCode,
                prospectId: prospect.id,
                trinityAction: 'new_client_onboarding',
                emailSnippet: emailBody.substring(0, 300),
              },
              severity: 'warning',
            });
            log.info(`[Resend Inbound] New prospect detected: ${normalizedSenderEmail} → tempCode=${tempCode}, owner notified`);
          }
        }
      }
    } catch (prospectErr: unknown) {
      log.warn('[Resend Inbound] Prospect detection error (non-blocking):', (prospectErr instanceof Error ? prospectErr.message : String(prospectErr)));
    }

    res.status(200).json({
      received: true,
      processed: true,
      workspaceId,
      workspaceName,
      // @ts-expect-error — TS migration: fix in refactoring sprint
      orgCode: orgCode || undefined,
      isNewProspect,
      prospectTempCode: prospectTempCode || undefined,
      result,
    });
  } catch (error: unknown) {
    log.error("[Resend Inbound] Error processing inbound email:", error);
    res.status(500).json({ error: "Inbound email processing failed", message: sanitizeError(error) });
  }
});

/**
 * DEV/TEST: Simulate inbound email (bypasses signature verification)
 * Only available in development mode
 */
router.post("/api/webhooks/resend/inbound/test", async (req, res) => {
  if (process.env.NODE_ENV === 'production') {
    return res.status(403).json({ error: "Test endpoint disabled in production" });
  }

  const testEmail = req.body || {
    from: "sarah.johnson@prestigesecurity.com",
    to: ["staffing-txpi@coaileague.com"],
    subject: "Need armed guard for warehouse site - March 15",
    text: "Hi, we need 1 armed security guard at 4500 Industrial Blvd, Houston TX 77023 on March 15, 2026 from 6:00 PM to 6:00 AM. Pay rate $28/hour. Must have Level III armed guard license and clean background. Contact: Sarah Johnson, 832-555-1234, sarah.johnson@prestigesecurity.com. Please also find our service contract attached for your records.",
    message_id: `test-${Date.now()}`,
    attachments: req.body?.attachments || [],
  };

  try {
    const senderEmail = testEmail.from?.match(/<([^>]+)>/)?.[1] || testEmail.from;
    const senderName = testEmail.from?.split('<')[0]?.trim();

    // @ts-expect-error — TS migration: fix in refactoring sprint
    const orgCode = extractOrgCodeFromEmail(testEmail);
    let workspaceId: string | null = null;
    let workspaceName: string | undefined;

    if (orgCode) {
      const orgLookup = await lookupWorkspaceByOrgCode(orgCode);
      if (orgLookup.found) {
        workspaceId = orgLookup.workspaceId!;
        workspaceName = orgLookup.workspaceName;
      }
    }

    if (!workspaceId) {
      workspaceId = PLATFORM_WORKSPACE_ID || null;
    }

    if (!workspaceId) {
      return res.status(400).json({ error: "No workspace found", hint: "Use staffing-ORGCODE@coaileague.com" });
    }

    const hasAttachments = (testEmail.attachments?.length || 0) > 0;
    const attachmentNames = testEmail.attachments?.map((a: any) => a.filename || a.name || 'unnamed') || [];
    const hasContractAttachment = attachmentNames.some((name: string) => 
      /contract|agreement|sow|terms|proposal/i.test(name)
    );

    const stageAResult = await inboundOpportunityAgent.processInboundEmail(workspaceId, {
      messageId: testEmail.message_id || `test-${Date.now()}`,
      fromEmail: senderEmail || 'noreply@coaileague.com',
      fromName: senderName || 'Test User',
      toEmail: testEmail.to?.[0],
      subject: testEmail.subject || 'Test Work Request',
      bodyText: testEmail.text || '',
      bodyHtml: testEmail.html,
      hasAttachments,
      attachmentCount: testEmail.attachments?.length || 0,
      attachmentNames,
      hasContractAttachment,
    });

    const pipelineTrace: any[] = [{ stage: 'A', name: 'Email Ingestion', result: stageAResult }];

    let stageBResult = null;
    if (stageAResult.success && stageAResult.data?.isShiftRequest && stageAResult.data?.extractedShifts?.length > 0) {
      try {
        stageBResult = await inboundOpportunityAgent.triggerAutoStaffing(workspaceId);
        pipelineTrace.push({ stage: 'B', name: 'Auto-Staffing', result: stageBResult });
      } catch (stageBErr: unknown) {
        pipelineTrace.push({ stage: 'B', name: 'Auto-Staffing', error: (stageBErr instanceof Error ? stageBErr.message : String(stageBErr)) });
      }
    }

    res.status(200).json({
      testMode: true,
      workspaceId,
      workspaceName,
      orgCode,
      pipelineTrace,
      contractDetected: hasContractAttachment,
      attachments: attachmentNames,
      stageA: stageAResult,
      stageB: stageBResult,
      nextSteps: stageBResult 
        ? 'Stage B complete. Employees have been sent shift offers. Use POST /api/onboarding/accept-offer/:workspaceId/:offerId to simulate acceptance (Stage C).'
        : stageAResult.success 
          ? 'Stage A complete. Trigger Stage B manually via POST /api/onboarding/staff-shifts/:workspaceId'
          : 'Stage A failed. Check logs.',
    });
  } catch (error: unknown) {
    log.error("[Resend Inbound TEST] Error:", error);
    res.status(500).json({ error: sanitizeError(error) });
  }
});

/**
 * Health check for inbound email configuration
 */
router.get("/api/webhooks/resend/inbound/status", async (req, res) => {
  const replitDomain = process.env.APP_BASE_URL;
  const webhookUrl = replitDomain 
    ? `https://${replitDomain}/api/webhooks/resend/inbound`
    : 'https://your-app-url/api/webhooks/resend/inbound';
  
  res.json({
    configured: true,
    staffingEmail: STAFFING_EMAIL_CONFIG.address,
    aliases: STAFFING_EMAIL_CONFIG.aliases,
    domain: STAFFING_EMAIL_CONFIG.domain,
    supportedFormats: [
      'function@{slug}.coaileague.com (subdomain format — only supported format)',
    ],
    webhookUrl,
    testEndpoint: replitDomain ? `https://${replitDomain}/api/webhooks/resend/inbound/test` : null,
    platformWorkspaceId: PLATFORM_WORKSPACE_ID || 'Not configured',
    mxRecord: '10 inbound.resend.com',
    dnsSetupRequired: true,
    instructions: [
      '1. In your DNS provider, add MX record for coaileague.com:',
      '   Type: MX, Name: @, Value: inbound.resend.com, Priority: 10',
      '2. In Resend Dashboard (resend.com/domains):',
      '   - Add domain: coaileague.com',
      '   - Verify the domain',
      '   - Enable "Inbound" in domain settings',
      '3. In Resend Dashboard (resend.com/webhooks):',
      `   - Create webhook URL: ${webhookUrl}`,
      '   - Select event: email.received',
      '4. Test by sending email to: staffing-STATEWIDE@coaileague.com',
    ],
  });
});

/**
 * Health check for the Resend outbound webhook receiver.
 * Confirms the route is reachable and the signing secret is configured.
 * Used to verify setup before pointing the Resend dashboard webhook here.
 */
router.get("/api/webhooks/resend/health", (_req, res) => {
  const secretConfigured = Boolean(RESEND_WEBHOOK_SECRET);
  res.json({
    ok: true,
    route: "POST /api/webhooks/resend",
    signingSecretConfigured: secretConfigured,
    message: secretConfigured
      ? "Resend webhook is ready. Signing secret is configured — all incoming events will be signature-verified."
      : "WARNING: RESEND_WEBHOOK_SECRET is not set. All incoming webhook payloads will be rejected until the secret is configured.",
    instructions: secretConfigured
      ? [
          "1. Point your Resend webhook to POST /api/webhooks/resend",
          "2. Events supported: email.sent, email.delivered, email.bounced, email.complained, email.clicked, email.opened, email.delivery_delayed",
        ]
      : [
          "1. Generate a signing secret in the Resend dashboard (Webhooks → Edit → Signing Secret)",
          "2. Set RESEND_WEBHOOK_SECRET=whsec_<your-secret> in your environment",
          "3. Restart the server and call this endpoint again to confirm",
        ],
  });
});

export default router;
