// Compliance Domain - Certifications, labor law, disputes, audits, PTO, terminations
// Re-exports from main schema for domain organization
// Import from this module for domain-specific schema access

// Tables
// Enums
// Insert Schemas
export {
  ptoRequests,
  policyAcknowledgments,
  auditLogs,
  supportAuditLogs,
  systemAuditLogs,
  dmAuditRequests,
  abuseViolations,
  trainingCertifications,
  disputes,
  auditProofPacks,
  passwordResetAuditLog,
  helpaiAuditLog,
  laborLawRules,
  complianceReports,
  complianceStates,
  complianceDocumentTypes,
  complianceRequirements,
  complianceDocuments,
  complianceApprovals,
  complianceAuditTrail,
  complianceExpirations,
  complianceAlerts,
  complianceScores,
  complianceChecklists,
  ptoStatusEnum,
  ptoTypeEnum,
  terminationTypeEnum,
  terminationStatusEnum,
  auditActionTypeEnum,
  certificationStatusEnum,
  policyStatusEnum,
  auditActionEnum,
  policyEffectEnum,
  complianceReportTypeEnum,
  complianceReportStatusEnum,
  complianceStateStatusEnum,
  complianceDocStatusEnum,
  complianceApprovalStatusEnum,
  complianceDocImageTypeEnum,
  insertPtoRequestSchema,
  insertCompanyPolicySchema,
  insertPolicyAcknowledgmentSchema,
  insertAuditLogSchema,
  insertSupportAuditLogSchema,
  insertDmAuditRequestSchema,
  insertAbuseViolationSchema,
  insertTrainingCertificationSchema,
  insertDisputeSchema,
  insertAuditProofPackSchema,
  insertPasswordResetAuditLogSchema,
  insertHelpaiAuditLogSchema,
  insertLaborLawRuleSchema,
  insertQuickFixRolePolicySchema,
  insertAccessPolicySchema,
  insertWorkspaceGovernancePolicySchema,
  insertComplianceReportSchema,
  insertComplianceStateSchema,
  insertComplianceDocumentTypeSchema,
  insertComplianceRequirementSchema,
  insertComplianceDocumentSchema,
  insertComplianceApprovalSchema,
  insertComplianceAuditTrailSchema,
  insertComplianceExpirationSchema,
  insertComplianceAlertSchema,
  insertComplianceScoreSchema,
  insertComplianceChecklistSchema,
  complianceStateRequirements,
  insertComplianceStateRequirementSchema,
} from '../schema';

export type {
  InsertComplianceStateRequirement,
  ComplianceStateRequirement,
  InsertPtoRequest,
  PtoRequest,
  InsertCompanyPolicy,
  CompanyPolicy,
  InsertPolicyAcknowledgment,
  PolicyAcknowledgment,
  InsertAuditLog,
  AuditLog,
  InsertSupportAuditLog,
  SupportAuditLog,
  SystemAuditLog,
  InsertDmAuditRequest,
  DmAuditRequest,
  InsertAbuseViolation,
  AbuseViolation,
  InsertTrainingCertification,
  TrainingCertification,
  InsertDispute,
  CreateDispute,
  Dispute,
  InsertAuditProofPack,
  AuditProofPack,
  InsertPasswordResetAuditLog,
  PasswordResetAuditLog,
  InsertHelpaiAuditLog,
  HelpaiAuditLog,
  InsertLaborLawRule,
  LaborLawRule,
  InsertQuickFixRolePolicy,
  QuickFixRolePolicy,
  InsertAccessPolicy,
  AccessPolicy,
  InsertWorkspaceGovernancePolicy,
  WorkspaceGovernancePolicy,
  InsertComplianceReport,
  ComplianceReport,
  InsertComplianceState,
  ComplianceState,
  InsertComplianceDocumentType,
  ComplianceDocumentType,
  InsertComplianceRequirement,
  ComplianceRequirement,
  InsertComplianceDocument,
  ComplianceDocument,
  InsertComplianceApproval,
  ComplianceApproval,
  InsertComplianceAuditTrail,
  ComplianceAuditTrail,
  InsertComplianceExpiration,
  ComplianceExpiration,
  InsertComplianceAlert,
  ComplianceAlert,
  InsertComplianceScore,
  ComplianceScore,
  InsertComplianceChecklist,
  ComplianceChecklist,
} from '../schema';

// Domain-specific tables not yet in main schema.ts
export {
  regulatoryViolations,
  insertRegulatoryViolationSchema,
  auditorVerificationRequests,
  insertAuditorVerificationRequestSchema,
} from './domains/compliance';
export type {
  RegulatoryViolation,
  InsertRegulatoryViolation,
  AuditorVerificationRequest,
  InsertAuditorVerificationRequest,
} from './domains/compliance';
