// Documents Domain - Document management, forms, templates, files, signatures, reports
// Re-exports from main schema for domain organization
// Import from this module for domain-specific schema access

// Tables
// Enums
// Insert Schemas
export {
  migrationDocuments,
  documentSignatures,
  documentAccessLogs,
  reportTemplates,
  reportSubmissions,
  reportWorkflowConfigs,
  reportApprovalSteps,
  lockedReportRecords,
  reportAttachments,
  serviceIncidentReports,
  emailTemplates,
  pulseSurveyTemplates,
  autoReports,
  mascotMotionProfiles,
  userDeviceProfiles,
  orgDocuments,
  orgDocumentAccess,
  orgDocumentSignatures,
  darReports,
  industryServiceTemplates,
  migrationDocumentTypeEnum,
  documentTypeEnum,
  documentSignatureStatusEnum,
  documentTypeSignatureEnum,
  insertMigrationDocumentSchema,
  insertDocumentSignatureSchema,
  insertDocumentAccessLogSchema,
  insertReportTemplateSchema,
  insertReportSubmissionSchema,
  insertReportWorkflowConfigSchema,
  insertReportApprovalStepSchema,
  insertLockedReportRecordSchema,
  insertReportAttachmentSchema,
  insertServiceIncidentReportSchema,
  insertEmailTemplateSchema,
  insertPulseSurveyTemplateSchema,
  insertAutoReportSchema,
  insertMascotMotionProfileSchema,
  insertUserDeviceProfileSchema,
  insertOrgDocumentSchema,
  insertOrgDocumentAccessSchema,
  insertOrgDocumentSignatureSchema,
  insertDarReportSchema,
  insertIndustryServiceTemplateSchema,
} from '../schema';

export type {
  InsertMigrationDocument,
  MigrationDocument,
  InsertDocumentSignature,
  DocumentSignature,
  InsertDocumentAccessLog,
  DocumentAccessLog,
  InsertReportTemplate,
  ReportTemplate,
  InsertReportSubmission,
  ReportSubmission,
  InsertReportWorkflowConfig,
  ReportWorkflowConfig,
  InsertReportApprovalStep,
  ReportApprovalStep,
  InsertLockedReportRecord,
  LockedReportRecord,
  InsertReportAttachment,
  ReportAttachment,
  InsertServiceIncidentReport,
  ServiceIncidentReport,
  InsertEmailTemplate,
  EmailTemplate,
  InsertPulseSurveyTemplate,
  PulseSurveyTemplate,
  InsertAutoReport,
  AutoReport,
  InsertMascotMotionProfile,
  MascotMotionProfile,
  InsertUserDeviceProfile,
  UserDeviceProfile,
  InsertOrgDocument,
  OrgDocument,
  InsertOrgDocumentAccess,
  OrgDocumentAccess,
  InsertOrgDocumentSignature,
  OrgDocumentSignature,
  InsertDarReport,
  DarReport,
  InsertIndustryServiceTemplate,
  IndustryServiceTemplate,
} from '../schema';
