// Onboarding Domain - Onboarding workflows, training, courses, checklists, HRIS
// Re-exports from main schema for domain organization
// Import from this module for domain-specific schema access

// Tables
// Enums
// Insert Schemas
export {
  userOnboarding,
  trainingScenarios,
  trainingRuns,
  trainingAttempts,
  onboardingInvites,
  onboardingApplications,
  onboardingWorkflowTemplates,
  onboardingChecklists,
  onboardingTemplates,
  onboardingTasks,
  onboardingSessions,
  trainingCourses,
  organizationOnboarding,
  organizationRoomOnboarding,
  orgOnboardingTasks,

  interactiveOnboardingState,
  workspaceOnboardingStates,
  trainingDifficultyEnum,
  onboardingStatusEnum,
  onboardingStepEnum,
  onboardingTaskStatusEnum,
  insertUserOnboardingSchema,
  insertTrainingScenarioSchema,
  insertTrainingRunSchema,
  insertTrainingAttemptSchema,
  insertOnboardingInviteSchema,
  insertOnboardingApplicationSchema,
  insertOnboardingWorkflowTemplateSchema,
  insertOnboardingChecklistSchema,
  insertOnboardingTemplateSchema,
  insertOnboardingTaskSchema,
  insertOnboardingSessionSchema,
  insertTrainingCourseSchema,
  insertOrganizationOnboardingSchema,
  insertOrganizationRoomOnboardingSchema,
  insertOrgOnboardingTaskSchema,
  insertUserOnboardingProgressSchema,
  insertInteractiveOnboardingStateSchema,
} from '../schema';

export type {
  InsertUserOnboarding,
  UserOnboarding,
  InsertTrainingScenario,
  TrainingScenario,
  InsertTrainingRun,
  TrainingRun,
  InsertTrainingAttempt,
  TrainingAttempt,
  InsertOnboardingInvite,
  OnboardingInvite,
  InsertOnboardingApplication,
  OnboardingApplication,
  InsertOnboardingWorkflowTemplate,
  OnboardingWorkflowTemplate,
  InsertOnboardingChecklist,
  OnboardingChecklist,
  OnboardingTemplate,
  InsertOnboardingTask,
  OnboardingTask,
  InsertOnboardingSession,
  OnboardingSession,
  InsertOnboardingTaskCompletion,
  InsertTrainingCourse,
  TrainingCourse,
  InsertOrganizationOnboarding,
  OrganizationOnboarding,
  InsertOrganizationRoomOnboarding,
  OrganizationRoomOnboarding,
  InsertOrgOnboardingTask,
  OrgOnboardingTask,
  InsertUserOnboardingProgress,
  UserOnboardingProgress,
  InsertInteractiveOnboardingState,
  InteractiveOnboardingState,
} from '../schema';
