/**
 * COAILEAGUE 15-DOMAIN ARCHITECTURAL CONTRACT
 * ============================================
 * THE LAW: Every table, route, service file, and API mount belongs to
 * exactly one of these 15 canonical domains. No exceptions.
 * No new tables without Bryan's explicit approval. Zero DROP TABLE ever.
 *
 * Established: March 2026
 * This file is the permanent architectural reference — do not delete.
 */

export const DOMAIN_CONTRACT = {
  // ─────────────────────────────────────────────────
  // Domain 1: Auth & Identity
  // ─────────────────────────────────────────────────
  auth: {
    label: 'Auth & Identity',
    schemaIndex: 'shared/schema/domains/auth/index.ts',
    tables: [
      'apiKeys',
      'platformRoles',
      'roleTemplates',
      'integrationApiKeys',
      'idempotencyKeys',
      'oauthStates',
      'externalIdentifiers',
      'idSequences',
      'idRegistry',
      'userDeviceProfiles',
      'sessionCheckpoints',
      'sessionRecoveryRequests',
      'userAutomationConsents',
      'accessPolicies',
      'accessControlEvents',
      'workspaceApiKeys',
      'apiKeyUsageLogs',
      'expressSessions',
      'managedApiKeys',
      'sessions',
      'users',
      'authTokens',
      'authSessions',
      'passwordResetAuditLog',
    ],
    mounts: [
      '/api/auth',
      '/api/auth/login',
      '/api/auth/register',
      '/api/auth/forgot-password',
      '/api/auth/magic-link',
      '/api/auth/reset-password',
      '/api/session-checkpoints',
    ],
    routes: [
      'server/routes/authRoutes.ts',
      'server/routes/devRoutes.ts',
      'server/routes/endUserControlRoutes.ts',
      'server/routes/sessionCheckpointRoutes.ts',
      'server/routes/wellKnown.ts',
    ],
    services: [
      'server/services/abuseDetection.ts',
      'server/services/auth/mfa.ts',
      'server/services/authService.ts',
      'server/services/oauth/googleCalendar.ts',
      'server/services/oauth/gusto.ts',
      'server/services/recaptchaService.ts',
      'server/services/session/elevatedSessionService.ts',
      'server/services/session/sessionCheckpointService.ts',
      'server/services/session/sessionWorkspaceService.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 2: Orgs & Workspaces
  // ─────────────────────────────────────────────────
  orgs: {
    label: 'Orgs & Workspaces',
    schemaIndex: 'shared/schema/domains/orgs/index.ts',
    tables: [
      'userOnboarding',
      'workspaceMembers',
      'onboardingInvites',
      'onboardingApplications',
      'onboardingWorkflowTemplates',
      'featureFlags',
      'integrationMarketplace',
      'integrationConnections',
      'webhookSubscriptions',
      'promotionalBanners',
      'onboardingTemplates',
      'onboardingTasks',
      'organizationOnboarding',
      'organizationRoomOnboarding',
      'workspaceAddons',
      'featureUpdates',
      'featureUpdateReceipts',
      'orgInvitations',
      'interactiveOnboardingState',
      'orgDocuments',
      'orgDocumentAccess',
      'industryServiceTemplates',
      'workspaceServiceCatalog',
      'orgFeatures',
      'workspaces',
      'workspaceThemes',
      'workspaceInvites',
      'onboardingChecklists',
      'orgOnboardingTasks',
      'orgRewards',
    ],
    mounts: [
      '/api/workspace',
      '/api/enterprise',
      '/api/enterprise-features',
      '/api/onboarding',
      '/api/employee-onboarding',
      '/api/integrations',
      '/api/feature-flags',
      '/api/whats-new',
      '/api/import',
    ],
    routes: [
      'server/routes/assisted-onboarding.ts',
      'server/routes/deviceLoaderRoutes.ts',
      'server/routes/employeeOnboardingRoutes.ts',
      'server/routes/enterpriseFeatures.ts',
      'server/routes/enterpriseOnboardingRoutes.ts',
      'server/routes/experienceRoutes.ts',
      'server/routes/featureFlagsRoutes.ts',
      'server/routes/hireosRoutes.ts',
      'server/routes/importRoutes.ts',
      'server/routes/integrationManagementRoutes.ts',
      'server/routes/integrationRoutes.ts',
      'server/routes/integrationsInlineRoutes.ts',
      'server/routes/onboarding-assistant-routes.ts',
      'server/routes/onboardingInlineRoutes.ts',
      'server/routes/onboardingRoutes.ts',
      'server/routes/promotionalBannerRoutes.ts',
      'server/routes/whatsNewRoutes.ts',
      'server/routes/workspace.ts',
      'server/routes/workspaceInlineRoutes.ts',
    ],
    services: [
      'server/services/featureFlagsService.ts',
      'server/services/hris/hrisIntegrationService.ts',
      'server/services/industryTemplates.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 3: Workforce
  // ─────────────────────────────────────────────────
  workforce: {
    label: 'Workforce',
    schemaIndex: 'shared/schema/domains/workforce/index.ts',
    tables: [
      'employeeSkills',
      'contractorPool',
      'contractorSkills',
      'contractorAssignments',
      'performanceReviews',
      'managerAssignments',
      'employeeDocuments',
      'turnoverRiskScores',
      'skillGapAnalyses',
      'pulseSurveyTemplates',
      'pulseSurveyResponses',
      'anonymousSuggestions',
      'employeeHealthScores',
      'offboardingSessions',
      'exitInterviewResponses',
      'employeeAvailability',
      'satisfactionSurveys',
      'achievements',
      'employeePoints',
      'leaderboardCache',
      'coaileagueEmployeeProfiles',
      'employeeEventLog',
      'personalityTagsCatalog',
      'userFeedback',
      'feedbackComments',
      'feedbackVotes',
      'flexContractors',
      'flexAvailability',
      'flexGigs',
      'flexGigApplications',
      'flexGigRatings',
      'knownContractors',
      'employees',
      'trainingScenarios',
      'trainingRuns',
      'trainingCourses',
      'trainingEnrollments',
      'engagementScoreHistory',
    ],
    mounts: [
      '/api/employees',
      '/api/hr',
      '/api/flex-staffing',
      '/api/gamification',
      '/api/gamification/enhanced',
      '/api/engagement',
      '/api/officer-scores',
      '/api/training',
      '/api/reviews',
      '/api/benefits',
      '/api/availability',
    ],
    routes: [
      'server/routes/availabilityRoutes.ts',
      'server/routes/benefitRoutes.ts',
      'server/routes/deactivateRoutes.ts',
      'server/routes/employeeRoutes.ts',
      'server/routes/engagementRoutes.ts',
      'server/routes/feedbackRoutes.ts',
      'server/routes/flexStaffingRoutes.ts',
      'server/routes/gamificationRoutes.ts',
      'server/routes/hrInlineRoutes.ts',
      'server/routes/hrisRoutes.ts',
      'server/routes/leaderRoutes.ts',
      'server/routes/officerScoreRoutes.ts',
      'server/routes/owner-employee.ts',
      'server/routes/reviewRoutes.ts',
      'server/routes/terminationRoutes.ts',
      'server/routes/trainingRoutes.ts',
    ],
    services: [
      'server/services/assistedOnboardingService.ts',
      'server/services/compositeScoresService.ts',
      'server/services/deactivateService.ts',
      'server/services/employeeBehaviorScoring.ts',
      'server/services/employeeDocumentOnboardingService.ts',
      'server/services/employeePatternService.ts',
      'server/services/employeeRoleSyncService.ts',
      'server/services/engagementCalculations.ts',
      'server/services/enterpriseOnboardingOrchestrator.ts',
      'server/services/gamification/aiBrainNotifier.ts',
      'server/services/gamification/eventTracker.ts',
      'server/services/gamification/gamificationEvents.ts',
      'server/services/gamification/gamificationService.ts',
      'server/services/gamification/whatsNewIntegration.ts',
      'server/services/officerScoreService.ts',
      'server/services/onboardingPipelineService.ts',
      'server/services/ownerManagerEmployeeService.ts',
      'server/services/performanceMetrics.ts',
      'server/services/performanceReviewReminders.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 4: Scheduling
  // ─────────────────────────────────────────────────
  scheduling: {
    label: 'Scheduling',
    schemaIndex: 'shared/schema/domains/scheduling/index.ts',
    tables: [
      'schedules',
      'shiftRequests',
      'shiftOffers',
      'shifts',
      'customSchedulerIntervals',
      'recurringShiftPatterns',
      'shiftSwapRequests',
      'scheduleTemplates',
      'shiftAcknowledgments',
      'serviceCoverageRequests',
      'publishedSchedules',
      'scheduleSnapshots',
      'scheduleProposals',
      'shiftTemplates',
      'smartScheduleUsage',
      'shiftOrders',
      'shiftOrderAcknowledgments',
      'internalBids',
      'bidApplications',
      'capacityAlerts',
      'shiftActions',
      'shiftAcceptanceRecords',
      'schedulerNotificationEvents',
      'calendarSubscriptions',
      'calendarImports',
      'calendarSyncEvents',
      'approvalGates',
      'scheduleLifecycles',
      'shiftChatrooms',
      'shiftChatroomMembers',
      'shiftChatroomMessages',
      'shiftCoverageRequests',
      'stagedShifts',
      'automatedShiftOffers',
      'staffingClaimTokens',
      'shiftCoverageClaims',
    ],
    mounts: [
      '/api/shifts',
      '/api/schedules',
      '/api/scheduler',
      '/api/orchestrated-schedule',
      '/api/ai/scheduling',
      '/api/calendar',
      '/api/coverage',
      '/api/post-orders',
      '/api/trinity-staffing',
      '/api/public/trinity-staffing',
    ],
    routes: [
      'server/routes/advancedSchedulingRoutes.ts',
      'server/routes/aiSchedulingRoutes.ts',
      'server/routes/autonomousSchedulingRoutes.ts',
      'server/routes/calendarRoutes.ts',
      'server/routes/coverageRoutes.ts',
      'server/routes/orchestratedScheduleRoutes.ts',
      'server/routes/postOrderRoutes.ts',
      'server/routes/scheduleosRoutes.ts',
      'server/routes/schedulerRoutes.ts',
      'server/routes/shiftChatroomRoutes.ts',
      'server/routes/shiftRoutes.ts',
      'server/routes/trinitySchedulingRoutes.ts',
      'server/routes/trinityStaffingRoutes.ts',
    ],
    services: [
      'server/services/advancedSchedulingService.ts',
      'server/services/autonomousScheduler.ts',
      'server/services/fieldOperations/shiftHandoffService.ts',
      'server/services/scheduleLiveNotifier.ts',
      'server/services/scheduleMigration.ts',
      'server/services/scheduleRollbackService.ts',
      'server/services/scheduleSmartAI.ts',
      'server/services/scheduling/autonomousSchedulingDaemon.ts',
      'server/services/scheduling/historicalScheduleImporter.ts',
      'server/services/scheduling/index.ts',
      'server/services/scheduling/officerDeactivationHandler.ts',
      'server/services/scheduling/recurringScheduleTemplates.ts',
      'server/services/scheduling/schedulingEnhancementsService.ts',
      'server/services/shiftApprovalService.ts',
      'server/services/shiftChatroomWorkflowService.ts',
      'server/services/shiftRemindersService.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 5: Time & Attendance
  // ─────────────────────────────────────────────────
  time: {
    label: 'Time & Attendance',
    schemaIndex: 'shared/schema/domains/time/index.ts',
    tables: [
      'ptoRequests',
      'timeEntries',
      'timeEntryAuditEvents',
      'gpsLocations',
      'scheduledBreaks',
      'evvVisitRecords',
      'manualClockinOverrides',
      'timeEntryBreaks',
      'timeEntryDiscrepancies',
      'timeOffRequests',
      'timesheetEditRequests',
    ],
    mounts: [
      '/api/time-entries',
      '/api/time-off',
      '/api/gps',
      '/api/breaks',
    ],
    routes: [
      'server/routes/breakRoutes.ts',
      'server/routes/gpsRoutes.ts',
      'server/routes/timeEntryRoutes.ts',
      'server/routes/timeOffRoutes.ts',
      'server/routes/timesheetReportRoutes.ts',
    ],
    services: [
      'server/services/breaksService.ts',
      'server/services/gpsGeofenceService.ts',
      'server/services/timeEntryDisputeService.ts',
      'server/services/timeEntryService.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 6: Payroll
  // ─────────────────────────────────────────────────
  payroll: {
    label: 'Payroll',
    schemaIndex: 'shared/schema/domains/payroll/index.ts',
    tables: [
      'employeeBenefits',
      'payrollProposals',
      'offCyclePayrollRuns',
      'payrollRuns',
      'payrollEntries',
      'employeePayrollInfo',
      'employeeRateHistory',
      'laborLawRules',
      'workerTaxClassificationHistory',
      'multiStateComplianceWindows',
      'payStubs',
      'deductionConfigs',
      'payrollProviderConnections',
    ],
    mounts: [
      '/api/payroll',
      '/api/pay-stubs',
      '/api/expenses',
    ],
    routes: [
      'server/routes/expenseRoutes.ts',
      'server/routes/payStubRoutes.ts',
      'server/routes/payrollRoutes.ts',
    ],
    services: [
      'server/services/finance/payrollExportService.ts',
      'server/services/payroll/payrollLedger.ts',
      'server/services/payrollDeductionService.ts',
      'server/services/paystubService.ts',
      'server/services/ptoAccrual.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 7: Billing & Finance
  // ─────────────────────────────────────────────────
  billing: {
    label: 'Billing & Finance',
    schemaIndex: 'shared/schema/domains/billing/index.ts',
    tables: [
      'invoices',
      'invoiceLineItems',
      'paymentRecords',
      'orgLedger',
      'exchangeRates',
      'subscriptions',
      'platformRevenue',
      'costVariancePredictions',
      'expenseCategories',
      'expenses',
      'expenseReceipts',
      'budgets',
      'budgetLineItems',
      'budgetVariances',
      'disputes',
      'paymentReminders',
      'billingAddons',
      'aiTokenWallets',
      'subscriptionInvoices',
      'subscriptionLineItems',
      'subscriptionPayments',
      'billingAuditLog',
      'workspaceRateHistory',
      'quickbooksMigrationRuns',
      'quickbooksOnboardingFlows',
      'quickbooksApiUsage',
      'billingPolicyProfiles',
      'usageAggregates',
      'commitmentLedger',
      'trinityCreditPackages',
      'trinityCredits',
      'trinityCreditCosts',
      'quickbooksSyncReceipts',
      'billingServices',
      'processedStripeEvents',
      'evvBillingCodes',
      'locationPnlSnapshots',
      'reconciliationFindings',
      'reconciliationRuns',
      'financialSnapshots',
      'clientProfitability',
      'financialAlerts',
      'subscriptionTiers',
      'addonFeatures',
      'orgSubscriptions',
      'upsellEvents',
      'featureAddons',
      'accountFreezes',
      'freezeAppeals',
      'orgFinanceSettings',
      'creditBalances',
      'financialProcessingFees',
      'platformInvoices',
      'usageCaps',
      'platformCreditPool',
      'pointsTransactions',
    ],
    mounts: [
      '/api/billing',
      '/api/billing/upsell',
      '/api/invoices',
      '/api/finance',
      '/api/credits',
      '/api/budgets',
      '/api/disputes',
      '/api/quickbooks',
      '/api/stripe',
    ],
    routes: [
      'server/routes/billingSettingsRoutes.ts',
      'server/routes/budgetRoutes.ts',
      'server/routes/creditRoutes.ts',
      'server/routes/disputeRoutes.ts',
      'server/routes/empireRoutes.ts',
      'server/routes/financeInlineRoutes.ts',
      'server/routes/financeRoutes.ts',
      'server/routes/financeSettingsRoutes.ts',
      'server/routes/financialIntelligence.ts',
      'server/routes/invoiceRoutes.ts',
      'server/routes/qbReportsRoutes.ts',
      'server/routes/quickbooks-sync.ts',
      'server/routes/quickbooksPhase3Routes.ts',
      'server/routes/stripeInlineRoutes.ts',
      'server/routes/timesheetInvoiceRoutes.ts',
      'server/routes/trinityRevenueRoutes.ts',
      'server/routes/upsellRoutes.ts',
    ],
    services: [
      'server/services/billing/accountState.ts',
      'server/services/billing/aiCreditGateway.ts',
      'server/services/billing/aiRateLimiter.ts',
      'server/services/billing/billingConstants.ts',
      'server/services/billing/billingReconciliation.ts',
      'server/services/billing/costAggregation.ts',
      'server/services/billing/creditBalanceService.ts',
      'server/services/billing/creditLedger.ts',
      'server/services/billing/creditManager.ts',
      'server/services/billing/creditPurchase.ts',
      'server/services/billing/creditResetCron.ts',
      'server/services/billing/creditWrapper.ts',
      'server/services/billing/creditsLedgerService.ts',
      'server/services/billing/exceptionQueueProcessor.ts',
      'server/services/billing/featureGateService.ts',
      'server/services/billing/featureToggle.ts',
      'server/services/billing/financialProcessingFeeService.ts',
      'server/services/billing/index.ts',
      'server/services/billing/invoice.ts',
      'server/services/billing/meteredGeminiClient.ts',
      'server/services/billing/meteredGptClient.ts',
      'server/services/billing/middlewareTransactionFees.ts',
      'server/services/billing/partnerApiUsage.ts',
      'server/services/billing/payrollTaxService.ts',
      'server/services/billing/platformBillService.ts',
      'server/services/billing/platformServicesMeter.ts',
      'server/services/billing/providerPreferenceService.ts',
      'server/services/billing/recycledCreditsPipeline.ts',
      'server/services/billing/stateTaxService.ts',
      'server/services/billing/stripeConnectPayoutService.ts',
      'server/services/billing/stripeEventBridge.ts',
      'server/services/billing/stripeWebhooks.ts',
      'server/services/billing/subscriptionManager.ts',
      'server/services/billing/trialConversionOrchestrator.ts',
      'server/services/billing/trialManager.ts',
      'server/services/billing/universalAIBillingInterceptor.ts',
      'server/services/billing/upsellService.ts',
      'server/services/billing/usageCapService.ts',
      'server/services/billing/usageMetering.ts',
      'server/services/billing/usageTracker.ts',
      'server/services/billing/weeklyBillingRunService.ts',
      'server/services/billos.ts',
      'server/services/contracts/contractPipelineService.ts',
      'server/services/currency/exchangeRateService.ts',
      'server/services/integrations/quickbooksDiscovery.ts',
      'server/services/integrations/quickbooksIntegration.ts',
      'server/services/integrations/quickbooksLazySync.ts',
      'server/services/integrations/quickbooksRateLimiter.ts',
      'server/services/integrations/quickbooksSyncPollingService.ts',
      'server/services/integrations/quickbooksTokenRefresh.ts',
      'server/services/integrations/quickbooksWebhookService.ts',
      'server/services/invoiceAdjustmentService.ts',
      'server/services/oauth/quickbooks.ts',
      'server/services/orgLedgerService.ts',
      'server/services/partners/billingOrchestrationService.ts',
      'server/services/partners/quickbooks.ts',
      'server/services/partners/quickbooksPhase3Service.ts',
      'server/services/partners/quickbooksSyncService.ts',
      'server/services/quickbooksClientBillingSync.ts',
      'server/services/quickbooksReceiptService.ts',
      'server/services/rateManagement.ts',
      'server/services/timesheetInvoiceService.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 8: Trinity AI Engine
  // ─────────────────────────────────────────────────
  trinity: {
    label: 'Trinity AI Engine',
    schemaIndex: 'shared/schema/domains/trinity/index.ts',
    tables: [
      'workspaceAiUsage',
      'customRules',
      'ruleExecutionLogs',
      'aiInsights',
      'aiUsageEvents',
      'aiUsageDailyRollups',
      'exceptionTriageQueue',
      'aiBrainJobs',
      'aiCheckpoints',
      'scoringWeightProfiles',
      'aiSuggestions',
      'stagedCodeChanges',
      'codeChangeBatches',
      'orchestrationRuns',
      'orchestrationRunSteps',
      'workflowArtifacts',
      'quickFixActions',
      'quickFixRolePolicies',
      'quickFixRequests',
      'quickFixExecutions',
      'aiSubagentDefinitions',
      'trinityAccessControl',
      'subagentTelemetry',
      'trinityUnlockCodes',
      'automationActionLedger',
      'trinityConversationSessions',
      'trinityConversationTurns',
      'aiApprovals',
      'entityAttributes',
      'a2aAgents',
      'a2aMessages',
      'a2aTeams',
      'a2aTrustRules',
      'aiLearningEvents',
      'llmJudgeEvaluations',
      'llmJudgeRegressions',
      'automationGovernance',
      'trinityThoughtSignatures',
      'trinityActionLogs',
      'trinityUserConfidenceStats',
      'trinityOrgStats',
      'orchestrationOverlays',
      'aiGapFindings',
      'trinitySelfAwareness',
      'aiBrainLiveEvents',
      'automationExecutions',
      'trinityAutomationSettings',
      'trinityAutomationRequests',
      'trinityAutomationReceipts',
      'trinityBuddySettings',
      'trinityMetacognitionLog',
      'trinityDecisionLog',
      'trinityRuntimeFlags',
      'trinityRuntimeFlagChanges',
      'trinityRequests',
      'trinityUsageAnalytics',
      'trinityRecommendations',
      'aiModels',
      'aiTaskTypes',
      'aiTaskQueue',
      'aiModelHealth',
      'pendingConfigurations',
      'executionPipelineLogs',
      'trinityAnomalyLog',
      'metaCognitionLogs',
      'durableJobQueue',
      'automationTriggersRaw',
      'trinityKnowledgeBase',
      'trinityCreditTransactions',
      'trinityMeetingRecordings',
    ],
    mounts: [
      '/api/ai-brain',
      '/api/trinity',
      '/api/trinity-decisions',
      '/api/ai/orchestra',
      '/api/automation',
      '/api/automation-events',
      '/api/execution-tracker',
      '/api/approvals',
      '/api/helpai',
      '/api/quick-fix',
      '/api/subagents',
      '/api/workboard',
      '/api/control-tower',
      '/api/workflows',
      '/api/bug-remediation',
    ],
    routes: [
      'server/routes/ai-brain-console.ts',
      'server/routes/aiBrainControlRoutes.ts',
      'server/routes/aiBrainInlineRoutes.ts',
      'server/routes/aiOrchestraRoutes.ts',
      'server/routes/aiOrchestratorRoutes.ts',
      'server/routes/aiRoutes.ts',
      'server/routes/approvalRoutes.ts',
      'server/routes/automation-events.ts',
      'server/routes/automation.ts',
      'server/routes/automationGovernanceRoutes.ts',
      'server/routes/automationInlineRoutes.ts',
      'server/routes/bugRemediation.ts',
      'server/routes/code-editor.ts',
      'server/routes/contentInlineRoutes.ts',
      'server/routes/controlTowerRoutes.ts',
      'server/routes/executionTrackerRoutes.ts',
      'server/routes/governanceInlineRoutes.ts',
      'server/routes/quickFixRoutes.ts',
      'server/routes/subagentRoutes.ts',
      'server/routes/trinity-alerts.ts',
      'server/routes/trinityChatRoutes.ts',
      'server/routes/trinityControlConsoleRoutes.ts',
      'server/routes/trinityCrisisRoutes.ts',
      'server/routes/trinityDecisionRoutes.ts',
      'server/routes/trinityInsightsRoutes.ts',
      'server/routes/trinityIntelligenceRoutes.ts',
      'server/routes/trinityMaintenanceRoutes.ts',
      'server/routes/trinityMiscRoutes.ts',
      'server/routes/trinityNotificationRoutes.ts',
      'server/routes/trinitySelfEditRoutes.ts',
      'server/routes/trinitySessionRoutes.ts',
      'server/routes/trinitySwarmRoutes.ts',
      'server/routes/trinityTrainingRoutes.ts',
      'server/routes/vqaRoutes.ts',
      'server/routes/workboardRoutes.ts',
      'server/routes/workflowConfigRoutes.ts',
      'server/routes/workflowRoutes.ts',
    ],
    services: [
      'server/services/ai-brain/actionRegistry.ts',
      'server/services/ai-brain/adaptiveSupervisionRouter.ts',
      'server/services/ai-brain/agent/alternativeStrategyService.ts',
      'server/services/ai-brain/agent/goalExecutionService.ts',
      'server/services/ai-brain/agent/goalMetricsService.ts',
      'server/services/ai-brain/agent/stateVerificationService.ts',
      'server/services/ai-brain/agentCache.ts',
      'server/services/ai-brain/agentToAgentProtocol.ts',
      'server/services/ai-brain/aiAnalyticsEngine.ts',
      'server/services/ai-brain/aiBrainAuthorizationService.ts',
      'server/services/ai-brain/aiBrainCodeEditor.ts',
      'server/services/ai-brain/aiBrainFileSystemTools.ts',
      'server/services/ai-brain/aiBrainMasterOrchestrator.ts',
      'server/services/ai-brain/aiBrainService.ts',
      'server/services/ai-brain/aiBrainTestRunner.ts',
      'server/services/ai-brain/aiBrainWorkflowExecutor.ts',
      'server/services/ai-brain/aiDynamicPricingService.ts',
      'server/services/ai-brain/aiExpenseCategorizationService.ts',
      'server/services/ai-brain/aiOrchestraService.ts',
      'server/services/ai-brain/aiProviderBalances.ts',
      'server/services/ai-brain/approvalRequestService.ts',
      'server/services/ai-brain/approvalResumeOrchestrator.ts',
      'server/services/ai-brain/automationGovernanceService.ts',
      'server/services/ai-brain/autonomousFixPipeline.ts',
      'server/services/ai-brain/autonomousWorkflowService.ts',
      'server/services/ai-brain/behavioralMonitoringService.ts',
      'server/services/ai-brain/blueDotProtocol.ts',
      'server/services/ai-brain/browserAutomationTool.ts',
      'server/services/ai-brain/bugReportOrchestrator.ts',
      'server/services/ai-brain/cacheUtils.ts',
      'server/services/ai-brain/chatServerSubagent.ts',
      'server/services/ai-brain/cleanupAgentSubagent.ts',
      'server/services/ai-brain/cognitiveBrainActions.ts',
      'server/services/ai-brain/cognitiveOnboardingService.ts',
      'server/services/ai-brain/cognitiveRepositories.ts',
      'server/services/ai-brain/commitmentManager.ts',
      'server/services/ai-brain/contextResolver.ts',
      'server/services/ai-brain/costMonitor.ts',
      'server/services/ai-brain/costOptimizedRouter.ts',
      'server/services/ai-brain/crawlerTypes.ts',
      'server/services/ai-brain/crisisManager.ts',
      'server/services/ai-brain/documentUnderstandingPipeline.ts',
      'server/services/ai-brain/domainLeadSupervisors.ts',
      'server/services/ai-brain/domainSupervisorActions.ts',
      'server/services/ai-brain/dualai/aiActionLogger.ts',
      'server/services/ai-brain/dualai/claudeService.ts',
      'server/services/ai-brain/dualai/claudeVerificationService.ts',
      'server/services/ai-brain/dualai/index.ts',
      'server/services/ai-brain/dualai/taskRouter.ts',
      'server/services/ai-brain/dualai/trinityConfidenceScorer.ts',
      'server/services/ai-brain/dualai/unifiedAIOrchestrator.ts',
      'server/services/ai-brain/elevatedSessionGuardian.ts',
      'server/services/ai-brain/fastModeService.ts',
      'server/services/ai-brain/gapIntelligenceService.ts',
      'server/services/ai-brain/geminiToolSchemaGenerator.ts',
      'server/services/ai-brain/growthStrategist.ts',
      'server/services/ai-brain/holisticGrowthEngine.ts',
      'server/services/ai-brain/idempotencyService.ts',
      'server/services/ai-brain/industryComplianceTemplates.ts',
      'server/services/ai-brain/integrationBrainActions.ts',
      'server/services/ai-brain/integrationManagementService.ts',
      'server/services/ai-brain/integrationPartnerService.ts',
      'server/services/ai-brain/internalEventEmitter.ts',
      'server/services/ai-brain/knowledgeOrchestrationService.ts',
      'server/services/ai-brain/llmJudgeEnhanced.ts',
      'server/services/ai-brain/llmJudgeEvaluator.ts',
      'server/services/ai-brain/metaCognitionService.ts',
      'server/services/ai-brain/modelRoutingEngine.ts',
      'server/services/ai-brain/notificationDiagnostics.ts',
      'server/services/ai-brain/orchestrationBridge.ts',
      'server/services/ai-brain/orchestrationStateMachine.ts',
      'server/services/ai-brain/orchestratorCapabilities.ts',
      'server/services/ai-brain/orgOnboardingAssistant.ts',
      'server/services/ai-brain/planningFrameworkService.ts',
      'server/services/ai-brain/platformAwarenessHelper.ts',
      'server/services/ai-brain/platformChangeMonitor.ts',
      'server/services/ai-brain/platformFeatureRegistry.ts',
      'server/services/ai-brain/platformHealthMonitor.ts',
      'server/services/ai-brain/platformIntentRouter.ts',
      'server/services/ai-brain/providers/geminiClient.ts',
      'server/services/ai-brain/providers/modelRouter.ts',
      'server/services/ai-brain/providers/openaiClient.ts',
      'server/services/ai-brain/providers/resilientAIGateway.ts',
      'server/services/ai-brain/realTimeBridge.ts',
      'server/services/ai-brain/reinforcementLearningLoop.ts',
      'server/services/ai-brain/scheduleLiveNotifierActions.ts',
      'server/services/ai-brain/schedulerCoordinator.ts',
      'server/services/ai-brain/seasonalSubagent.ts',
      'server/services/ai-brain/secureToolExecutor.ts',
      'server/services/ai-brain/selfReflectionEngine.ts',
      'server/services/ai-brain/serviceControl.ts',
      'server/services/ai-brain/serviceOrchestrationWatchdog.ts',
      'server/services/ai-brain/sessionSyncService.ts',
      'server/services/ai-brain/sharedKnowledgeGraph.ts',
      'server/services/ai-brain/skills/base-skill.ts',
      'server/services/ai-brain/skills/dataResearchSkill.ts',
      'server/services/ai-brain/skills/documentGeneratorSkill.ts',
      'server/services/ai-brain/skills/financialMathVerifierSkill.ts',
      'server/services/ai-brain/skills/intelligentScheduler.ts',
      'server/services/ai-brain/skills/invoiceReconciliation.ts',
      'server/services/ai-brain/skills/payrollValidation.ts',
      'server/services/ai-brain/skills/seasonalOrchestrator.ts',
      'server/services/ai-brain/skills/skill-loader.ts',
      'server/services/ai-brain/skills/skill-registry.ts',
      'server/services/ai-brain/skills/timeAnomalyDetection.ts',
      'server/services/ai-brain/skills/trinity-staffing-skill.ts',
      'server/services/ai-brain/skills/types.ts',
      'server/services/ai-brain/strategicOptimizationService.ts',
      'server/services/ai-brain/streaming/trinityWebSocketService.ts',
      'server/services/ai-brain/subagentBanker.ts',
      'server/services/ai-brain/subagentConfidenceMonitor.ts',
      'server/services/ai-brain/subagentPerformanceMeetingService.ts',
      'server/services/ai-brain/subagentSupervisor.ts',
      'server/services/ai-brain/subagents/coreSubagentOrchestration.ts',
      'server/services/ai-brain/subagents/dataMigrationAgent.ts',
      'server/services/ai-brain/subagents/domainOpsSubagents.ts',
      'server/services/ai-brain/subagents/gamificationActivationAgent.ts',
      'server/services/ai-brain/subagents/invoiceSubagent.ts',
      'server/services/ai-brain/subagents/notificationSubagent.ts',
      'server/services/ai-brain/subagents/onboardingOrchestrator.ts',
      'server/services/ai-brain/subagents/payrollSubagent.ts',
      'server/services/ai-brain/subagents/schedulingSubagent.ts',
      'server/services/ai-brain/subagents/visualQaSubagent.ts',
      'server/services/ai-brain/suggestedChangesService.ts',
      'server/services/ai-brain/supervisoryAgent.ts',
      'server/services/ai-brain/swarmCommanderService.ts',
      'server/services/ai-brain/toolCapabilityRegistry.ts',
      'server/services/ai-brain/trinityAgentParityLayer.ts',
      'server/services/ai-brain/trinityAnalyticsService.ts',
      'server/services/ai-brain/trinityAnomalyDetector.ts',
      'server/services/ai-brain/trinityAutonomousNotifier.ts',
      'server/services/ai-brain/trinityAutonomousOps.ts',
      'server/services/ai-brain/trinityBusinessIntelligence.ts',
      'server/services/ai-brain/trinityBusinessProMode.ts',
      'server/services/ai-brain/trinityChatService.ts',
      'server/services/ai-brain/trinityCodeOps.ts',
      'server/services/ai-brain/trinityCodeOpsActions.ts',
      'server/services/ai-brain/trinityConfidenceTracker.ts',
      'server/services/ai-brain/trinityContentGuardrails.ts',
      'server/services/ai-brain/trinityContextManager.ts',
      'server/services/ai-brain/trinityControlConsole.ts',
      'server/services/ai-brain/trinityCrossDomainIntelligence.ts',
      'server/services/ai-brain/trinityEnhancedModeActions.ts',
      'server/services/ai-brain/trinityExecutionFabric.ts',
      'server/services/ai-brain/trinityFastDiagnostic.ts',
      'server/services/ai-brain/trinityFrontierActions.ts',
      'server/services/ai-brain/trinityFrontierCapabilities.ts',
      'server/services/ai-brain/trinityGuruMode.ts',
      'server/services/ai-brain/trinityKnowledgeService.ts',
      'server/services/ai-brain/trinityMemoryOptimizer.ts',
      'server/services/ai-brain/trinityMemoryService.ts',
      'server/services/ai-brain/trinityNotificationBridge.ts',
      'server/services/ai-brain/trinityOrchestrationGovernance.ts',
      'server/services/ai-brain/trinityOrgIntelligenceService.ts',
      'server/services/ai-brain/trinityPersona.ts',
      'server/services/ai-brain/trinityPlatformConnector.ts',
      'server/services/ai-brain/trinityQuickBooksSnapshot.ts',
      'server/services/ai-brain/trinityReflectionEngine.ts',
      'server/services/ai-brain/trinityScanOrchestrator.ts',
      'server/services/ai-brain/trinitySelfAssessment.ts',
      'server/services/ai-brain/trinitySelfAwarenessService.ts',
      'server/services/ai-brain/trinitySelfEditGovernance.ts',
      'server/services/ai-brain/trinitySentinel.ts',
      'server/services/ai-brain/trinityThoughtEngine.ts',
      'server/services/ai-brain/trinityVelocityEngine.ts',
      'server/services/ai-brain/trinityVoice.ts',
      'server/services/ai-brain/trinityWorkOrderActions.ts',
      'server/services/ai-brain/trinityWorkOrderSystem.ts',
      'server/services/ai-brain/types.ts',
      'server/services/ai-brain/uiControlSubagent.ts',
      'server/services/ai-brain/uiShellBrainActions.ts',
      'server/services/ai-brain/unifiedLifecycleManager.ts',
      'server/services/ai-brain/universalDiagnosticOrchestrator.ts',
      'server/services/ai-brain/workboardService.ts',
      'server/services/ai-brain/workflowApprovalService.ts',
      'server/services/ai-brain/workflowLedger.ts',
      'server/services/ai-brain/workspaceContextService.ts',
      'server/services/automation-engine.ts',
      'server/services/automation-schemas.ts',
      'server/services/automation/automationCheckpointer.ts',
      'server/services/automation/billableHoursAggregator.ts',
      'server/services/automation/coaileagueScoringService.ts',
      'server/services/automation/coveragePipeline.ts',
      'server/services/automation/employeeScoring.ts',
      'server/services/automation/holidayDetector.ts',
      'server/services/automation/loneWorkerSafetyService.ts',
      'server/services/automation/notificationEventCoverage.ts',
      'server/services/automation/payrollHoursAggregator.ts',
      'server/services/automation/rateResolver.ts',
      'server/services/automation/shiftCompletionBridge.ts',
      'server/services/automation/shiftMonitoringService.ts',
      'server/services/automation/trinityAutomationToggle.ts',
      'server/services/automationEventsService.ts',
      'server/services/automationMetrics.ts',
      'server/services/automationRollbackService.ts',
      'server/services/autonomy/helpers.ts',
      'server/services/autonomy/migrateExistingRates.ts',
      'server/services/billingAutomation.ts',
      'server/services/configRegistry.ts',
      'server/services/emailAutomation.ts',
      'server/services/fieldOperations/trinityFieldOpsIntegration.ts',
      'server/services/ircEventRegistry.ts',
      'server/services/onboardingAutomation.ts',
      'server/services/orchestration/approvalGateEnforcement.ts',
      'server/services/orchestration/automationExecutionTracker.ts',
      'server/services/orchestration/automationOrchestration.ts',
      'server/services/orchestration/automationTriggerService.ts',
      'server/services/orchestration/crossDomainExceptionService.ts',
      'server/services/orchestration/index.ts',
      'server/services/orchestration/notificationAcknowledgmentService.ts',
      'server/services/orchestration/onboardingQuickBooksFlow.ts',
      'server/services/orchestration/onboardingStateMachine.ts',
      'server/services/orchestration/orchestratedBusinessOps.ts',
      'server/services/orchestration/quickbooksOrchestration.ts',
      'server/services/orchestration/scheduleLifecycleOrchestrator.ts',
      'server/services/orchestration/trinitySchedulingOrchestrator.ts',
      'server/services/orchestration/universalStepLogger.ts',
      'server/services/payrollAutomation.ts',
      'server/services/pulseSurveyAutomation.ts',
      'server/services/quickFix/quickFixService.ts',
      'server/services/routeHealthService.ts',
      'server/services/sandbox/index.ts',
      'server/services/sandbox/sandboxQuickBooksSimulator.ts',
      'server/services/sandbox/sandboxSimulationService.ts',
      'server/services/sandbox/trinityAutomationTestRunner.ts',
      'server/services/scheduling/trinityAutonomousScheduler.ts',
      'server/services/scheduling/trinityOrchestrationBridge.ts',
      'server/services/scheduling/trinityShiftGenerator.ts',
      'server/services/shared/trinityHumanPersonality.ts',
      'server/services/trinity/eventBus.ts',
      'server/services/trinity/trinityFieldIntelligence.ts',
      'server/services/trinity/trinityOrchestrationAdapter.ts',
      'server/services/trinity/trinityOrchestrationGateway.ts',
      'server/services/trinity/weeklyPlatformAudit.ts',
      'server/services/trinityContext.ts',
      'server/services/trinityDataIntegrityScanner.ts',
      'server/services/trinityDecisionLogger.ts',
      'server/services/trinityEmailOrchestration.ts',
      'server/services/trinityEventSubscriptions.ts',
      'server/services/trinityInvoiceNumbering.ts',
      'server/services/trinityMaintenanceOrchestrator.ts',
      'server/services/trinityOutreachService.ts',
      'server/services/trinityStaffing/clientConfirmationService.ts',
      'server/services/trinityStaffing/escalationChainService.ts',
      'server/services/trinityStaffing/index.ts',
      'server/services/trinityStaffing/orchestrator.ts',
      'server/services/trinityStaffing/workRequestParser.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 9: Communications
  // ─────────────────────────────────────────────────
  comms: {
    label: 'Communications',
    schemaIndex: 'shared/schema/domains/comms/index.ts',
    tables: [
      'userMascotPreferences',
      'chatConversations',
      'chatMessages',
      'messageReactions',
      'messageReadReceipts',
      'chatMacros',
      'typingIndicators',
      'chatUploads',
      'roomEvents',
      'dmAuditRequests',
      'dmAccessLogs',
      'conversationEncryptionKeys',
      'chatParticipants',
      'blockedContacts',
      'conversationUserState',
      'messageDeletedFor',
      'emailTemplates',
      'emailSends',
      'emailSequences',
      'sequenceSends',
      'motdMessages',
      'motdAcknowledgment',
      'chatAgreementAcceptances',
      'organizationChatRooms',
      'organizationChatChannels',
      'organizationRoomMembers',
      'notifications',
      'pushSubscriptions',
      'userNotificationPreferences',
      'chatConnections',
      'emailEvents',
      'emailUnsubscribes',
      'internalMailboxes',
      'internalEmailFolders',
      'internalEmails',
      'internalEmailRecipients',
      'roomAnalytics',
      'roomAnalyticsTimeseries',
      'mascotMotionProfiles',
      'holidayMascotDecor',
      'holidayMascotHistory',
      'externalEmailsSent',
      'emailDrafts',
      'contractorCommunications',
      'inboundEmails',
      'broadcasts',
      'broadcastRecipients',
      'broadcastFeedback',
      'channelBridges',
      'bridgeConversations',
      'bridgeMessages',
      'trinityEmailConversations',
    ],
    mounts: [
      '/api/chat',
      '/api/chat/rooms',
      '/api/chat/manage',
      '/api/chat/upload',
      '/api/broadcasts',
      '/api/bridges',
      '/api/emails',
      '/api/email-attachments',
      '/api/internal-email',
      '/api/notifications',
      '/api/sms',
      '/api/mascot',
    ],
    routes: [
      'server/routes/broadcasts.ts',
      'server/routes/chat-management.ts',
      'server/routes/chat-rooms.ts',
      'server/routes/chat-uploads.ts',
      'server/routes/chat.ts',
      'server/routes/chatInlineRoutes.ts',
      'server/routes/commInlineRoutes.ts',
      'server/routes/commOsRoutes.ts',
      'server/routes/email-attachments.ts',
      'server/routes/emailUnsubscribe.ts',
      'server/routes/emails.ts',
      'server/routes/externalEmailRoutes.ts',
      'server/routes/internalEmails.ts',
      'server/routes/mascot-routes.ts',
      'server/routes/messageBridgeRoutes.ts',
      'server/routes/notifications.ts',
      'server/routes/privateMessageRoutes.ts',
      'server/routes/resendWebhooks.ts',
      'server/routes/smsRoutes.ts',
      'server/routes/twilioWebhooks.ts',
    ],
    services: [
      'server/services/ChatServerHub.ts',
      'server/services/MessageBridgeService.ts',
      'server/services/aiNotificationService.ts',
      'server/services/broadcastService.ts',
      'server/services/chatParityService.ts',
      'server/services/chatSentimentService.ts',
      'server/services/chatroomCommandService.ts',
      'server/services/compliance/complianceScoringBridge.ts',
      'server/services/compliance/documentPipelineBridge.ts',
      'server/services/emailIntelligenceService.ts',
      'server/services/emailService.ts',
      'server/services/fieldOperations/smsFailoverService.ts',
      'server/services/notificationCleanupService.ts',
      'server/services/notificationInit.ts',
      'server/services/notificationService.ts',
      'server/services/notificationStateManager.ts',
      'server/services/privacy/index.ts',
      'server/services/privacy/orgDataPrivacyGuard.ts',
      'server/services/pushNotificationService.ts',
      'server/services/roomAnalyticsService.ts',
      'server/services/roomLifecycleService.ts',
      'server/services/smsService.ts',
      'server/services/universalNotificationEngine.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 10: Clients & Sites
  // ─────────────────────────────────────────────────
  clients: {
    label: 'Clients & Sites',
    schemaIndex: 'shared/schema/domains/clients/index.ts',
    tables: [
      'clients',
      'subClients',
      'postOrderTemplates',
      'clientRates',
      'contacts',
      'partnerConnections',
      'sites',
      'siteContacts',
      'businessLocations',
      'clientContracts',
      'clientContractAuditLog',
      'clientContractAccessTokens',
      'clientContractPipelineUsage',
      'clientPortalReports',
      'siteBriefings',
      'slaContracts',
    ],
    mounts: [
      '/api/clients',
      '/api/contracts',
      '/api/site-briefings',
    ],
    routes: [
      'server/routes/clientRoutes.ts',
      'server/routes/contractPipelineRoutes.ts',
      'server/routes/siteBriefingRoutes.ts',
    ],
    services: [
      'server/services/clientProspectService.ts',
      'server/services/fieldOperations/clientReportService.ts',
      'server/services/github/githubClient.ts',
      'server/services/helpai/clientPortalHelpAIService.ts',
      'server/services/partners/gusto.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 11: Compliance & Documents
  // ─────────────────────────────────────────────────
  compliance: {
    label: 'Compliance & Documents',
    schemaIndex: 'shared/schema/domains/compliance/index.ts',
    tables: [
      'securityIncidents',
      'documentSignatures',
      'companyPolicies',
      'policyAcknowledgments',
      'documentAccessLogs',
      'governanceApprovals',
      'customForms',
      'customFormSubmissions',
      'termsAcknowledgments',
      'serviceIncidentReports',
      'complianceReports',
      'orgDocumentSignatures',
      'darReports',
      'complianceStates',
      'complianceDocumentTypes',
      'complianceRequirements',
      'complianceDocuments',
      'complianceApprovals',
      'complianceExpirations',
      'complianceAlerts',
      'regulatorAccess',
      'complianceScores',
      'complianceChecklists',
      'officerReadiness',
      'officerComplaints',
      'officerGrievances',
      'complianceWindows',
      'documentRetentionLog',
      'complianceRegistryEntries',
      'stateLicenseVerifications',
      'documentTemplates',
      'documentInstances',
      'signatures',
      'documentVault',
      'incidentReports',
      'rmsCases',
      'abuseViolations',
      'trainingCertifications',
      'backgroundCheckProviders',
    ],
    mounts: [
      '/api/security-compliance',
      '/api/documents',
      '/api/document-library',
      '/api/document-vault',
      '/api/forms',
      '/api/credentials',
      '/api/policy-compliance',
    ],
    routes: [
      'server/routes/compliance/approvals.ts',
      'server/routes/compliance/auditTrail.ts',
      'server/routes/compliance/checklists.ts',
      'server/routes/compliance/documentTypes.ts',
      'server/routes/compliance/documents.ts',
      'server/routes/compliance/enforcement.ts',
      'server/routes/compliance/index.ts',
      'server/routes/compliance/matrix.ts',
      'server/routes/compliance/packets.ts',
      'server/routes/compliance/records.ts',
      'server/routes/compliance/regulator.ts',
      'server/routes/compliance/requirements.ts',
      'server/routes/compliance/states.ts',
      'server/routes/complianceInlineRoutes.ts',
      'server/routes/complianceRoutes.ts',
      'server/routes/credentialRoutes.ts',
      'server/routes/documentLibraryRoutes.ts',
      'server/routes/documentRoutes.ts',
      'server/routes/documentTemplateRoutes.ts',
      'server/routes/documentVaultRoutes.ts',
      'server/routes/fileDownload.ts',
      'server/routes/formBuilderRoutes.ts',
      'server/routes/formRoutes.ts',
      'server/routes/policyComplianceRoutes.ts',
      'server/routes/uacpRoutes.ts',
    ],
    services: [
      'server/services/audit-logger.ts',
      'server/services/compliance/auditorService.ts',
      'server/services/compliance/certificationTypes.ts',
      'server/services/compliance/complianceEnforcementService.ts',
      'server/services/compliance/financialAuditService.ts',
      'server/services/compliance/stateComplianceConfig.ts',
      'server/services/complianceAlertService.ts',
      'server/services/complianceMonitoring.ts',
      'server/services/complianceReports.ts',
      'server/services/darPdfService.ts',
      'server/services/documentDeliveryService.ts',
      'server/services/documentExtraction.ts',
      'server/services/documentSigningService.ts',
      'server/services/geoCompliance.ts',
      'server/services/incidentRoutingService.ts',
      'server/services/infrastructure/complianceSignoffService.ts',
      'server/services/proposalPdfService.ts',
      'server/services/reportWorkflowEngine.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 12: Audit & Platform Ops
  // ─────────────────────────────────────────────────
  audit: {
    label: 'Audit & Platform Ops',
    schemaIndex: 'shared/schema/domains/audit/index.ts',
    tables: [
      'leaderActions',
      'auditLogs',
      'reportTemplates',
      'reportSubmissions',
      'reportWorkflowConfigs',
      'reportApprovalSteps',
      'lockedReportRecords',
      'reportAttachments',
      'customerReportAccess',
      'kpiAlerts',
      'kpiAlertTriggers',
      'benchmarkMetrics',
      'employerRatings',
      'employerBenchmarkScores',
      'webhookDeliveries',
      'autoReports',
      'searchQueries',
      'metricsSnapshots',
      'userPlatformUpdateViews',
      'auditProofPacks',
      'rateThrottleLogs',
      'oversightEvents',
      'writeAheadLog',
      'alertConfigurations',
      'alertHistory',
      'alertRateLimits',
      'platformScanSnapshots',
      'platformChangeEvents',
      'featureUsageEvents',
      'apiUsageEvents',
      'supervisorTelemetry',
      'platformAwarenessEvents',
      'backupRecords',
      'officerScoreEvents',
      'auditorAccounts',
      'auditSessions',
      'auditorDocumentRequests',
      'auditFindings',
      'auditorFollowups',
      'auditorDocumentSafe',
      'platformConfigSnapshots',
      'platformConfigAudit',
      'savedReports',
      'universalAuditTrail',
      'reportAuditTrail',
      'activities',
      'alertRules',
    ],
    mounts: [
      '/api/audit',
      '/api/analytics',
      '/api/reports',
      '/api/metrics',
      '/api/insights',
      '/api/dashboard',
      '/api/exports',
      '/api/kpi-alerts',
      '/api/infrastructure',
      '/api/health',
      '/api/platform',
      '/api/maintenance',
      '/api-docs',
    ],
    routes: [
      'server/routes/admin/aiCosts.ts',
      'server/routes/adminRoutes.ts',
      'server/routes/analyticsRoutes.ts',
      'server/routes/apiDocsRoutes.ts',
      'server/routes/auditRoutes.ts',
      'server/routes/command-documentation.ts',
      'server/routes/dashboardRoutes.ts',
      'server/routes/database-parity.ts',
      'server/routes/deletionProtectionRoutes.ts',
      'server/routes/exportRoutes.ts',
      'server/routes/health.ts',
      'server/routes/infrastructureRoutes.ts',
      'server/routes/insightsRoutes.ts',
      'server/routes/kpiAlertRoutes.ts',
      'server/routes/metricsRoutes.ts',
      'server/routes/middleware-quality.ts',
      'server/routes/miscRoutes.ts',
      'server/routes/ownerAnalytics.ts',
      'server/routes/platformRoutes.ts',
      'server/routes/reportsRoutes.ts',
      'server/routes/resilience-api.ts',
      'server/routes/sandbox-routes.ts',
    ],
    services: [
      'server/services/advancedAnalyticsService.ts',
      'server/services/advancedUsageAnalyticsService.ts',
      'server/services/aiActivityService.ts',
      'server/services/aiSchedulingTriggerService.ts',
      'server/services/aiSearchService.ts',
      'server/services/alertService.ts',
      'server/services/analytics/index.ts',
      'server/services/analyticsAIService.ts',
      'server/services/analyticsDataService.ts',
      'server/services/analyticsStats.ts',
      'server/services/animationControlService.ts',
      'server/services/availabilityService.ts',
      'server/services/businessInsights/businessInsightsService.ts',
      'server/services/businessOwnerAnalyticsService.ts',
      'server/services/calendarService.ts',
      'server/services/crossDeviceSyncService.ts',
      'server/services/dailyDigestService.ts',
      'server/services/databaseMaintenance.ts',
      'server/services/databaseParityScanner.ts',
      'server/services/deletionProtectionService.ts',
      'server/services/developmentSeed.ts',
      'server/services/developmentSeedEnrichment.ts',
      'server/services/diagnosticServiceRegistry.ts',
      'server/services/disputeAI.ts',
      'server/services/dynamicMessageService.ts',
      'server/services/employerRatingsService.ts',
      'server/services/entityCreationNotifier.ts',
      'server/services/escalationMatrixService.ts',
      'server/services/executionPipeline.ts',
      'server/services/exportService.ts',
      'server/services/externalMonitoring.ts',
      'server/services/featureRegistryService.ts',
      'server/services/fieldOperations/gpsInactivityMonitor.ts',
      'server/services/fieldOperations/index.ts',
      'server/services/fieldOperations/panicProtocolService.ts',
      'server/services/fieldOperations/postOrderQuizService.ts',
      'server/services/fieldOperations/presenceMonitorService.ts',
      'server/services/fieldOperations/priorityMessageService.ts',
      'server/services/fieldOperations/proofOfServiceService.ts',
      'server/services/finance/financeSettingsService.ts',
      'server/services/finance/middlewareFeeService.ts',
      'server/services/finance/profitLossService.ts',
      'server/services/financialLedgerService.ts',
      'server/services/financialPipelineOrchestrator.ts',
      'server/services/formWorkflowService.ts',
      'server/services/healthCheck.ts',
      'server/services/healthService.ts',
      'server/services/heatmapService.ts',
      'server/services/helpOsQueue.ts',
      'server/services/helposService/index.ts',
      'server/services/helposSettingsService.ts',
      'server/services/icalService.ts',
      'server/services/identityService.ts',
      'server/services/inboundOpportunityAgent.ts',
      'server/services/infrastructure/apiKeyRotationService.ts',
      'server/services/infrastructure/auditTrailExportService.ts',
      'server/services/infrastructure/backupService.ts',
      'server/services/infrastructure/cdnCachingService.ts',
      'server/services/infrastructure/chaosTestingService.ts',
      'server/services/infrastructure/circuitBreaker.ts',
      'server/services/infrastructure/connectionPooling.ts',
      'server/services/infrastructure/disasterRecoveryService.ts',
      'server/services/infrastructure/distributedTracing.ts',
      'server/services/infrastructure/durableJobQueue.ts',
      'server/services/infrastructure/errorTrackingService.ts',
      'server/services/infrastructure/healthCheckAggregation.ts',
      'server/services/infrastructure/index.ts',
      'server/services/infrastructure/launchReadinessService.ts',
      'server/services/infrastructure/launchRehearsalService.ts',
      'server/services/infrastructure/logAggregationService.ts',
      'server/services/infrastructure/metricsDashboard.ts',
      'server/services/infrastructure/operationsRunbookService.ts',
      'server/services/infrastructure/productionSeeding.ts',
      'server/services/infrastructure/rateLimiting.ts',
      'server/services/infrastructure/securityHardeningService.ts',
      'server/services/infrastructure/slaMonitoring.ts',
      'server/services/integrations/gustoIntegration.ts',
      'server/services/integrations/index.ts',
      'server/services/integrations/quotaEnforcementService.ts',
      'server/services/integrations/webhookVerifier.ts',
      'server/services/issueDetectionService.ts',
      'server/services/jobRetrievalService.ts',
      'server/services/maintenanceModeService.ts',
      'server/services/middlewareQualityScanner.ts',
      'server/services/monitoringService.ts',
      'server/services/officerStatusService.ts',
      'server/services/photoGeofenceService.ts',
      'server/services/platform/aiRequestDeduplicator.ts',
      'server/services/platform/cacheManager.ts',
      'server/services/platform/index.ts',
      'server/services/platform/lazyInitializer.ts',
      'server/services/platform/writeBatcher.ts',
      'server/services/platformEventBus.ts',
      'server/services/platformMaintenanceService.ts',
      'server/services/predictionos.ts',
      'server/services/premiumFeatureGating.ts',
      'server/services/processingMetricsService.ts',
      'server/services/productionSeed.ts',
      'server/services/reportService.ts',
      'server/services/resilience/circuitBreaker.ts',
      'server/services/resilience/rateLimitQueue.ts',
      'server/services/schemaParityService.ts',
      'server/services/sentimentAnalyzer.ts',
      'server/services/smartReplyService.ts',
      'server/services/staffHierarchy.ts',
      'server/services/staffingClaimService.ts',
      'server/services/taxCalculator.ts',
      'server/services/taxFilingAssistanceService.ts',
      'server/services/taxFormGeneratorService.ts',
      'server/services/timesheetReportService.ts',
      'server/services/tokenCleanupService.ts',
      'server/services/training/scenarioSeeder.ts',
      'server/services/trainingRateService.ts',
      'server/services/uacp/agentIdentityService.ts',
      'server/services/uacp/policyDecisionPoint.ts',
      'server/services/uacp/uacpOrchestrationActions.ts',
      'server/services/uiShellValidation.ts',
      'server/services/universalAuditService.ts',
      'server/services/universalConfigRegistry.ts',
      'server/services/universalLoader/deviceLoader.ts',
      'server/services/unreadMessageService.ts',
      'server/services/utils/scheduling.ts',
      'server/services/virusScanService.ts',
      'server/services/websocketCounter.ts',
      'server/services/whatsNewService.ts',
      'server/services/workflowStatusService.ts',
      'server/services/wsConnectionCleanup.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 13: Support & HelpAI
  // ─────────────────────────────────────────────────
  support: {
    label: 'Support & HelpAI',
    schemaIndex: 'shared/schema/domains/support/index.ts',
    tables: [
      'escalationTickets',
      'supportSessions',
      'supportTickets',
      'helposFaqs',
      'faqVersions',
      'faqGapEvents',
      'faqSearchHistory',
      'helpOsQueue',
      'supportRooms',
      'supportTicketAccess',
      'knowledgeArticles',
      'knowledgeQueries',
      'platformUpdates',
      'supportRegistry',
      'helposAiSessions',
      'helposAiTranscriptEntries',
      'helpaiRegistry',
      'helpaiIntegrations',
      'helpaiCredentials',
      'helpaiAuditLog',
      'helpaiSessions',
      'helpaiActionLog',
      'helpaiSafetyCodes',
      'serviceControlStates',
      'supportInterventions',
      'supportSessionElevations',
      'knowledgeGapLogs',
      'knowledgeEntities',
      'knowledgeRelationships',
      'knowledgeLearningEntries',
      'platformConfigRegistry',
    ],
    mounts: [
      '/api/helpdesk',
      '/api/tickets',
      '/api/support',
      '/api/support/chat',
      '/api/support/command',
      '/api/support/assisted-onboarding',
    ],
    routes: [
      'server/routes/helpdeskRoutes.ts',
      'server/routes/support-chat.ts',
      'server/routes/support-command-console.ts',
      'server/routes/supportActionRoutes.ts',
      'server/routes/supportRoutes.ts',
      'server/routes/ticketSearchRoutes.ts',
    ],
    services: [
      'server/services/autoTicketCreation.ts',
      'server/services/helpAICapabilities.ts',
      'server/services/helpai/contentModerationService.ts',
      'server/services/helpai/helpAIBotService.ts',
      'server/services/helpai/helpAIOrchestrator.ts',
      'server/services/helpai/helpaiAuditService.ts',
      'server/services/helpai/helpaiIntegrationService.ts',
      'server/services/helpai/helpaiRegistryService.ts',
      'server/services/helpai/index.ts',
      'server/services/helpai/platformActionHub.ts',
      'server/services/shared/helpaiMemoryService.ts',
      'server/services/supportActionsService.ts',
      'server/services/supportSessionService.ts',
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 14: Sales & CRM
  // ─────────────────────────────────────────────────
  sales: {
    label: 'Sales & CRM',
    schemaIndex: 'shared/schema/domains/sales/index.ts',
    tables: [
      'leads',
      'deals',
      'rfps',
      'proposals',
      'dealTasks',
      'testimonials',
      'clientProspects',
      'pipelineDeals',
      'rfpDocuments',
    ],
    mounts: [
      '/api/sales',
      '/api/leads',
      '/api/public/leads',
      '/api/rfp',
      '/api/proposals',
      '/api/testimonials',
    ],
    routes: [
      'server/routes/leadCrmRoutes.ts',
      'server/routes/proposalRoutes.ts',
      'server/routes/publicLeads.ts',
      'server/routes/rfpEthicsRoutes.ts',
      'server/routes/rfpPipelineRoutes.ts',
      'server/routes/salesInlineRoutes.ts',
      'server/routes/salesRoutes.ts',
      'server/routes/testimonials.ts',
    ],
    services: [
    ],
  },

  // ─────────────────────────────────────────────────
  // Domain 15: Field Ops
  // ─────────────────────────────────────────────────
  ops: {
    label: 'Field Ops',
    schemaIndex: 'shared/schema/domains/ops/index.ts',
    tables: [
      'assets',
      'assetSchedules',
      'assetUsageLogs',
      'maintenanceAlerts',
      'maintenanceAcknowledgments',
      'dispatchIncidents',
      'dispatchAssignments',
      'unitStatuses',
      'dispatchLogs',
      'agentIdentities',
      'equipmentItems',
      'equipmentAssignments',
      'equipmentMaintenanceLogs',
      'weapons',
      'weaponCheckouts',
      'guardTours',
      'guardTourCheckpoints',
      'guardTourScans',
      'vehicles',
      'vehicleAssignments',
      'vehicleMaintenance',
      'panicAlerts',
      'loneWorkerSessions',
      'boloAlerts',
      'lostFoundItems',
      'visitorLogs',
    ],
    mounts: [
      '/api/dispatch',
      '/api/cad',
      '/api/situation',
      '/api/safety',
      '/api/rms',
      '/api/vehicles',
      '/api/equipment',
      '/api/maintenance',
      '/api/incidents',
      '/api/incident-reports',
      '/api/guard-tours',
      '/api/migration',
    ],
    routes: [
      'server/routes/cadRoutes.ts',
      'server/routes/dispatch.ts',
      'server/routes/equipmentRoutes.ts',
      'server/routes/guardTourRoutes.ts',
      'server/routes/incidentPipelineRoutes.ts',
      'server/routes/maintenanceRoutes.ts',
      'server/routes/migration.ts',
      'server/routes/mobileWorkerRoutes.ts',
      'server/routes/rmsRoutes.ts',
      'server/routes/safetyRoutes.ts',
      'server/routes/situationRoutes.ts',
      'server/routes/vehicleRoutes.ts',
    ],
    services: [
      'server/services/aiGuardRails.ts',
      'server/services/dbMigrationService.ts',
      'server/services/dispatch.ts',
      'server/services/migration.ts',
      'server/services/workspaceGuard.ts',
      'server/services/ops/panicAlertService.ts',
      'server/services/ops/loneWorkerService.ts',
      'server/services/ops/boloService.ts',
      'server/services/ops/visitorLogService.ts',
      'server/services/ops/assetTrackingService.ts',
      'server/services/ops/weaponCheckService.ts',
      'server/services/ops/lostFoundService.ts',
    ],
  },

} as const;

export type DomainName = keyof typeof DOMAIN_CONTRACT;

/** Type-safe helper to get the domain for a given file or route. */
export const DOMAIN_NAMES: DomainName[] = [
  'auth',
  'orgs',
  'workforce',
  'scheduling',
  'time',
  'payroll',
  'billing',
  'trinity',
  'comms',
  'clients',
  'compliance',
  'audit',
  'support',
  'sales',
  'ops',
] as const;
