/**
 * Field Operations Configuration Registry
 * Centralized configuration for all field operations features
 * Supports per-org and per-post customization
 */

import { z } from 'zod';
import { MessagePriority } from '../types/fieldOperations';

// ═══════════════════════════════════════════════════════════════════════════
// CONFIGURATION SCHEMAS
// ═══════════════════════════════════════════════════════════════════════════

export const GeofenceConfigSchema = z.object({
  defaultRadius: z.number().min(10).max(5000).default(100),
  enforceOnClockIn: z.boolean().default(true),
  enforceOnClockOut: z.boolean().default(true),
  enforceOnPOS: z.boolean().default(true),
  allowOverride: z.boolean().default(true),
  overrideRequiresReason: z.boolean().default(true)
});

export const POSConfigSchema = z.object({
  enabled: z.boolean().default(true),
  frequency: z.enum(['hourly', 'custom']).default('hourly'),
  customIntervalMinutes: z.number().min(15).max(480).optional(),
  startOffsetMinutes: z.number().min(0).max(60).default(15),
  gracePeriodMinutes: z.number().min(5).max(60).default(15),
  gpsRequired: z.boolean().default(true),
  overlayEnabled: z.boolean().default(true),
  overlayPosition: z.enum(['top', 'bottom']).default('bottom'),
  minimumPerShift: z.number().min(0).max(24).default(0),
  reminderBeforeDueMinutes: z.number().min(1).max(30).default(5),
  notifyOnMissed: z.boolean().default(true),
  escalateAfterMisses: z.number().min(1).max(10).default(2)
});

export const PresenceMonitoringConfigSchema = z.object({
  enabled: z.boolean().default(true),
  checkIntervalMinutes: z.number().min(1).max(60).default(5),
  backgroundTrackingEnabled: z.boolean().default(true),
  detectLeftGeofence: z.boolean().default(true),
  leftGeofenceGraceMinutes: z.number().min(1).max(60).default(5),
  detectRapidMovement: z.boolean().default(true),
  rapidMovementThresholdMps: z.number().min(10).max(100).default(50),
  detectDeviceChange: z.boolean().default(true),
  lowGpsAccuracyThresholdMeters: z.number().min(50).max(500).default(100)
});

export const ClockInOutConfigSchema = z.object({
  gpsRequired: z.boolean().default(true),
  geofenceEnforced: z.boolean().default(true),
  photoOnClockIn: z.boolean().default(false),
  photoOnClockOut: z.boolean().default(false),
  allowManualClock: z.boolean().default(true),
  manualClockRequiresApproval: z.boolean().default(true),
  earlyClockInMinutes: z.number().min(0).max(60).default(15),
  lateClockOutGraceMinutes: z.number().min(0).max(30).default(5)
});

export const AckDeadlinesSchema = z.object({
  important: z.number().min(5).max(120).default(30),
  urgent: z.number().min(1).max(60).default(10),
  emergency: z.number().min(1).max(30).default(5),
  panic: z.number().min(1).max(10).default(1)
});

export const PriorityMessageConfigSchema = z.object({
  defaultAckDeadlines: AckDeadlinesSchema.default({
    important: 30,
    urgent: 10,
    emergency: 5,
    panic: 1
  }),
  escalationEnabled: z.boolean().default(true),
  maxEscalationLevels: z.number().min(1).max(10).default(3),
  smsFailoverEnabled: z.boolean().default(true),
  smsFailoverAfterMinutes: z.number().min(1).max(30).default(5)
});

export const PanicProtocolConfigSchema = z.object({
  enabled: z.boolean().default(true),
  holdDurationSeconds: z.number().min(1).max(10).default(3),
  autoRecordAudio: z.boolean().default(true),
  audioRecordingDurationSeconds: z.number().min(60).max(600).default(300),
  autoCapturePhotos: z.boolean().default(true),
  autoCallEnabled: z.boolean().default(false),
  autoCallNumber: z.string().optional(),
  notifyAllSupervisors: z.boolean().default(true),
  notifyEmergencyContacts: z.boolean().default(true),
  notifyPlatformSupport: z.boolean().default(true)
});

export const ShiftHandoffConfigSchema = z.object({
  enabled: z.boolean().default(true),
  autoGenerateSummary: z.boolean().default(true),
  requireOutgoingConfirmation: z.boolean().default(true),
  requireIncomingConfirmation: z.boolean().default(true),
  checklistEnabled: z.boolean().default(true),
  customChecklistItems: z.array(z.object({
    label: z.string(),
    required: z.boolean()
  })).default([]),
  notifyOnMissedHandoff: z.boolean().default(true)
});

export const ClientReportConfigSchema = z.object({
  autoGenerateDaily: z.boolean().default(false),
  autoGenerateWeekly: z.boolean().default(true),
  autoGenerateMonthly: z.boolean().default(true),
  includePOSPhotos: z.boolean().default(true),
  includePresenceData: z.boolean().default(true),
  includeIncidents: z.boolean().default(true),
  includeDiscrepancies: z.boolean().default(true),
  emailToClient: z.boolean().default(false),
  clientEmailAddresses: z.array(z.string().email()).default([])
});

export const FieldOperationsConfigSchema = z.object({
  orgId: z.string(),
  postId: z.string().optional(),
  
  geofence: GeofenceConfigSchema.default({}),
  pos: POSConfigSchema.default({}),
  presenceMonitoring: PresenceMonitoringConfigSchema.default({}),
  clockInOut: ClockInOutConfigSchema.default({}),
  priorityMessages: PriorityMessageConfigSchema.default({}),
  panicProtocol: PanicProtocolConfigSchema.default({}),
  shiftHandoff: ShiftHandoffConfigSchema.default({}),
  clientReports: ClientReportConfigSchema.default({}),
  
  updatedAt: z.date().default(() => new Date()),
  updatedBy: z.string().optional()
});

export type GeofenceConfig = z.infer<typeof GeofenceConfigSchema>;
export type POSConfig = z.infer<typeof POSConfigSchema>;
export type PresenceMonitoringConfig = z.infer<typeof PresenceMonitoringConfigSchema>;
export type ClockInOutConfig = z.infer<typeof ClockInOutConfigSchema>;
export type PriorityMessageConfig = z.infer<typeof PriorityMessageConfigSchema>;
export type PanicProtocolConfig = z.infer<typeof PanicProtocolConfigSchema>;
export type ShiftHandoffConfig = z.infer<typeof ShiftHandoffConfigSchema>;
export type ClientReportConfig = z.infer<typeof ClientReportConfigSchema>;
export type FieldOperationsConfig = z.infer<typeof FieldOperationsConfigSchema>;

// ═══════════════════════════════════════════════════════════════════════════
// DEFAULT CONFIGURATIONS
// ═══════════════════════════════════════════════════════════════════════════

export const DEFAULT_FIELD_OPS_CONFIG: Omit<FieldOperationsConfig, 'orgId'> = {
  geofence: {
    defaultRadius: 100,
    enforceOnClockIn: true,
    enforceOnClockOut: true,
    enforceOnPOS: true,
    allowOverride: true,
    overrideRequiresReason: true
  },
  pos: {
    enabled: true,
    frequency: 'hourly',
    startOffsetMinutes: 15,
    gracePeriodMinutes: 15,
    gpsRequired: true,
    overlayEnabled: true,
    overlayPosition: 'bottom',
    minimumPerShift: 0,
    reminderBeforeDueMinutes: 5,
    notifyOnMissed: true,
    escalateAfterMisses: 2
  },
  presenceMonitoring: {
    enabled: true,
    checkIntervalMinutes: 5,
    backgroundTrackingEnabled: true,
    detectLeftGeofence: true,
    leftGeofenceGraceMinutes: 5,
    detectRapidMovement: true,
    rapidMovementThresholdMps: 50,
    detectDeviceChange: true,
    lowGpsAccuracyThresholdMeters: 100
  },
  clockInOut: {
    gpsRequired: true,
    geofenceEnforced: true,
    photoOnClockIn: false,
    photoOnClockOut: false,
    allowManualClock: true,
    manualClockRequiresApproval: true,
    earlyClockInMinutes: 15,
    lateClockOutGraceMinutes: 5
  },
  priorityMessages: {
    defaultAckDeadlines: {
      important: 30,
      urgent: 10,
      emergency: 5,
      panic: 1
    },
    escalationEnabled: true,
    maxEscalationLevels: 3,
    smsFailoverEnabled: true,
    smsFailoverAfterMinutes: 5
  },
  panicProtocol: {
    enabled: true,
    holdDurationSeconds: 3,
    autoRecordAudio: true,
    audioRecordingDurationSeconds: 300,
    autoCapturePhotos: true,
    autoCallEnabled: false,
    notifyAllSupervisors: true,
    notifyEmergencyContacts: true,
    notifyPlatformSupport: true
  },
  shiftHandoff: {
    enabled: true,
    autoGenerateSummary: true,
    requireOutgoingConfirmation: true,
    requireIncomingConfirmation: true,
    checklistEnabled: true,
    customChecklistItems: [],
    notifyOnMissedHandoff: true
  },
  clientReports: {
    autoGenerateDaily: false,
    autoGenerateWeekly: true,
    autoGenerateMonthly: true,
    includePOSPhotos: true,
    includePresenceData: true,
    includeIncidents: true,
    includeDiscrepancies: true,
    emailToClient: false,
    clientEmailAddresses: []
  },
  updatedAt: new Date()
};

// ═══════════════════════════════════════════════════════════════════════════
// CONFIGURATION REGISTRY
// ═══════════════════════════════════════════════════════════════════════════

class FieldOperationsConfigRegistry {
  private configs: Map<string, FieldOperationsConfig> = new Map();
  
  getConfigKey(orgId: string, postId?: string): string {
    return postId ? `${orgId}:${postId}` : orgId;
  }
  
  getConfig(orgId: string, postId?: string): FieldOperationsConfig {
    const postKey = this.getConfigKey(orgId, postId);
    const orgKey = this.getConfigKey(orgId);
    
    const postConfig = this.configs.get(postKey);
    if (postConfig) return postConfig;
    
    const orgConfig = this.configs.get(orgKey);
    if (orgConfig) return orgConfig;
    
    return { ...DEFAULT_FIELD_OPS_CONFIG, orgId };
  }
  
  setConfig(config: FieldOperationsConfig): void {
    const key = this.getConfigKey(config.orgId, config.postId);
    config.updatedAt = new Date();
    this.configs.set(key, config);
    console.log(`[FieldOpsConfig] Updated config for ${key}`);
  }
  
  updateConfig(orgId: string, postId: string | undefined, updates: Partial<FieldOperationsConfig>): FieldOperationsConfig {
    const current = this.getConfig(orgId, postId);
    const updated = { ...current, ...updates, orgId, postId, updatedAt: new Date() };
    this.setConfig(updated);
    return updated;
  }
  
  deleteConfig(orgId: string, postId?: string): boolean {
    const key = this.getConfigKey(orgId, postId);
    return this.configs.delete(key);
  }
  
  listConfigs(): FieldOperationsConfig[] {
    return Array.from(this.configs.values());
  }
}

export const fieldOpsConfigRegistry = new FieldOperationsConfigRegistry();
