// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ads-company/AdCompanyFbPost.tsx": () => import("../components/mockups/ads-company/AdCompanyFbPost.tsx"),
  "./components/mockups/ads-company/AdCompanyFreeTrial.tsx": () => import("../components/mockups/ads-company/AdCompanyFreeTrial.tsx"),
  "./components/mockups/ads-company/AdCompanyFreeTrialEs.tsx": () => import("../components/mockups/ads-company/AdCompanyFreeTrialEs.tsx"),
  "./components/mockups/ads-company/AdCompanyIdentity.tsx": () => import("../components/mockups/ads-company/AdCompanyIdentity.tsx"),
  "./components/mockups/ads-company/AdCompanyOutcome.tsx": () => import("../components/mockups/ads-company/AdCompanyOutcome.tsx"),
  "./components/mockups/ads-company/AdCompanyPainPoint.tsx": () => import("../components/mockups/ads-company/AdCompanyPainPoint.tsx"),
  "./components/mockups/ads-regulatory/AdRegulatoryAllStates.tsx": () => import("../components/mockups/ads-regulatory/AdRegulatoryAllStates.tsx"),
  "./components/mockups/ads-regulatory/AdRegulatoryEmailBanner.tsx": () => import("../components/mockups/ads-regulatory/AdRegulatoryEmailBanner.tsx"),
  "./components/mockups/ads-regulatory/AdRegulatoryTcole.tsx": () => import("../components/mockups/ads-regulatory/AdRegulatoryTcole.tsx"),
  "./components/mockups/ads-regulatory/AdRegulatoryTcoleEs.tsx": () => import("../components/mockups/ads-regulatory/AdRegulatoryTcoleEs.tsx")
};
