/**
 * Autonomous Scheduler Service
 * Runs scheduled jobs for AutoForce™ autonomous operations:
 * - Nightly invoice generation (BillOS™)
 * - Weekly schedule generation (ScheduleOS™)
 * - Automatic payroll processing (PayrollOS™)
 * 
 * All automation activities are logged to AuditOS for compliance tracking.
 */

import cron from 'node-cron';
import { db } from '../db';
import { workspaces, employees } from '@shared/schema';
import { eq, and } from 'drizzle-orm';
import { generateUsageBasedInvoices } from './billos';
import { PayrollAutomationEngine } from './payrollAutomation';
import { ScheduleOSAI } from '../ai/scheduleos';
import { addDays, startOfWeek, endOfWeek, format } from 'date-fns';
import { shouldRunBiweekly, seedAnchor, advanceAnchor, detectAnchorDrift } from './utils/scheduling';
import { storage } from '../storage';

// ============================================================================
// AUTOMATION AUDIT LOGGING
// ============================================================================

/**
 * System user context for automation jobs
 * Used for all AuditOS audit logs generated by autonomous processes
 */
const AUTOFORCE_AUTOMATION_USER = {
  userId: 'system-autoforce',
  userName: 'AutoForce™ Automation',
  userEmail: 'automation@autoforce.ai',
  userRole: 'system' as const,
};

/**
 * Log automation job lifecycle (start, complete, error) to AuditOS
 * 
 * Ensures all automation activities are auditable and never fails the main job
 * if audit logging encounters errors.
 */
async function logAutomationLifecycle<T>(
  params: {
    jobType: 'invoicing' | 'scheduling' | 'payroll';
    workspaceId: string;
    workspaceName: string;
    runId: string;
  },
  runner: () => Promise<T>
): Promise<T> {
  const { jobType, workspaceId, workspaceName, runId } = params;
  const startTime = Date.now();

  // Log job start (don't fail if audit logging fails)
  try {
    await storage.createAuditLog({
      workspaceId,
      ...AUTOFORCE_AUTOMATION_USER,
      action: 'automation_job_start',
      entityType: 'automation_job',
      entityId: runId,
      entityDescription: `${jobType.toUpperCase()}OS™ automation started for ${workspaceName}`,
      metadata: {
        jobType,
        timestamp: new Date().toISOString(),
      },
    });
  } catch (error) {
    console.error(`[AUDIT WARNING] Failed to log automation start for ${workspaceName}:`, error);
  }

  try {
    // Execute the actual job
    const result = await runner();
    const duration = Date.now() - startTime;

    // Log job completion
    try {
      await storage.createAuditLog({
        workspaceId,
        ...AUTOFORCE_AUTOMATION_USER,
        action: 'automation_job_complete',
        entityType: 'automation_job',
        entityId: runId,
        entityDescription: `${jobType.toUpperCase()}OS™ automation completed for ${workspaceName}`,
        metadata: {
          jobType,
          duration,
          timestamp: new Date().toISOString(),
          result: typeof result === 'object' ? result : { value: result },
        },
      });
    } catch (error) {
      console.error(`[AUDIT WARNING] Failed to log automation completion for ${workspaceName}:`, error);
    }

    return result;
  } catch (error: any) {
    const duration = Date.now() - startTime;

    // Log job error
    try {
      await storage.createAuditLog({
        workspaceId,
        ...AUTOFORCE_AUTOMATION_USER,
        action: 'automation_job_error',
        entityType: 'automation_job',
        entityId: runId,
        entityDescription: `${jobType.toUpperCase()}OS™ automation failed for ${workspaceName}: ${error.message}`,
        metadata: {
          jobType,
          duration,
          error: error.message,
          stack: error.stack?.substring(0, 500), // Truncate stack trace
          timestamp: new Date().toISOString(),
        },
      });
    } catch (auditError) {
      console.error(`[AUDIT WARNING] Failed to log automation error for ${workspaceName}:`, auditError);
    }

    throw error; // Re-throw to maintain original error handling
  }
}

// ============================================================================
// CONFIGURATION
// ============================================================================

const SCHEDULER_CONFIG = {
  invoicing: {
    enabled: true,
    schedule: '0 2 * * *', // Every day at 2 AM
    description: 'Daily check for invoice generation based on workspace schedules'
  },
  scheduling: {
    enabled: true,
    schedule: '0 23 * * *', // Every day at 11 PM
    description: 'Daily check for schedule generation based on workspace intervals'
  },
  payroll: {
    enabled: true,
    schedule: '0 3 * * *', // Every day at 3 AM (after invoicing)
    description: 'Daily check for payroll processing based on workspace pay periods'
  }
};

// ============================================================================
// JOB HANDLERS
// ============================================================================

/**
 * Nightly Invoice Generation
 * Runs for all workspaces with auto-invoicing enabled
 */
async function runNightlyInvoiceGeneration() {
  console.log('=================================================');
  console.log('🤖 BILLΟΣ™ AUTONOMOUS INVOICING - START');
  console.log(`Timestamp: ${new Date().toISOString()}`);
  console.log('=================================================');

  try {
    // Get all active workspaces with auto-invoicing enabled
    const activeWorkspaces = await db
      .select()
      .from(workspaces)
      .where(
        and(
          eq(workspaces.isSuspended, false),
          eq(workspaces.isFrozen, false),
          eq(workspaces.isLocked, false),
          eq(workspaces.autoInvoicingEnabled, true)
        )
      );

    console.log(`Found ${activeWorkspaces.length} workspace(s) with auto-invoicing enabled`);

    let totalInvoicesGenerated = 0;
    let successCount = 0;
    let errorCount = 0;

    const today = new Date();
    const dayOfMonth = today.getDate();
    const dayOfWeek = today.getDay(); // 0 = Sunday, 1 = Monday
    const lastDayOfMonth = new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate();
    
    for (const workspace of activeWorkspaces) {
      try {
        const schedule = workspace.invoiceSchedule || 'monthly';
        
        console.log(`\n📊 Checking workspace: ${workspace.name} (${workspace.id})`);
        console.log(`   Schedule: ${schedule}`);
        
        // Check if today matches the workspace's invoice schedule
        let shouldGenerateInvoices = false;
        
        if (schedule === 'weekly') {
          const dayOfWeekSetting = workspace.invoiceDayOfWeek ?? 1; // Default Monday
          shouldGenerateInvoices = dayOfWeek === dayOfWeekSetting;
          console.log(`   Day of Week: ${dayOfWeekSetting} (today: ${dayOfWeek})`);
        } else if (schedule === 'biweekly') {
          const dayOfWeekSetting = workspace.invoiceDayOfWeek ?? 1; // Default Monday
          
          // Seed anchor if not set (transactional)
          if (!workspace.invoiceBiweeklyAnchor) {
            console.log(`   🌱 Seeding biweekly anchor for first run...`);
            const anchor = seedAnchor(dayOfWeekSetting, today);
            await db.transaction(async (tx) => {
              await tx.update(workspaces)
                .set({ invoiceBiweeklyAnchor: anchor })
                .where(eq(workspaces.id, workspace.id));
            });
            workspace.invoiceBiweeklyAnchor = anchor;
          }
          
          // Check anchor drift
          detectAnchorDrift(workspace.invoiceBiweeklyAnchor, today);
          
          // Use anchor-based calculation
          shouldGenerateInvoices = shouldRunBiweekly(workspace.invoiceBiweeklyAnchor, dayOfWeekSetting, today);
        } else if (schedule === 'semi-monthly') {
          // 15th and last day of month
          shouldGenerateInvoices = dayOfMonth === 15 || dayOfMonth === lastDayOfMonth;
          console.log(`   Pay Dates: 15th and last day (today: ${dayOfMonth})`);
        } else if (schedule === 'monthly') {
          const dayOfMonthSetting = workspace.invoiceDayOfMonth ?? 1;
          shouldGenerateInvoices = dayOfMonth === dayOfMonthSetting;
          console.log(`   Day of Month: ${dayOfMonthSetting} (today: ${dayOfMonth})`);
        } else if (schedule === 'net30') {
          const dayOfMonthSetting = workspace.invoiceDayOfMonth ?? 1;
          shouldGenerateInvoices = dayOfMonth === dayOfMonthSetting;
          console.log(`   Day of Month: ${dayOfMonthSetting} (today: ${dayOfMonth})`);
        } else if (schedule === 'custom' && workspace.invoiceCustomDays) {
          // TODO: Implement custom interval tracking (needs lastRunDate in DB)
          console.log(`   ℹ️  Custom schedule not yet implemented (${workspace.invoiceCustomDays} days)`);
          shouldGenerateInvoices = false;
        }
        
        if (shouldGenerateInvoices) {
          console.log(`   ✓ Schedule matched, generating invoices...`);
          
          // Wrap automation in audit logging lifecycle
          const runId = `billos-${workspace.id}-${Date.now()}`;
          
          await logAutomationLifecycle(
            {
              jobType: 'invoicing',
              workspaceId: workspace.id,
              workspaceName: workspace.name,
              runId,
            },
            async () => {
              // Generate invoices for yesterday's approved time entries
              const invoices = await generateUsageBasedInvoices(workspace.id);
              
              if (invoices.length > 0) {
                console.log(`✅ Generated ${invoices.length} invoice(s) for ${workspace.name}`);
                totalInvoicesGenerated += invoices.length;
                successCount++;
              } else {
                console.log(`ℹ️  No unbilled time entries for ${workspace.name}`);
              }
              
              // Update lastRunAt and advance anchor (transactional) - ALWAYS run to maintain cadence
              await db.transaction(async (tx) => {
                const updateData: any = { lastInvoiceRunAt: today };
                
                // Advance biweekly anchor if applicable
                if (schedule === 'biweekly' && workspace.invoiceBiweeklyAnchor) {
                  const newAnchor = advanceAnchor(workspace.invoiceBiweeklyAnchor);
                  updateData.invoiceBiweeklyAnchor = newAnchor;
                }
                
                await tx.update(workspaces)
                  .set(updateData)
                  .where(eq(workspaces.id, workspace.id));
              });
              
              return { invoicesGenerated: invoices.length };
            }
          );
        } else {
          console.log(`   ℹ️  Not an invoice generation date for this schedule, skipping`);
        }
      } catch (error) {
        console.error(`❌ Failed to generate invoices for ${workspace.name}:`, error);
        errorCount++;
      }
    }

    console.log('\n=================================================');
    console.log('📈 BILLΟΣ™ AUTONOMOUS INVOICING - SUMMARY');
    console.log(`Total Workspaces: ${activeWorkspaces.length}`);
    console.log(`Successful: ${successCount}`);
    console.log(`Errors: ${errorCount}`);
    console.log(`Total Invoices Generated: ${totalInvoicesGenerated}`);
    console.log('=================================================\n');

  } catch (error) {
    console.error('💥 Critical error in nightly invoice generation:', error);
  }
}

/**
 * Weekly Schedule Generation
 * Runs Sunday nights to create schedules for upcoming week
 */
async function runWeeklyScheduleGeneration() {
  console.log('=================================================');
  console.log('🤖 SCHEDULEΟΣ™ AUTONOMOUS SCHEDULING - START');
  console.log(`Timestamp: ${new Date().toISOString()}`);
  console.log('=================================================');

  try {
    // Get all active workspaces with auto-scheduling enabled
    const activeWorkspaces = await db
      .select()
      .from(workspaces)
      .where(
        and(
          eq(workspaces.isSuspended, false),
          eq(workspaces.isFrozen, false),
          eq(workspaces.isLocked, false),
          eq(workspaces.autoSchedulingEnabled, true)
        )
      );

    console.log(`Found ${activeWorkspaces.length} workspace(s) with auto-scheduling enabled`);

    const today = new Date();
    const dayOfMonth = today.getDate();
    const dayOfWeek = today.getDay(); // 0 = Sunday, 1 = Monday
    
    // Calculate next week's date range
    const nextWeekStart = startOfWeek(addDays(new Date(), 7)); // Next Monday
    const nextWeekEnd = endOfWeek(nextWeekStart); // Following Sunday

    console.log(`\n📅 Target schedule period:`);
    console.log(`   Start: ${format(nextWeekStart, 'MMM dd, yyyy')}`);
    console.log(`   End:   ${format(nextWeekEnd, 'MMM dd, yyyy')}\n`);

    let successCount = 0;
    let errorCount = 0;

    for (const workspace of activeWorkspaces) {
      try {
        const interval = workspace.scheduleGenerationInterval || 'weekly';
        const advanceNoticeDays = workspace.scheduleAdvanceNoticeDays || 7;
        
        console.log(`\n📊 Checking workspace: ${workspace.name} (${workspace.id})`);
        console.log(`   Schedule Interval: ${interval}`);
        console.log(`   Advance Notice: ${advanceNoticeDays} days`);
        
        // Check if today matches the workspace's schedule generation interval
        let shouldGenerateSchedule = false;
        
        if (interval === 'weekly') {
          const dayOfWeekSetting = workspace.scheduleDayOfWeek ?? 0; // Default Sunday
          shouldGenerateSchedule = dayOfWeek === dayOfWeekSetting;
          console.log(`   Day of Week: ${dayOfWeekSetting} (today: ${dayOfWeek})`);
        } else if (interval === 'biweekly') {
          const dayOfWeekSetting = workspace.scheduleDayOfWeek ?? 0; // Default Sunday
          
          // Seed anchor if not set (transactional)
          if (!workspace.scheduleBiweeklyAnchor) {
            console.log(`   🌱 Seeding biweekly anchor for first run...`);
            const anchor = seedAnchor(dayOfWeekSetting, today);
            await db.transaction(async (tx) => {
              await tx.update(workspaces)
                .set({ scheduleBiweeklyAnchor: anchor })
                .where(eq(workspaces.id, workspace.id));
            });
            workspace.scheduleBiweeklyAnchor = anchor;
          }
          
          // Check anchor drift
          detectAnchorDrift(workspace.scheduleBiweeklyAnchor, today);
          
          // Use anchor-based calculation
          shouldGenerateSchedule = shouldRunBiweekly(workspace.scheduleBiweeklyAnchor, dayOfWeekSetting, today);
        } else if (interval === 'monthly') {
          const dayOfMonthSetting = workspace.scheduleDayOfMonth ?? 25; // Default 25th
          shouldGenerateSchedule = dayOfMonth === dayOfMonthSetting;
          console.log(`   Day of Month: ${dayOfMonthSetting} (today: ${dayOfMonth})`);
        } else if (interval === 'custom' && workspace.scheduleCustomDays) {
          // TODO: Implement custom interval tracking (needs lastRunDate in DB)
          console.log(`   ℹ️  Custom schedule not yet implemented (${workspace.scheduleCustomDays} days)`);
          shouldGenerateSchedule = false;
        }
        
        if (shouldGenerateSchedule) {
          console.log(`   ✓ Schedule interval matched, generating schedules...`);
          
          // Wrap automation in audit logging lifecycle
          const runId = `scheduleos-${workspace.id}-${Date.now()}`;
          
          await logAutomationLifecycle(
            {
              jobType: 'scheduling',
              workspaceId: workspace.id,
              workspaceName: workspace.name,
              runId,
            },
            async () => {
              // TODO: Get shift requirements from workspace configuration
              // For now, skip auto-scheduling until shift requirements are configured
              console.log(`   ℹ️  Shift templates not yet configured for ${workspace.name}`);
              console.log(`   (Requires shift requirement templates in workspace settings)`);
              
              // Update lastRunAt and advance anchor (transactional)
              await db.transaction(async (tx) => {
                const updateData: any = { lastScheduleRunAt: today };
                
                // Advance biweekly anchor if applicable
                if (interval === 'biweekly' && workspace.scheduleBiweeklyAnchor) {
                  const newAnchor = advanceAnchor(workspace.scheduleBiweeklyAnchor);
                  updateData.scheduleBiweeklyAnchor = newAnchor;
                }
                
                await tx.update(workspaces)
                  .set(updateData)
                  .where(eq(workspaces.id, workspace.id));
              });
              
              return { shiftsGenerated: 0 }; // Will be non-zero when shift templates are configured
            }
          );
          
          // Example of how it would work:
          /*
          const scheduleOSAI = new ScheduleOSAI();
          const result = await scheduleOSAI.generateSchedule({
            workspaceId: workspace.id,
            weekStartDate: nextWeekStart,
            shiftRequirements: workspace.shiftTemplates // Would come from settings
          });
          
          if (result.success) {
            console.log(`✅ Generated ${result.shiftsGenerated} shifts for ${workspace.name}`);
            successCount++;
          }
          */
        } else {
          console.log(`   ℹ️  Not a schedule generation date for this interval, skipping`);
        }
        
      } catch (error) {
        console.error(`❌ Failed to generate schedule for ${workspace.name}:`, error);
        errorCount++;
      }
    }

    console.log('\n=================================================');
    console.log('📈 SCHEDULEΟΣ™ AUTONOMOUS SCHEDULING - SUMMARY');
    console.log(`Total Workspaces: ${activeWorkspaces.length}`);
    console.log(`Successful: ${successCount}`);
    console.log(`Errors: ${errorCount}`);
    console.log('=================================================\n');

  } catch (error) {
    console.error('💥 Critical error in weekly schedule generation:', error);
  }
}

/**
 * Automatic Payroll Processing
 * Runs on configured pay period dates
 */
async function runAutomaticPayrollProcessing() {
  console.log('=================================================');
  console.log('🤖 PAYROLLOS™ AUTONOMOUS PAYROLL - START');
  console.log(`Timestamp: ${new Date().toISOString()}`);
  console.log('=================================================');

  try {
    // Get all active workspaces with auto-payroll enabled
    const activeWorkspaces = await db
      .select()
      .from(workspaces)
      .where(
        and(
          eq(workspaces.isSuspended, false),
          eq(workspaces.isFrozen, false),
          eq(workspaces.isLocked, false),
          eq(workspaces.autoPayrollEnabled, true)
        )
      );

    console.log(`Found ${activeWorkspaces.length} workspace(s) with auto-payroll enabled`);

    const today = new Date();
    const dayOfMonth = today.getDate();
    const dayOfWeek = today.getDay(); // 0 = Sunday, 1 = Monday

    let totalPayrollRuns = 0;
    let successCount = 0;
    let errorCount = 0;

    for (const workspace of activeWorkspaces) {
      try {
        // Get payroll schedule from workspace settings
        const paySchedule = workspace.payrollSchedule || 'biweekly';
        const cutoffDay = workspace.payrollCutoffDay ?? 15;
        let shouldProcessPayroll = false;

        console.log(`\n📊 Checking workspace: ${workspace.name} (${workspace.id})`);
        console.log(`   Payroll Schedule: ${paySchedule}`);

        // Check if today is a pay period date based on schedule
        if (paySchedule === 'weekly') {
          const dayOfWeekSetting = workspace.payrollDayOfWeek ?? 1; // Default Monday
          shouldProcessPayroll = dayOfWeek === dayOfWeekSetting;
          console.log(`   Day of Week: ${dayOfWeekSetting} (today: ${dayOfWeek})`);
        } else if (paySchedule === 'biweekly') {
          const dayOfWeekSetting = workspace.payrollDayOfWeek ?? 1; // Default Monday
          
          // Seed anchor if not set (transactional)
          if (!workspace.payrollBiweeklyAnchor) {
            console.log(`   🌱 Seeding biweekly anchor for first run...`);
            const anchor = seedAnchor(dayOfWeekSetting, today);
            await db.transaction(async (tx) => {
              await tx.update(workspaces)
                .set({ payrollBiweeklyAnchor: anchor })
                .where(eq(workspaces.id, workspace.id));
            });
            workspace.payrollBiweeklyAnchor = anchor;
          }
          
          // Check anchor drift
          detectAnchorDrift(workspace.payrollBiweeklyAnchor, today);
          
          // Use anchor-based calculation
          shouldProcessPayroll = shouldRunBiweekly(workspace.payrollBiweeklyAnchor, dayOfWeekSetting, today);
        } else if (paySchedule === 'semi-monthly') {
          const processDay = workspace.payrollDayOfMonth ?? 1;
          shouldProcessPayroll = dayOfMonth === processDay || dayOfMonth === cutoffDay;
          console.log(`   Pay Dates: ${processDay} and ${cutoffDay} (today: ${dayOfMonth})`);
        } else if (paySchedule === 'monthly') {
          const dayOfMonthSetting = workspace.payrollDayOfMonth ?? 1;
          shouldProcessPayroll = dayOfMonth === dayOfMonthSetting;
          console.log(`   Day of Month: ${dayOfMonthSetting} (today: ${dayOfMonth})`);
        } else if (paySchedule === 'custom' && workspace.payrollCustomDays) {
          // TODO: Implement custom interval logic (needs lastRunDate in DB)
          console.log(`   ℹ️  Custom schedule not yet implemented (${workspace.payrollCustomDays} days)`);
          shouldProcessPayroll = false;
        }

        if (shouldProcessPayroll) {
          console.log(`   ✓ Pay period date matched, processing payroll...`);
          
          // Wrap automation in audit logging lifecycle
          const runId = `payrollos-${workspace.id}-${Date.now()}`;
          
          await logAutomationLifecycle(
            {
              jobType: 'payroll',
              workspaceId: workspace.id,
              workspaceName: workspace.name,
              runId,
            },
            async () => {
              // Get workspace owner to attribute payroll run
              const [owner] = await db
                .select()
                .from(employees)
                .where(
                  and(
                    eq(employees.workspaceId, workspace.id),
                    eq(employees.workspaceRole, 'org_owner')
                  )
                )
                .limit(1);

              if (owner && owner.userId) {
                // Process automated payroll
                const result = await PayrollAutomationEngine.processAutomatedPayroll(
                  workspace.id,
                  owner.userId
                );

                console.log(`✅ Payroll processed for ${workspace.name}:`);
                console.log(`   Employees: ${result.totalEmployees}`);
                console.log(`   Gross Pay: $${result.totalGrossPay.toFixed(2)}`);
                console.log(`   Net Pay: $${result.totalNetPay.toFixed(2)}`);
                
                totalPayrollRuns++;
                successCount++;
                
                // Update lastRunAt and advance anchor (transactional) - ALWAYS run to maintain cadence
                await db.transaction(async (tx) => {
                  const updateData: any = { lastPayrollRunAt: today };
                  
                  // Advance biweekly anchor if applicable
                  if (paySchedule === 'biweekly' && workspace.payrollBiweeklyAnchor) {
                    const newAnchor = advanceAnchor(workspace.payrollBiweeklyAnchor);
                    updateData.payrollBiweeklyAnchor = newAnchor;
                  }
                  
                  await tx.update(workspaces)
                    .set(updateData)
                    .where(eq(workspaces.id, workspace.id));
                });
                
                return {
                  employeesProcessed: result.totalEmployees,
                  grossPay: result.totalGrossPay,
                  netPay: result.totalNetPay
                };
              } else {
                console.log(`⚠️  No owner found for ${workspace.name}, skipping payroll`);
                return { employeesProcessed: 0, grossPay: 0, netPay: 0 };
              }
            }
          );
        } else {
          console.log(`   ℹ️  Not a pay period date, skipping`);
        }

      } catch (error) {
        console.error(`❌ Failed to process payroll for ${workspace.name}:`, error);
        errorCount++;
      }
    }

    console.log('\n=================================================');
    console.log('📈 PAYROLLOS™ AUTONOMOUS PAYROLL - SUMMARY');
    console.log(`Total Workspaces Checked: ${activeWorkspaces.length}`);
    console.log(`Payroll Runs Processed: ${totalPayrollRuns}`);
    console.log(`Successful: ${successCount}`);
    console.log(`Errors: ${errorCount}`);
    console.log('=================================================\n');

  } catch (error) {
    console.error('💥 Critical error in automatic payroll processing:', error);
  }
}

// ============================================================================
// SCHEDULER INITIALIZATION
// ============================================================================

let isSchedulerRunning = false;

/**
 * Start all autonomous job schedulers
 */
export function startAutonomousScheduler() {
  if (isSchedulerRunning) {
    console.log('⚠️  Autonomous scheduler is already running');
    return;
  }

  console.log('\n╔════════════════════════════════════════════════╗');
  console.log('║  🤖 AUTOFORCE™ AUTONOMOUS SCHEDULER STARTING  ║');
  console.log('╚════════════════════════════════════════════════╝\n');

  // 1. Nightly Invoice Generation (2 AM daily)
  if (SCHEDULER_CONFIG.invoicing.enabled) {
    cron.schedule(SCHEDULER_CONFIG.invoicing.schedule, () => {
      runNightlyInvoiceGeneration();
    });
    console.log('✅ BillOS™ Invoicing Automation:');
    console.log(`   Schedule: ${SCHEDULER_CONFIG.invoicing.schedule} (daily 2 AM)`);
    console.log(`   ${SCHEDULER_CONFIG.invoicing.description}\n`);
  }

  // 2. Schedule Generation (11 PM daily)
  if (SCHEDULER_CONFIG.scheduling.enabled) {
    cron.schedule(SCHEDULER_CONFIG.scheduling.schedule, () => {
      runWeeklyScheduleGeneration();
    });
    console.log('✅ ScheduleOS™ Schedule Automation:');
    console.log(`   Schedule: ${SCHEDULER_CONFIG.scheduling.schedule} (daily 11 PM)`);
    console.log(`   ${SCHEDULER_CONFIG.scheduling.description}\n`);
  }

  // 3. Automatic Payroll Processing (3 AM daily)
  if (SCHEDULER_CONFIG.payroll.enabled) {
    cron.schedule(SCHEDULER_CONFIG.payroll.schedule, () => {
      runAutomaticPayrollProcessing();
    });
    console.log('✅ PayrollOS™ Payroll Automation:');
    console.log(`   Schedule: ${SCHEDULER_CONFIG.payroll.schedule} (daily 3 AM)`);
    console.log(`   ${SCHEDULER_CONFIG.payroll.description}\n`);
  }

  isSchedulerRunning = true;

  console.log('╔════════════════════════════════════════════════╗');
  console.log('║  ✅ AUTONOMOUS SCHEDULER RUNNING SUCCESSFULLY  ║');
  console.log('╚════════════════════════════════════════════════╝\n');
}

/**
 * Manually trigger jobs for testing
 */
export const manualTriggers = {
  invoicing: runNightlyInvoiceGeneration,
  scheduling: runWeeklyScheduleGeneration,
  payroll: runAutomaticPayrollProcessing,
};
