/**
 * Autonomous Scheduler Service
 * Runs scheduled jobs for AutoForce™ autonomous operations:
 * - Nightly invoice generation (BillOS™)
 * - Weekly schedule generation (OperationsOS™)
 * - Automatic payroll processing (BillOS™)
 * 
 * All automation activities are logged to AuditOS™ for compliance tracking.
 */

import cron from 'node-cron';
import { db } from '../db';
import { workspaces, employees, idempotencyKeys, chatConversations, roomEvents } from '@shared/schema';
import { eq, and, sql, lt } from 'drizzle-orm';
import { generateUsageBasedInvoices } from './billos';
import { PayrollAutomationEngine } from './payrollAutomation';
import { ScheduleOSAI } from '../ai/scheduleos';
import { addDays, startOfWeek, endOfWeek, format } from 'date-fns';
import { shouldRunBiweekly, seedAnchor, advanceAnchor, detectAnchorDrift } from './utils/scheduling';
import { storage } from '../storage';
import { executeIdempotencyCheck, updateIdempotencyResult } from './autonomy/helpers';
import { runWebSocketConnectionCleanup } from './wsConnectionCleanup';
import crypto from 'crypto';

// ============================================================================
// IDEMPOTENCY FINGERPRINTING
// ============================================================================

/**
 * Build idempotency fingerprint for invoice generation
 * Includes: workspace, period boundaries (start/end dates), schedule config hash
 */
function buildInvoiceFingerprintData(workspace: any, date: Date) {
  // Calculate billing period boundaries (yesterday's work)
  const periodEnd = new Date(date);
  periodEnd.setHours(0, 0, 0, 0);
  const periodStart = new Date(periodEnd);
  periodStart.setDate(periodStart.getDate() - 1);
  
  return {
    workspaceId: workspace.id,
    runDate: date.toISOString().split('T')[0], // YYYY-MM-DD
    periodStart: periodStart.toISOString().split('T')[0],
    periodEnd: periodEnd.toISOString().split('T')[0],
    schedule: workspace.invoiceSchedule,
    dayOfWeek: workspace.invoiceDayOfWeek,
    dayOfMonth: workspace.invoiceDayOfMonth,
    biweeklyAnchor: workspace.invoiceBiweeklyAnchor?.toISOString(),
    configHash: crypto
      .createHash('sha256')
      .update(JSON.stringify({
        schedule: workspace.invoiceSchedule,
        dayOfWeek: workspace.invoiceDayOfWeek,
        dayOfMonth: workspace.invoiceDayOfMonth,
      }))
      .digest('hex')
      .substring(0, 16),
  };
}

function buildPayrollFingerprintData(workspace: any, date: Date) {
  // Calculate payroll period boundaries  
  const periodEnd = new Date(date);
  periodEnd.setHours(0, 0, 0, 0);
  const periodStart = new Date(periodEnd);
  periodStart.setDate(periodStart.getDate() - 1);
  
  return {
    workspaceId: workspace.id,
    runDate: date.toISOString().split('T')[0], // YYYY-MM-DD
    periodStart: periodStart.toISOString().split('T')[0],
    periodEnd: periodEnd.toISOString().split('T')[0],
    schedule: workspace.payrollSchedule,
    dayOfWeek: workspace.payrollDayOfWeek,
    dayOfMonth: workspace.payrollDayOfMonth,
    cutoffDay: workspace.payrollCutoffDay,
    biweeklyAnchor: workspace.payrollBiweeklyAnchor?.toISOString(),
    configHash: crypto
      .createHash('sha256')
      .update(JSON.stringify({
        schedule: workspace.payrollSchedule,
        dayOfWeek: workspace.payrollDayOfWeek,
        dayOfMonth: workspace.payrollDayOfMonth,
        cutoffDay: workspace.payrollCutoffDay,
      }))
      .digest('hex')
      .substring(0, 16),
  };
}

/**
 * Build idempotency fingerprint for schedule generation
 * Includes: workspace, period boundaries (next week), schedule config hash
 */
function buildScheduleFingerprintData(workspace: any, date: Date, nextWeekStart: Date, nextWeekEnd: Date) {
  return {
    workspaceId: workspace.id,
    runDate: date.toISOString().split('T')[0], // YYYY-MM-DD
    periodStart: nextWeekStart.toISOString().split('T')[0],
    periodEnd: nextWeekEnd.toISOString().split('T')[0],
    interval: workspace.scheduleGenerationInterval,
    dayOfWeek: workspace.scheduleDayOfWeek,
    dayOfMonth: workspace.scheduleDayOfMonth,
    advanceNoticeDays: workspace.scheduleAdvanceNoticeDays,
    biweeklyAnchor: workspace.scheduleBiweeklyAnchor?.toISOString(),
    configHash: crypto
      .createHash('sha256')
      .update(JSON.stringify({
        interval: workspace.scheduleGenerationInterval,
        dayOfWeek: workspace.scheduleDayOfWeek,
        dayOfMonth: workspace.scheduleDayOfMonth,
        advanceNoticeDays: workspace.scheduleAdvanceNoticeDays,
      }))
      .digest('hex')
      .substring(0, 16),
  };
}

// ============================================================================
// AUTOMATION AUDIT LOGGING
// ============================================================================

/**
 * System user context for automation jobs
 * Used for all AuditOS audit logs generated by autonomous processes
 */
const AUTOFORCE_AUTOMATION_USER = {
  userId: 'system-autoforce',
  userName: 'AutoForce™ Automation',
  userEmail: 'automation@autoforce.ai',
  userRole: 'system' as const,
};

/**
 * Log automation job lifecycle (start, complete, error) to AuditOS
 * 
 * Ensures all automation activities are auditable and never fails the main job
 * if audit logging encounters errors.
 */
async function logAutomationLifecycle<T>(
  params: {
    jobType: 'invoicing' | 'scheduling' | 'payroll' | 'idempotency_cleanup' | 'room_auto_close';
    workspaceId: string;
    workspaceName: string;
    runId: string;
  },
  runner: () => Promise<T>
): Promise<T> {
  const { jobType, workspaceId, workspaceName, runId } = params;
  const startTime = Date.now();

  // Map job types to consolidated OS names
  const osNameMap = {
    invoicing: 'BillOS™',
    scheduling: 'OperationsOS™',
    payroll: 'BillOS™',
    idempotency_cleanup: 'AuditOS™',
    room_auto_close: 'CommOS™',
  };
  const osName = osNameMap[jobType];

  // Log job start (don't fail if audit logging fails)
  try {
    await storage.createAuditLog({
      workspaceId,
      ...AUTOFORCE_AUTOMATION_USER,
      action: 'automation_job_start',
      actionDescription: `${osName} automation started for ${workspaceName}`,
      entityType: 'automation_job',
      entityId: runId,
      metadata: {
        jobType,
        osName,
        timestamp: new Date().toISOString(),
      },
    });
  } catch (error) {
    console.error(`[AUDIT WARNING] Failed to log automation start for ${workspaceName}:`, error);
  }

  try {
    // Execute the actual job
    const result = await runner();
    const duration = Date.now() - startTime;

    // Log job completion
    try {
      await storage.createAuditLog({
        workspaceId,
        ...AUTOFORCE_AUTOMATION_USER,
        action: 'automation_job_complete',
        actionDescription: `${osName} automation completed for ${workspaceName}`,
        entityType: 'automation_job',
        entityId: runId,
        metadata: {
          jobType,
          osName,
          duration,
          timestamp: new Date().toISOString(),
          result: typeof result === 'object' ? result : { value: result },
        },
      });
    } catch (error) {
      console.error(`[AUDIT WARNING] Failed to log automation completion for ${workspaceName}:`, error);
    }

    return result;
  } catch (error: any) {
    const duration = Date.now() - startTime;

    // Log job error
    try {
      await storage.createAuditLog({
        workspaceId,
        ...AUTOFORCE_AUTOMATION_USER,
        action: 'automation_job_error',
        actionDescription: `${osName} automation failed for ${workspaceName}: ${error.message}`,
        entityType: 'automation_job',
        entityId: runId,
        metadata: {
          jobType,
          osName,
          duration,
          error: error.message,
          stack: error.stack?.substring(0, 500), // Truncate stack trace
          timestamp: new Date().toISOString(),
        },
      });
    } catch (auditError) {
      console.error(`[AUDIT WARNING] Failed to log automation error for ${workspaceName}:`, auditError);
    }

    throw error; // Re-throw to maintain original error handling
  }
}

// ============================================================================
// CONFIGURATION
// ============================================================================

const SCHEDULER_CONFIG = {
  invoicing: {
    enabled: true,
    schedule: '0 2 * * *', // Every day at 2 AM
    description: 'Daily check for invoice generation based on workspace schedules'
  },
  scheduling: {
    enabled: true,
    schedule: '0 23 * * *', // Every day at 11 PM
    description: 'Daily check for schedule generation based on workspace intervals'
  },
  payroll: {
    enabled: true,
    schedule: '0 3 * * *', // Every day at 3 AM (after invoicing)
    description: 'Daily check for payroll processing based on workspace pay periods'
  },
  cleanup: {
    enabled: true,
    schedule: '0 4 * * *', // Every day at 4 AM (after all automation jobs)
    description: 'Daily cleanup of expired idempotency keys based on TTL'
  },
  roomAutoClose: {
    enabled: true,
    schedule: '*/5 * * * *', // Every 5 minutes
    description: 'Auto-close expired shift rooms based on autoCloseAt timestamp'
  },
  wsConnectionCleanup: {
    enabled: true,
    schedule: '*/5 * * * *', // Every 5 minutes
    description: 'Auto-close orphaned WebSocket connections (>5min) and purge stale records (>24h)'
  }
};

// ============================================================================
// JOB HANDLERS
// ============================================================================

/**
 * Nightly Invoice Generation
 * Runs for all workspaces with auto-invoicing enabled
 */
async function runNightlyInvoiceGeneration() {
  console.log('=================================================');
  console.log('🤖 BILLΟΣ™ AUTONOMOUS INVOICING - START');
  console.log(`Timestamp: ${new Date().toISOString()}`);
  console.log('=================================================');

  try {
    // Get all active workspaces with auto-invoicing enabled
    const activeWorkspaces = await db
      .select()
      .from(workspaces)
      .where(
        and(
          eq(workspaces.isSuspended, false),
          eq(workspaces.isFrozen, false),
          eq(workspaces.isLocked, false),
          eq(workspaces.autoInvoicingEnabled, true)
        )
      );

    console.log(`Found ${activeWorkspaces.length} workspace(s) with auto-invoicing enabled`);

    let totalInvoicesGenerated = 0;
    let successCount = 0;
    let errorCount = 0;

    const today = new Date();
    const dayOfMonth = today.getDate();
    const dayOfWeek = today.getDay(); // 0 = Sunday, 1 = Monday
    const lastDayOfMonth = new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate();
    
    for (const workspace of activeWorkspaces) {
      try {
        const schedule = workspace.invoiceSchedule || 'monthly';
        
        console.log(`\n📊 Checking workspace: ${workspace.name} (${workspace.id})`);
        console.log(`   Schedule: ${schedule}`);
        
        // Check if today matches the workspace's invoice schedule
        let shouldGenerateInvoices = false;
        
        if (schedule === 'weekly') {
          const dayOfWeekSetting = workspace.invoiceDayOfWeek ?? 1; // Default Monday
          shouldGenerateInvoices = dayOfWeek === dayOfWeekSetting;
          console.log(`   Day of Week: ${dayOfWeekSetting} (today: ${dayOfWeek})`);
        } else if (schedule === 'biweekly') {
          const dayOfWeekSetting = workspace.invoiceDayOfWeek ?? 1; // Default Monday
          
          // Seed anchor if not set (transactional)
          if (!workspace.invoiceBiweeklyAnchor) {
            console.log(`   🌱 Seeding biweekly anchor for first run...`);
            const anchor = seedAnchor(dayOfWeekSetting, today);
            await db.transaction(async (tx) => {
              await tx.update(workspaces)
                .set({ invoiceBiweeklyAnchor: anchor })
                .where(eq(workspaces.id, workspace.id));
            });
            workspace.invoiceBiweeklyAnchor = anchor;
          }
          
          // Check anchor drift
          detectAnchorDrift(workspace.invoiceBiweeklyAnchor, today);
          
          // Use anchor-based calculation
          shouldGenerateInvoices = shouldRunBiweekly(workspace.invoiceBiweeklyAnchor, dayOfWeekSetting, today);
        } else if (schedule === 'semi-monthly') {
          // 15th and last day of month
          shouldGenerateInvoices = dayOfMonth === 15 || dayOfMonth === lastDayOfMonth;
          console.log(`   Pay Dates: 15th and last day (today: ${dayOfMonth})`);
        } else if (schedule === 'monthly') {
          const dayOfMonthSetting = workspace.invoiceDayOfMonth ?? 1;
          shouldGenerateInvoices = dayOfMonth === dayOfMonthSetting;
          console.log(`   Day of Month: ${dayOfMonthSetting} (today: ${dayOfMonth})`);
        } else if (schedule === 'net30') {
          const dayOfMonthSetting = workspace.invoiceDayOfMonth ?? 1;
          shouldGenerateInvoices = dayOfMonth === dayOfMonthSetting;
          console.log(`   Day of Month: ${dayOfMonthSetting} (today: ${dayOfMonth})`);
        } else if (schedule === 'custom' && workspace.invoiceCustomDays) {
          // TODO: Implement custom interval tracking (needs lastRunDate in DB)
          console.log(`   ℹ️  Custom schedule not yet implemented (${workspace.invoiceCustomDays} days)`);
          shouldGenerateInvoices = false;
        }
        
        if (shouldGenerateInvoices) {
          console.log(`   ✓ Schedule matched, checking idempotency...`);
          
          // Wrap automation in audit logging lifecycle
          const runId = `billos-${workspace.id}-${Date.now()}`;
          
          await logAutomationLifecycle(
            {
              jobType: 'invoicing',
              workspaceId: workspace.id,
              workspaceName: workspace.name,
              runId,
            },
            async () => {
              // IDEMPOTENCY: Check if this operation already ran today (14-day TTL for retry window)
              const idem = await executeIdempotencyCheck({
                workspaceId: workspace.id,
                operationType: 'invoice_generation',
                requestData: buildInvoiceFingerprintData(workspace, today),
                ttlDays: 14,
              });
              
              if (!idem.isNew) {
                console.log(`   ⚠️  Duplicate invoice generation detected (idempotency key ${idem.idempotencyKeyId})`);
                console.log(`   Existing status: ${idem.status}, skipping execution`);
                return { 
                  invoicesGenerated: 0, 
                  isDuplicate: true,
                  idempotencyKeyId: idem.idempotencyKeyId,
                };
              }
              
              console.log(`   ✓ New operation confirmed (key ${idem.idempotencyKeyId}), generating invoices...`);
              
              try {
                // Generate invoices for yesterday's approved time entries
                const invoices = await generateUsageBasedInvoices(workspace.id);
                
                if (invoices.length > 0) {
                  console.log(`✅ Generated ${invoices.length} invoice(s) for ${workspace.name}`);
                  totalInvoicesGenerated += invoices.length;
                  successCount++;
                } else {
                  console.log(`ℹ️  No unbilled time entries for ${workspace.name}`);
                }
                
                // Update lastRunAt, advance anchor, and mark idempotency complete (ATOMIC)
                await db.transaction(async (tx) => {
                  const updateData: any = { lastInvoiceRunAt: today };
                  
                  // Advance biweekly anchor if applicable (maintains 14-day cadence)
                  if (schedule === 'biweekly' && workspace.invoiceBiweeklyAnchor) {
                    const newAnchor = advanceAnchor(workspace.invoiceBiweeklyAnchor);
                    updateData.invoiceBiweeklyAnchor = newAnchor;
                  }
                  
                  await tx.update(workspaces)
                    .set(updateData)
                    .where(eq(workspaces.id, workspace.id));
                  
                  // Mark idempotency complete in SAME transaction using transaction-aware helper
                  await updateIdempotencyResult({
                    idempotencyKeyId: idem.idempotencyKeyId,
                    status: 'completed',
                    resultId: invoices.length > 0 ? String(invoices[0].id) : undefined,
                    resultMetadata: {
                      invoicesGenerated: invoices.length,
                      isDuplicate: false,
                      workspaceName: workspace.name,
                      schedule,
                      periodStart: buildInvoiceFingerprintData(workspace, today).periodStart,
                      periodEnd: buildInvoiceFingerprintData(workspace, today).periodEnd,
                    },
                  }, tx); // Pass transaction client for atomic update
                });
                
                return { 
                  invoicesGenerated: invoices.length,
                  isDuplicate: false,
                  idempotencyKeyId: idem.idempotencyKeyId,
                };
              } catch (error: any) {
                // Mark idempotency operation failed with full error context
                await updateIdempotencyResult({
                  idempotencyKeyId: idem.idempotencyKeyId,
                  status: 'failed',
                  errorMessage: error.message,
                  errorStack: error.stack,
                  resultMetadata: {
                    isDuplicate: false,
                    workspaceName: workspace.name,
                    schedule,
                  },
                });
                throw error; // Re-throw to trigger audit log error
              }
            }
          );
        } else {
          console.log(`   ℹ️  Not an invoice generation date for this schedule, skipping`);
        }
      } catch (error) {
        console.error(`❌ Failed to generate invoices for ${workspace.name}:`, error);
        errorCount++;
      }
    }

    console.log('\n=================================================');
    console.log('📈 BILLΟΣ™ AUTONOMOUS INVOICING - SUMMARY');
    console.log(`Total Workspaces: ${activeWorkspaces.length}`);
    console.log(`Successful: ${successCount}`);
    console.log(`Errors: ${errorCount}`);
    console.log(`Total Invoices Generated: ${totalInvoicesGenerated}`);
    console.log('=================================================\n');

  } catch (error) {
    console.error('💥 Critical error in nightly invoice generation:', error);
  }
}

/**
 * Weekly Schedule Generation
 * Runs Sunday nights to create schedules for upcoming week
 */
async function runWeeklyScheduleGeneration() {
  console.log('=================================================');
  console.log('🤖 OPERATIONSOS™ AUTONOMOUS SCHEDULING - START');
  console.log(`Timestamp: ${new Date().toISOString()}`);
  console.log('=================================================');

  try {
    // Get all active workspaces with auto-scheduling enabled
    const activeWorkspaces = await db
      .select()
      .from(workspaces)
      .where(
        and(
          eq(workspaces.isSuspended, false),
          eq(workspaces.isFrozen, false),
          eq(workspaces.isLocked, false),
          eq(workspaces.autoSchedulingEnabled, true)
        )
      );

    console.log(`Found ${activeWorkspaces.length} workspace(s) with auto-scheduling enabled`);

    const today = new Date();
    const dayOfMonth = today.getDate();
    const dayOfWeek = today.getDay(); // 0 = Sunday, 1 = Monday
    
    // Calculate next week's date range
    const nextWeekStart = startOfWeek(addDays(new Date(), 7)); // Next Monday
    const nextWeekEnd = endOfWeek(nextWeekStart); // Following Sunday

    console.log(`\n📅 Target schedule period:`);
    console.log(`   Start: ${format(nextWeekStart, 'MMM dd, yyyy')}`);
    console.log(`   End:   ${format(nextWeekEnd, 'MMM dd, yyyy')}\n`);

    let successCount = 0;
    let errorCount = 0;

    for (const workspace of activeWorkspaces) {
      try {
        const interval = workspace.scheduleGenerationInterval || 'weekly';
        const advanceNoticeDays = workspace.scheduleAdvanceNoticeDays || 7;
        
        console.log(`\n📊 Checking workspace: ${workspace.name} (${workspace.id})`);
        console.log(`   Schedule Interval: ${interval}`);
        console.log(`   Advance Notice: ${advanceNoticeDays} days`);
        
        // Check if today matches the workspace's schedule generation interval
        let shouldGenerateSchedule = false;
        
        if (interval === 'weekly') {
          const dayOfWeekSetting = workspace.scheduleDayOfWeek ?? 0; // Default Sunday
          shouldGenerateSchedule = dayOfWeek === dayOfWeekSetting;
          console.log(`   Day of Week: ${dayOfWeekSetting} (today: ${dayOfWeek})`);
        } else if (interval === 'biweekly') {
          const dayOfWeekSetting = workspace.scheduleDayOfWeek ?? 0; // Default Sunday
          
          // Seed anchor if not set (transactional)
          if (!workspace.scheduleBiweeklyAnchor) {
            console.log(`   🌱 Seeding biweekly anchor for first run...`);
            const anchor = seedAnchor(dayOfWeekSetting, today);
            await db.transaction(async (tx) => {
              await tx.update(workspaces)
                .set({ scheduleBiweeklyAnchor: anchor })
                .where(eq(workspaces.id, workspace.id));
            });
            workspace.scheduleBiweeklyAnchor = anchor;
          }
          
          // Check anchor drift
          detectAnchorDrift(workspace.scheduleBiweeklyAnchor, today);
          
          // Use anchor-based calculation
          shouldGenerateSchedule = shouldRunBiweekly(workspace.scheduleBiweeklyAnchor, dayOfWeekSetting, today);
        } else if (interval === 'monthly') {
          const dayOfMonthSetting = workspace.scheduleDayOfMonth ?? 25; // Default 25th
          shouldGenerateSchedule = dayOfMonth === dayOfMonthSetting;
          console.log(`   Day of Month: ${dayOfMonthSetting} (today: ${dayOfMonth})`);
        } else if (interval === 'custom' && workspace.scheduleCustomDays) {
          // TODO: Implement custom interval tracking (needs lastRunDate in DB)
          console.log(`   ℹ️  Custom schedule not yet implemented (${workspace.scheduleCustomDays} days)`);
          shouldGenerateSchedule = false;
        }
        
        if (shouldGenerateSchedule) {
          console.log(`   ✓ Schedule interval matched, checking idempotency...`);
          
          // Wrap automation in audit logging lifecycle
          const runId = `operationsos-${workspace.id}-${Date.now()}`;
          
          await logAutomationLifecycle(
            {
              jobType: 'scheduling',
              workspaceId: workspace.id,
              workspaceName: workspace.name,
              runId,
            },
            async () => {
              // IDEMPOTENCY: Check if this operation already ran today (14-day TTL)
              const idem = await executeIdempotencyCheck({
                workspaceId: workspace.id,
                operationType: 'schedule_generation',
                requestData: buildScheduleFingerprintData(workspace, today, nextWeekStart, nextWeekEnd),
                ttlDays: 14,
              });
              
              if (!idem.isNew) {
                console.log(`   ⚠️  Duplicate schedule generation detected (idempotency key ${idem.idempotencyKeyId})`);
                console.log(`   Existing status: ${idem.status}, skipping execution`);
                return { 
                  shiftsGenerated: 0, 
                  isDuplicate: true,
                  idempotencyKeyId: idem.idempotencyKeyId,
                };
              }
              
              console.log(`   ✓ New operation confirmed (key ${idem.idempotencyKeyId}), generating schedules...`);
              
              try {
                // TODO: Get shift requirements from workspace configuration
                // For now, skip auto-scheduling until shift requirements are configured
                console.log(`   ℹ️  Shift templates not yet configured for ${workspace.name}`);
                console.log(`   (Requires shift requirement templates in workspace settings)`);
                
                const shiftsGenerated = 0; // Will be non-zero when shift templates are configured
                
                // Update lastRunAt, advance anchor, and mark idempotency complete (ATOMIC)
                await db.transaction(async (tx) => {
                  const updateData: any = { lastScheduleRunAt: today };
                  
                  // Advance biweekly anchor if applicable
                  if (interval === 'biweekly' && workspace.scheduleBiweeklyAnchor) {
                    const newAnchor = advanceAnchor(workspace.scheduleBiweeklyAnchor);
                    updateData.scheduleBiweeklyAnchor = newAnchor;
                  }
                  
                  await tx.update(workspaces)
                    .set(updateData)
                    .where(eq(workspaces.id, workspace.id));
                  
                  // Mark idempotency operation complete (with transaction)
                  await updateIdempotencyResult({
                    idempotencyKeyId: idem.idempotencyKeyId,
                    status: 'completed',
                    resultId: undefined, // No specific result ID for schedule generation yet
                    resultMetadata: {
                      shiftsGenerated,
                      periodStart: nextWeekStart.toISOString().split('T')[0],
                      periodEnd: nextWeekEnd.toISOString().split('T')[0],
                      interval,
                    },
                  }, tx);
                });
                
                if (shiftsGenerated > 0) {
                  console.log(`✅ Generated ${shiftsGenerated} shift(s) for ${workspace.name}`);
                  successCount++;
                } else {
                  console.log(`ℹ️  No shifts generated (templates not configured)`);
                }
                
                return { shiftsGenerated };
                
              } catch (error) {
                // Mark idempotency operation failed (no transaction on error path)
                await updateIdempotencyResult({
                  idempotencyKeyId: idem.idempotencyKeyId,
                  status: 'failed',
                  errorMessage: error instanceof Error ? error.message : String(error),
                  errorStack: error instanceof Error ? error.stack : undefined,
                });
                throw error; // Re-throw to trigger audit log error handling
              }
            }
          );
          
          // Example of how it would work:
          /*
          const scheduleOSAI = new ScheduleOSAI();
          const result = await scheduleOSAI.generateSchedule({
            workspaceId: workspace.id,
            weekStartDate: nextWeekStart,
            shiftRequirements: workspace.shiftTemplates // Would come from settings
          });
          
          if (result.success) {
            console.log(`✅ Generated ${result.shiftsGenerated} shifts for ${workspace.name}`);
            successCount++;
          }
          */
        } else {
          console.log(`   ℹ️  Not a schedule generation date for this interval, skipping`);
        }
        
      } catch (error) {
        console.error(`❌ Failed to generate schedule for ${workspace.name}:`, error);
        errorCount++;
      }
    }

    console.log('\n=================================================');
    console.log('📈 OPERATIONSOS™ AUTONOMOUS SCHEDULING - SUMMARY');
    console.log(`Total Workspaces: ${activeWorkspaces.length}`);
    console.log(`Successful: ${successCount}`);
    console.log(`Errors: ${errorCount}`);
    console.log('=================================================\n');

  } catch (error) {
    console.error('💥 Critical error in weekly schedule generation:', error);
  }
}

/**
 * Automatic Payroll Processing
 * Runs on configured pay period dates
 */
async function runAutomaticPayrollProcessing() {
  console.log('=================================================');
  console.log('🤖 PAYROLLOS™ AUTONOMOUS PAYROLL - START');
  console.log(`Timestamp: ${new Date().toISOString()}`);
  console.log('=================================================');

  try {
    // Get all active workspaces with auto-payroll enabled
    const activeWorkspaces = await db
      .select()
      .from(workspaces)
      .where(
        and(
          eq(workspaces.isSuspended, false),
          eq(workspaces.isFrozen, false),
          eq(workspaces.isLocked, false),
          eq(workspaces.autoPayrollEnabled, true)
        )
      );

    console.log(`Found ${activeWorkspaces.length} workspace(s) with auto-payroll enabled`);

    const today = new Date();
    const dayOfMonth = today.getDate();
    const dayOfWeek = today.getDay(); // 0 = Sunday, 1 = Monday

    let totalPayrollRuns = 0;
    let successCount = 0;
    let errorCount = 0;

    for (const workspace of activeWorkspaces) {
      try {
        // Get payroll schedule from workspace settings
        const paySchedule = workspace.payrollSchedule || 'biweekly';
        const cutoffDay = workspace.payrollCutoffDay ?? 15;
        let shouldProcessPayroll = false;

        console.log(`\n📊 Checking workspace: ${workspace.name} (${workspace.id})`);
        console.log(`   Payroll Schedule: ${paySchedule}`);

        // Check if today is a pay period date based on schedule
        if (paySchedule === 'weekly') {
          const dayOfWeekSetting = workspace.payrollDayOfWeek ?? 1; // Default Monday
          shouldProcessPayroll = dayOfWeek === dayOfWeekSetting;
          console.log(`   Day of Week: ${dayOfWeekSetting} (today: ${dayOfWeek})`);
        } else if (paySchedule === 'biweekly') {
          const dayOfWeekSetting = workspace.payrollDayOfWeek ?? 1; // Default Monday
          
          // Seed anchor if not set (transactional)
          if (!workspace.payrollBiweeklyAnchor) {
            console.log(`   🌱 Seeding biweekly anchor for first run...`);
            const anchor = seedAnchor(dayOfWeekSetting, today);
            await db.transaction(async (tx) => {
              await tx.update(workspaces)
                .set({ payrollBiweeklyAnchor: anchor })
                .where(eq(workspaces.id, workspace.id));
            });
            workspace.payrollBiweeklyAnchor = anchor;
          }
          
          // Check anchor drift
          detectAnchorDrift(workspace.payrollBiweeklyAnchor, today);
          
          // Use anchor-based calculation
          shouldProcessPayroll = shouldRunBiweekly(workspace.payrollBiweeklyAnchor, dayOfWeekSetting, today);
        } else if (paySchedule === 'semi-monthly') {
          const processDay = workspace.payrollDayOfMonth ?? 1;
          shouldProcessPayroll = dayOfMonth === processDay || dayOfMonth === cutoffDay;
          console.log(`   Pay Dates: ${processDay} and ${cutoffDay} (today: ${dayOfMonth})`);
        } else if (paySchedule === 'monthly') {
          const dayOfMonthSetting = workspace.payrollDayOfMonth ?? 1;
          shouldProcessPayroll = dayOfMonth === dayOfMonthSetting;
          console.log(`   Day of Month: ${dayOfMonthSetting} (today: ${dayOfMonth})`);
        } else if (paySchedule === 'custom' && workspace.payrollCustomDays) {
          // TODO: Implement custom interval logic (needs lastRunDate in DB)
          console.log(`   ℹ️  Custom schedule not yet implemented (${workspace.payrollCustomDays} days)`);
          shouldProcessPayroll = false;
        }

        if (shouldProcessPayroll) {
          console.log(`   ✓ Pay period date matched, processing payroll...`);
          
          // Wrap automation in audit logging lifecycle
          const runId = `payrollos-${workspace.id}-${Date.now()}`;
          
          await logAutomationLifecycle(
            {
              jobType: 'payroll',
              workspaceId: workspace.id,
              workspaceName: workspace.name,
              runId,
            },
            async () => {
              // Idempotency check (45-day TTL for payroll)
              const idem = await executeIdempotencyCheck({
                workspaceId: workspace.id,
                operationType: 'payroll_run',
                requestData: buildPayrollFingerprintData(workspace, today),
                ttlDays: 45, // Longer TTL for critical payroll operations
              });
              
              if (!idem.isNew) {
                console.log(`   ⚠️  Duplicate payroll processing detected (idempotency key ${idem.idempotencyKeyId})`);
                console.log(`   Existing status: ${idem.status}, skipping execution`);
                return { 
                  employeesProcessed: 0,
                  grossPay: 0,
                  netPay: 0,
                  isDuplicate: true,
                  idempotencyKeyId: idem.idempotencyKeyId,
                };
              }
              
              console.log(`   ✓ New operation confirmed (key ${idem.idempotencyKeyId}), processing payroll...`);
              
              try {
                // Get workspace owner to attribute payroll run
                const [owner] = await db
                  .select()
                  .from(employees)
                  .where(
                    and(
                      eq(employees.workspaceId, workspace.id),
                      eq(employees.workspaceRole, 'org_owner')
                    )
                  )
                  .limit(1);

                if (owner && owner.userId) {
                  // Process automated payroll
                  const result = await PayrollAutomationEngine.processAutomatedPayroll(
                    workspace.id,
                    owner.userId
                  );

                  console.log(`✅ Payroll processed for ${workspace.name}:`);
                  console.log(`   Employees: ${result.totalEmployees}`);
                  console.log(`   Gross Pay: $${result.totalGrossPay.toFixed(2)}`);
                  console.log(`   Net Pay: $${result.totalNetPay.toFixed(2)}`);
                  
                  totalPayrollRuns++;
                  successCount++;
                  
                  // Update lastRunAt, advance anchor, and mark idempotency complete (ATOMIC)
                  await db.transaction(async (tx) => {
                    const updateData: any = { lastPayrollRunAt: today };
                    
                    // Advance biweekly anchor if applicable
                    if (paySchedule === 'biweekly' && workspace.payrollBiweeklyAnchor) {
                      const newAnchor = advanceAnchor(workspace.payrollBiweeklyAnchor);
                      updateData.payrollBiweeklyAnchor = newAnchor;
                    }
                    
                    await tx.update(workspaces)
                      .set(updateData)
                      .where(eq(workspaces.id, workspace.id));
                    
                    // Mark idempotency complete in SAME transaction
                    await updateIdempotencyResult({
                      idempotencyKeyId: idem.idempotencyKeyId,
                      status: 'completed',
                      resultId: result.payrollRunId ? String(result.payrollRunId) : undefined,
                      resultMetadata: {
                        employeesProcessed: result.totalEmployees,
                        grossPay: result.totalGrossPay,
                        netPay: result.totalNetPay,
                        isDuplicate: false,
                        workspaceName: workspace.name,
                        schedule: paySchedule,
                        periodStart: buildPayrollFingerprintData(workspace, today).periodStart,
                        periodEnd: buildPayrollFingerprintData(workspace, today).periodEnd,
                      },
                    }, tx); // Pass transaction client for atomic update
                  });
                  
                  return {
                    employeesProcessed: result.totalEmployees,
                    grossPay: result.totalGrossPay,
                    netPay: result.totalNetPay,
                    isDuplicate: false,
                    idempotencyKeyId: idem.idempotencyKeyId,
                  };
                } else {
                  console.log(`⚠️  No owner found for ${workspace.name}, skipping payroll`);
                  
                  // Still mark idempotency as complete (zero result is valid)
                  await updateIdempotencyResult({
                    idempotencyKeyId: idem.idempotencyKeyId,
                    status: 'completed',
                    resultMetadata: {
                      employeesProcessed: 0,
                      grossPay: 0,
                      netPay: 0,
                      isDuplicate: false,
                      workspaceName: workspace.name,
                      schedule: paySchedule,
                      reason: 'no_owner',
                    },
                  });
                  
                  return { employeesProcessed: 0, grossPay: 0, netPay: 0 };
                }
              } catch (error: any) {
                // Mark idempotency operation failed with full error context
                await updateIdempotencyResult({
                  idempotencyKeyId: idem.idempotencyKeyId,
                  status: 'failed',
                  errorMessage: error.message,
                  errorStack: error.stack,
                  resultMetadata: {
                    isDuplicate: false,
                    workspaceName: workspace.name,
                    schedule: paySchedule,
                  },
                });
                throw error; // Re-throw to trigger audit log error
              }
            }
          );
        } else {
          console.log(`   ℹ️  Not a pay period date, skipping`);
        }

      } catch (error) {
        console.error(`❌ Failed to process payroll for ${workspace.name}:`, error);
        errorCount++;
      }
    }

    console.log('\n=================================================');
    console.log('📈 PAYROLLOS™ AUTONOMOUS PAYROLL - SUMMARY');
    console.log(`Total Workspaces Checked: ${activeWorkspaces.length}`);
    console.log(`Payroll Runs Processed: ${totalPayrollRuns}`);
    console.log(`Successful: ${successCount}`);
    console.log(`Errors: ${errorCount}`);
    console.log('=================================================\n');

  } catch (error) {
    console.error('💥 Critical error in automatic payroll processing:', error);
  }
}

/**
 * Daily Idempotency Key Cleanup
 * Removes expired keys based on TTL to prevent database bloat
 * Runs at 4 AM after all automation jobs complete
 */
async function runIdempotencyKeyCleanup() {
  console.log('=================================================');
  console.log('🧹 IDEMPOTENCY KEY CLEANUP - START');
  console.log(`Timestamp: ${new Date().toISOString()}`);
  console.log('=================================================');
  
  try {
    const runId = `cleanup-${Date.now()}`;
    
    await logAutomationLifecycle(
      {
        jobType: 'idempotency_cleanup',
        workspaceId: 'system',
        workspaceName: 'System-wide Cleanup',
        runId,
      },
      async () => {
        // Calculate expiration threshold
        // Use 60 days as max retention (beyond longest TTL of 45 days for payroll)
        const maxRetentionDays = 60;
        const expirationThreshold = new Date();
        expirationThreshold.setDate(expirationThreshold.getDate() - maxRetentionDays);
        
        console.log(`Removing idempotency keys older than ${maxRetentionDays} days`);
        console.log(`Expiration threshold: ${expirationThreshold.toISOString()}`);
        
        // Delete expired keys
        const deletedKeys = await db
          .delete(idempotencyKeys)
          .where(sql`${idempotencyKeys.createdAt} < ${expirationThreshold}`)
          .returning({ id: idempotencyKeys.id });
        
        const deletedCount = deletedKeys.length;
        
        if (deletedCount > 0) {
          console.log(`✅ Cleaned up ${deletedCount} expired idempotency key(s)`);
        } else {
          console.log(`ℹ️  No expired keys found`);
        }
        
        return { 
          keysDeleted: deletedCount,
          retentionDays: maxRetentionDays,
          expirationThreshold: expirationThreshold.toISOString(),
        };
      }
    );
    
  } catch (error) {
    console.error('💥 Critical error in idempotency key cleanup:', error);
  }
  
  console.log('=================================================\n');
}

/**
 * Room Auto-Close Automation
 * Runs every 5 minutes to close expired shift rooms
 */
async function runRoomAutoClose() {
  console.log('=================================================');
  console.log('🤖 COMMOS™ ROOM AUTO-CLOSE - START');
  console.log(`Timestamp: ${new Date().toISOString()}`);
  console.log('=================================================');

  try {
    const now = new Date();
    
    // Truncate to 5-minute window for idempotency
    const windowStart = new Date(now);
    windowStart.setMinutes(Math.floor(now.getMinutes() / 5) * 5, 0, 0);
    const windowEnd = new Date(windowStart);
    windowEnd.setMinutes(windowStart.getMinutes() + 5);
    
    // Find all expired rooms that are still active
    const expiredRooms = await db
      .select({
        id: chatConversations.id,
        workspaceId: chatConversations.workspaceId,
        subject: chatConversations.subject,
        conversationType: chatConversations.conversationType,
        autoCloseAt: chatConversations.autoCloseAt,
        status: chatConversations.status,
      })
      .from(chatConversations)
      .where(
        and(
          eq(chatConversations.status, 'active'),
          lt(chatConversations.autoCloseAt, now),
          sql`${chatConversations.autoCloseAt} IS NOT NULL`
        )
      )
      .orderBy(chatConversations.workspaceId);

    console.log(`Found ${expiredRooms.length} expired room(s) to auto-close`);

    if (expiredRooms.length === 0) {
      console.log('ℹ️  No expired rooms found');
      console.log('=================================================\n');
      return;
    }

    // Build idempotency fingerprint
    const roomCountHash = crypto
      .createHash('sha256')
      .update(expiredRooms.map(r => r.id).join(','))
      .digest('hex')
      .substring(0, 16);

    const fingerprintData = {
      jobType: 'room_auto_close',
      windowStart: windowStart.toISOString(),
      windowEnd: windowEnd.toISOString(),
      roomCount: expiredRooms.length,
      roomCountHash,
    };

    const runId = `room-auto-close-${windowStart.toISOString().replace(/[:.]/g, '-')}`;
    const idempotencyKey = `automation:room_auto_close:${crypto
      .createHash('sha256')
      .update(JSON.stringify(fingerprintData))
      .digest('hex')}`;

    // Check idempotency
    const idempotencyResult = await executeIdempotencyCheck({
      workspaceId: 'system', // System-wide job
      operationType: 'room_auto_close',
      requestData: fingerprintData,
      ttlDays: 7 // TTL: 7 days (short retention for frequent job)
    });

    if (!idempotencyResult.isNew) {
      console.log(`⏭️  Skipping - already processed this batch`);
      console.log('=================================================\n');
      return;
    }

    // Group rooms by workspace for batch processing
    const roomsByWorkspace = new Map<string, typeof expiredRooms>();
    for (const room of expiredRooms) {
      if (!roomsByWorkspace.has(room.workspaceId)) {
        roomsByWorkspace.set(room.workspaceId, []);
      }
      roomsByWorkspace.get(room.workspaceId)!.push(room);
    }

    let totalRoomsClosed = 0;
    let successWorkspaces = 0;
    let errorWorkspaces = 0;

    // Process each workspace
    for (const [workspaceId, rooms] of Array.from(roomsByWorkspace.entries())) {
      try {
        // Get workspace name for audit logging
        const [workspace] = await db
          .select({ name: workspaces.name })
          .from(workspaces)
          .where(eq(workspaces.id, workspaceId))
          .limit(1);

        const workspaceName = workspace?.name || 'Unknown Workspace';
        
        console.log(`\n📊 Processing workspace: ${workspaceName} (${workspaceId})`);
        console.log(`   Rooms to close: ${rooms.length}`);

        // Use transaction for atomic updates
        await db.transaction(async (tx) => {
          for (const room of rooms) {
            // Update room status
            await tx
              .update(chatConversations)
              .set({ 
                status: 'closed',
                updatedAt: now,
              })
              .where(eq(chatConversations.id, room.id));

            // Create room event
            await tx.insert(roomEvents).values({
              workspaceId: room.workspaceId,
              conversationId: room.id,
              actorId: null, // System automation
              actorName: AUTOFORCE_AUTOMATION_USER.userName,
              actorRole: AUTOFORCE_AUTOMATION_USER.userRole,
              eventType: 'room_closed',
              description: `Room auto-closed at ${now.toISOString()} (scheduled: ${room.autoCloseAt})`,
              eventPayload: {
                previousStatus: room.status,
                autoCloseAt: room.autoCloseAt,
                conversationType: room.conversationType,
                automationRunId: runId,
              },
              ipAddress: '127.0.0.1',
            });

            console.log(`   ✅ Closed room: ${room.subject || room.id}`);
            totalRoomsClosed++;
          }
        });

        // Log to AuditOS for workspace
        await logAutomationLifecycle(
          {
            jobType: 'room_auto_close',
            workspaceId,
            workspaceName,
            runId,
          },
          async () => ({
            roomsClosed: rooms.length,
            roomIds: rooms.map((r: any) => r.id),
          })
        );

        successWorkspaces++;
      } catch (error: any) {
        console.error(`   ❌ Error processing workspace ${workspaceId}:`, error.message);
        errorWorkspaces++;
      }
    }

    // Mark idempotency key as completed
    await updateIdempotencyResult({
      idempotencyKeyId: idempotencyResult.idempotencyKeyId,
      status: 'completed',
      resultMetadata: {
        totalRoomsClosed,
        successWorkspaces,
        errorWorkspaces,
        timestamp: now.toISOString(),
      },
    });

    console.log(`\n✅ Auto-close complete: ${totalRoomsClosed} room(s) closed`);
    console.log(`   Workspaces processed: ${successWorkspaces} success, ${errorWorkspaces} errors`);

  } catch (error) {
    console.error('💥 Critical error in room auto-close:', error);
  }

  console.log('=================================================\n');
}

// ============================================================================
// SCHEDULER INITIALIZATION
// ============================================================================

let isSchedulerRunning = false;

/**
 * Start all autonomous job schedulers
 */
export function startAutonomousScheduler() {
  if (isSchedulerRunning) {
    console.log('⚠️  Autonomous scheduler is already running');
    return;
  }

  console.log('\n╔════════════════════════════════════════════════╗');
  console.log('║  🤖 AUTOFORCE™ AUTONOMOUS SCHEDULER STARTING  ║');
  console.log('╚════════════════════════════════════════════════╝\n');

  // 1. Nightly Invoice Generation (2 AM daily)
  if (SCHEDULER_CONFIG.invoicing.enabled) {
    cron.schedule(SCHEDULER_CONFIG.invoicing.schedule, () => {
      runNightlyInvoiceGeneration();
    });
    console.log('✅ BillOS™ Invoicing Automation:');
    console.log(`   Schedule: ${SCHEDULER_CONFIG.invoicing.schedule} (daily 2 AM)`);
    console.log(`   ${SCHEDULER_CONFIG.invoicing.description}\n`);
  }

  // 2. Schedule Generation (11 PM daily)
  if (SCHEDULER_CONFIG.scheduling.enabled) {
    cron.schedule(SCHEDULER_CONFIG.scheduling.schedule, () => {
      runWeeklyScheduleGeneration();
    });
    console.log('✅ OperationsOS™ Schedule Automation:');
    console.log(`   Schedule: ${SCHEDULER_CONFIG.scheduling.schedule} (daily 11 PM)`);
    console.log(`   ${SCHEDULER_CONFIG.scheduling.description}\n`);
  }

  // 3. Automatic Payroll Processing (3 AM daily)
  if (SCHEDULER_CONFIG.payroll.enabled) {
    cron.schedule(SCHEDULER_CONFIG.payroll.schedule, () => {
      runAutomaticPayrollProcessing();
    });
    console.log('✅ BillOS™ Payroll Automation:');
    console.log(`   Schedule: ${SCHEDULER_CONFIG.payroll.schedule} (daily 3 AM)`);
    console.log(`   ${SCHEDULER_CONFIG.payroll.description}\n`);
  }

  // 4. Idempotency Key Cleanup (4 AM daily)
  if (SCHEDULER_CONFIG.cleanup.enabled) {
    cron.schedule(SCHEDULER_CONFIG.cleanup.schedule, () => {
      runIdempotencyKeyCleanup();
    });
    console.log('✅ Idempotency Key Cleanup:');
    console.log(`   Schedule: ${SCHEDULER_CONFIG.cleanup.schedule} (daily 4 AM)`);
    console.log(`   ${SCHEDULER_CONFIG.cleanup.description}\n`);
  }

  // 5. CommOS™ Room Auto-Close (Every 5 minutes)
  if (SCHEDULER_CONFIG.roomAutoClose.enabled) {
    cron.schedule(SCHEDULER_CONFIG.roomAutoClose.schedule, () => {
      runRoomAutoClose();
    });
    console.log('✅ CommOS™ Room Auto-Close:');
    console.log(`   Schedule: ${SCHEDULER_CONFIG.roomAutoClose.schedule} (every 5 minutes)`);
    console.log(`   ${SCHEDULER_CONFIG.roomAutoClose.description}\n`);
  }

  // 6. WebSocket Connection Cleanup (Every 5 minutes)
  if (SCHEDULER_CONFIG.wsConnectionCleanup.enabled) {
    cron.schedule(SCHEDULER_CONFIG.wsConnectionCleanup.schedule, () => {
      runWebSocketConnectionCleanup();
    });
    console.log('✅ WebSocket Connection Cleanup:');
    console.log(`   Schedule: ${SCHEDULER_CONFIG.wsConnectionCleanup.schedule} (every 5 minutes)`);
    console.log(`   ${SCHEDULER_CONFIG.wsConnectionCleanup.description}\n`);
  }

  isSchedulerRunning = true;

  console.log('╔════════════════════════════════════════════════╗');
  console.log('║  ✅ AUTONOMOUS SCHEDULER RUNNING SUCCESSFULLY  ║');
  console.log('╚════════════════════════════════════════════════╝\n');
}

/**
 * Manually trigger jobs for testing
 */
export const manualTriggers = {
  invoicing: runNightlyInvoiceGeneration,
  scheduling: runWeeklyScheduleGeneration,
  payroll: runAutomaticPayrollProcessing,
  cleanup: runIdempotencyKeyCleanup,
  roomAutoClose: runRoomAutoClose,
  wsConnectionCleanup: runWebSocketConnectionCleanup,
};
