/**
 * Notification Service - Automated notification creation and delivery
 * Creates and sends notifications to users for various platform events
 */

import { db } from '../db';
import { notifications } from '@shared/schema';
import { eq, and } from 'drizzle-orm';

interface CreateNotificationParams {
  workspaceId: string;
  userId: string;
  type: string;
  title: string;
  message: string;
  actionUrl?: string;
  relatedEntityType?: string;
  relatedEntityId?: string;
  metadata?: Record<string, any>;
  createdBy?: string;
}

/**
 * Create and send a notification to a user
 * Note: WebSocket broadcasting is handled automatically by the notification routes
 */
export async function createNotification(params: CreateNotificationParams) {
  try {
    const [notification] = await db
      .insert(notifications)
      .values({
        workspaceId: params.workspaceId,
        userId: params.userId,
        type: params.type as any,
        title: params.title,
        message: params.message,
        actionUrl: params.actionUrl,
        relatedEntityType: params.relatedEntityType,
        relatedEntityId: params.relatedEntityId,
        metadata: params.metadata,
        createdBy: params.createdBy,
        isRead: false,
      })
      .returning();

    console.log(`[Notifications] Created notification for user ${params.userId}: ${params.title}`);

    return notification;
  } catch (error) {
    console.error('[Notifications] Error creating notification:', error);
    throw error;
  }
}

/**
 * Send welcome notification when a new organization is created
 */
export async function sendWelcomeOrgNotification(workspaceId: string, ownerId: string, orgName: string) {
  return createNotification({
    workspaceId,
    userId: ownerId,
    type: 'welcome_org',
    title: '🎉 Welcome to AutoForce™!',
    message: `Your organization "${orgName}" is ready. Our AI Brain will help you manage your workforce with 99% automation. Get started by adding employees and creating your first schedule.`,
    actionUrl: '/dashboard',
    relatedEntityType: 'workspace',
    relatedEntityId: workspaceId,
    metadata: { orgName },
  });
}

/**
 * Send welcome notification when a new employee is added
 */
export async function sendWelcomeEmployeeNotification(
  workspaceId: string,
  userId: string,
  employeeName: string,
  orgName: string
) {
  return createNotification({
    workspaceId,
    userId,
    type: 'welcome_employee',
    title: '👋 Welcome to the Team!',
    message: `Welcome to ${orgName}! You've been added as an employee. Check your schedule, clock in/out, request time off, and manage your profile here.`,
    actionUrl: '/employee-portal',
    relatedEntityType: 'employee',
    relatedEntityId: userId,
    metadata: { employeeName, orgName },
  });
}

/**
 * Send notification when AI Brain needs approval for a workflow
 */
export async function sendAIApprovalNeededNotification(
  workspaceId: string,
  userId: string,
  actionType: string,
  deadline: Date,
  details: string,
  actionUrl?: string
) {
  const daysUntilDeadline = Math.ceil((deadline.getTime() - Date.now()) / (1000 * 60 * 60 * 24));
  
  return createNotification({
    workspaceId,
    userId,
    type: 'ai_approval_needed',
    title: '🤖 AI Brain Approval Required',
    message: `${details} Please review and approve within ${daysUntilDeadline} days to avoid business disruption.`,
    actionUrl: actionUrl || '/dashboard',
    relatedEntityType: 'ai_workflow',
    relatedEntityId: workspaceId,
    metadata: { actionType, deadline: deadline.toISOString(), daysUntilDeadline },
  });
}

/**
 * Send notification when AI-generated schedule is ready for approval
 */
export async function sendAIScheduleReadyNotification(
  workspaceId: string,
  userId: string,
  scheduleId: string,
  period: string
) {
  return createNotification({
    workspaceId,
    userId,
    type: 'ai_schedule_ready',
    title: '📅 AI Schedule Ready for Approval',
    message: `Your AI-generated schedule for ${period} is ready for review. Approve it to publish to your team.`,
    actionUrl: `/schedule/${scheduleId}`,
    relatedEntityType: 'schedule',
    relatedEntityId: scheduleId,
    metadata: { period },
  });
}

/**
 * Send notification when invoice is generated
 */
export async function sendInvoiceGeneratedNotification(
  workspaceId: string,
  userId: string,
  invoiceId: string,
  clientName: string,
  amount: number
) {
  return createNotification({
    workspaceId,
    userId,
    type: 'invoice_generated',
    title: '💰 Invoice Generated',
    message: `Invoice for ${clientName} has been automatically generated by AI Brain. Amount: $${amount.toFixed(2)}`,
    actionUrl: `/invoices/${invoiceId}`,
    relatedEntityType: 'invoice',
    relatedEntityId: invoiceId,
    metadata: { clientName, amount },
  });
}

/**
 * Send notification when payment is received
 */
export async function sendPaymentReceivedNotification(
  workspaceId: string,
  userId: string,
  invoiceId: string,
  clientName: string,
  amount: number
) {
  return createNotification({
    workspaceId,
    userId,
    type: 'payment_received',
    title: '✅ Payment Received',
    message: `Payment of $${amount.toFixed(2)} received from ${clientName}.`,
    actionUrl: `/invoices/${invoiceId}`,
    relatedEntityType: 'payment',
    relatedEntityId: invoiceId,
    metadata: { clientName, amount },
  });
}

/**
 * Send notification when deadline is approaching
 */
export async function sendDeadlineApproachingNotification(
  workspaceId: string,
  userId: string,
  actionType: string,
  deadline: Date,
  actionUrl?: string
) {
  const hoursUntilDeadline = Math.ceil((deadline.getTime() - Date.now()) / (1000 * 60 * 60));
  
  return createNotification({
    workspaceId,
    userId,
    type: 'deadline_approaching',
    title: '⚠️ Deadline Approaching',
    message: `${actionType} deadline is approaching in ${hoursUntilDeadline} hours. Please take action to avoid business disruption.`,
    actionUrl: actionUrl || '/dashboard',
    relatedEntityType: 'deadline',
    relatedEntityId: workspaceId,
    metadata: { actionType, deadline: deadline.toISOString(), hoursUntilDeadline },
  });
}

/**
 * Send notification when AI Brain completes an automated action
 */
export async function sendAIActionCompletedNotification(
  workspaceId: string,
  userId: string,
  actionType: string,
  details: string,
  actionUrl?: string
) {
  return createNotification({
    workspaceId,
    userId,
    type: 'ai_action_completed',
    title: '✨ AI Brain Action Completed',
    message: `${details}`,
    actionUrl: actionUrl || '/dashboard',
    relatedEntityType: 'ai_action',
    relatedEntityId: workspaceId,
    metadata: { actionType },
  });
}

/**
 * Send notification for schedule changes
 */
export async function sendScheduleChangeNotification(
  workspaceId: string,
  userId: string,
  details: string,
  scheduleId?: string
) {
  return createNotification({
    workspaceId,
    userId,
    type: 'schedule_change',
    title: '📅 Schedule Updated',
    message: details,
    actionUrl: scheduleId ? `/schedule/${scheduleId}` : '/schedule',
    relatedEntityType: 'schedule',
    relatedEntityId: scheduleId,
    metadata: { details },
  });
}

/**
 * Send notification for payroll processing
 */
export async function sendPayrollProcessedNotification(
  workspaceId: string,
  userId: string,
  period: string,
  amount: number
) {
  return createNotification({
    workspaceId,
    userId,
    type: 'payroll_processed',
    title: '💵 Payroll Processed',
    message: `Your payroll for ${period} has been processed. Amount: $${amount.toFixed(2)}`,
    actionUrl: '/employee-portal',
    relatedEntityType: 'payroll',
    relatedEntityId: userId,
    metadata: { period, amount },
  });
}
