import PDFDocument from 'pdfkit';
import { pool } from '../db';
import { format } from 'date-fns';
import { typedPool } from '../lib/typedSql';

interface ProposalData {
  id: string;
  workspace_id: string;
  proposal_name: string;
  version: number;
  template_id: string | null;
  client_name: string | null;
  client_address: string | null;
  client_contact: string | null;
  client_email: string | null;
  client_phone: string | null;
  company_name: string | null;
  company_address: string | null;
  company_phone: string | null;
  company_email: string | null;
  company_logo: string | null;
  total_value: string | null;
  valid_until: string | null;
  sections: any[] | null;
  line_items: any[] | null;
  terms_and_conditions: string | null;
  status: string;
  created_by: string | null;
  created_at: string;
}

interface LineItem {
  description: string;
  quantity: number;
  rate: number;
  total: number;
}

interface ProposalSection {
  title: string;
  content: string;
}

async function q(text: string, params: any[] = []) {
  const r = await typedPool(text, params);
  return r.rows;
}

function renderPdfHeader(doc: PDFKit.PDFDocument, companyName: string, proposalName: string) {
  const blue = '#1e3a5f';
  const gray = '#6b7280';
  doc.fontSize(20).fillColor(blue).text(companyName.toUpperCase(), { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(14).fillColor(blue).text('PROPOSAL / BID', { align: 'center' });
  doc.moveDown(0.2);
  doc.fontSize(11).fillColor(gray).text(proposalName, { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(8).fillColor(gray).text(`Generated: ${format(new Date(), 'MMMM dd, yyyy')}`, { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#d1d5db').stroke();
  doc.moveDown(0.5);
}

function renderField(doc: PDFKit.PDFDocument, label: string, value: string, x: number, yPos: number) {
  doc.fontSize(8).fillColor('#6b7280').text(label, x, yPos);
  doc.fontSize(10).fillColor('#111827').text(value || 'N/A', x, yPos + 11);
}

function renderSectionTitle(doc: PDFKit.PDFDocument, title: string) {
  doc.fontSize(12).fillColor('#1e3a5f').text(title);
  doc.moveDown(0.3);
}

function renderDivider(doc: PDFKit.PDFDocument) {
  doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#d1d5db').stroke();
  doc.moveDown(0.5);
}

function renderLineItems(doc: PDFKit.PDFDocument, items: LineItem[]) {
  if (!items || items.length === 0) return;
  if (doc.y > 600) doc.addPage();
  renderDivider(doc);
  renderSectionTitle(doc, 'PRICING BREAKDOWN');

  const headers = ['Description', 'Qty', 'Rate', 'Total'];
  const colWidths = [260, 60, 80, 80];
  let xPos = 50;

  doc.fontSize(8).fillColor('#6b7280');
  headers.forEach((h, i) => {
    doc.text(h, xPos, doc.y, { width: colWidths[i], continued: false });
    xPos += colWidths[i] + 8;
  });
  doc.moveDown(0.4);
  doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#e5e7eb').stroke();
  doc.moveDown(0.3);

  let grandTotal = 0;
  items.forEach((item) => {
    if (doc.y > 700) doc.addPage();
    xPos = 50;
    const rowY = doc.y;
    const lineTotal = (item.quantity || 0) * (item.rate || 0);
    grandTotal += item.total || lineTotal;

    doc.fontSize(9).fillColor('#111827');
    doc.text(item.description || '', xPos, rowY, { width: colWidths[0] }); xPos += colWidths[0] + 8;
    doc.text(String(item.quantity || 0), xPos, rowY, { width: colWidths[1] }); xPos += colWidths[1] + 8;
    doc.text(`$${(item.rate || 0).toFixed(2)}`, xPos, rowY, { width: colWidths[2] }); xPos += colWidths[2] + 8;
    doc.text(`$${(item.total || lineTotal).toFixed(2)}`, xPos, rowY, { width: colWidths[3] });
    doc.moveDown(0.6);
  });

  doc.moveDown(0.2);
  doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#e5e7eb').stroke();
  doc.moveDown(0.3);
  doc.fontSize(11).fillColor('#1e3a5f').text(`Total: $${grandTotal.toFixed(2)}`, { align: 'right' });
  doc.moveDown(0.5);
}

function renderFooter(doc: PDFKit.PDFDocument, proposalId: string) {
  doc.fontSize(7).fillColor('#9ca3af');
  doc.text(
    `Generated by CoAIleague Platform | Proposal ID: ${proposalId.slice(0, 8).toUpperCase()} | ${format(new Date(), 'MMM dd, yyyy hh:mm a')}`,
    50, 730,
    { width: 512, align: 'center' }
  );
}

export async function generateProposalPdf(proposalId: string, workspaceId: string): Promise<Buffer> {
  const rows = await q(`SELECT * FROM proposals WHERE id=$1 AND workspace_id=$2`, [proposalId, workspaceId]);
  if (!rows.length) throw new Error('Proposal not found');
  const proposal = rows[0] as unknown as ProposalData;

  const wsRows = await q(`SELECT name FROM workspaces WHERE id=$1`, [workspaceId]);
  const orgName = (wsRows[0] as any)?.name || proposal.company_name || 'Security Organization';

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
      info: {
        Title: `Proposal - ${proposal.proposal_name}`,
        Author: orgName,
        Subject: 'Business Proposal',
      },
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    renderPdfHeader(doc, proposal.company_name || orgName, proposal.proposal_name);

    let y = doc.y;
    renderField(doc, 'Prepared For', proposal.client_name || 'N/A', 50, y);
    renderField(doc, 'Prepared By', proposal.company_name || orgName, 310, y);
    y += 30;
    renderField(doc, 'Client Contact', proposal.client_contact || 'N/A', 50, y);
    renderField(doc, 'Company Phone', proposal.company_phone || 'N/A', 310, y);
    y += 30;
    renderField(doc, 'Client Email', proposal.client_email || 'N/A', 50, y);
    renderField(doc, 'Company Email', proposal.company_email || 'N/A', 310, y);
    y += 30;
    if (proposal.client_address || proposal.company_address) {
      renderField(doc, 'Client Address', proposal.client_address || 'N/A', 50, y);
      renderField(doc, 'Company Address', proposal.company_address || 'N/A', 310, y);
      y += 30;
    }
    if (proposal.valid_until) {
      renderField(doc, 'Valid Until', format(new Date(proposal.valid_until), 'MMMM dd, yyyy'), 50, y);
      renderField(doc, 'Version', String(proposal.version || 1), 310, y);
      y += 30;
    }
    doc.y = y + 10;

    const sections = (proposal.sections || []) as ProposalSection[];
    if (sections.length > 0) {
      for (const section of sections) {
        if (doc.y > 650) doc.addPage();
        renderDivider(doc);
        renderSectionTitle(doc, section.title?.toUpperCase() || 'SECTION');
        doc.fontSize(10).fillColor('#111827').text(section.content || '', { width: 512 });
        doc.moveDown(0.5);
      }
    }

    const lineItems = (proposal.line_items || []) as LineItem[];
    renderLineItems(doc, lineItems);

    if (proposal.terms_and_conditions) {
      if (doc.y > 550) doc.addPage();
      renderDivider(doc);
      renderSectionTitle(doc, 'TERMS AND CONDITIONS');
      doc.fontSize(9).fillColor('#374151').text(proposal.terms_and_conditions, { width: 512 });
      doc.moveDown(0.5);
    }

    if (doc.y > 600) doc.addPage();
    renderDivider(doc);
    doc.moveDown(1);
    doc.fontSize(8).fillColor('#6b7280').text('Authorized Signature:', 50);
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y + 10).lineTo(260, doc.y + 10).strokeColor('#9ca3af').stroke();
    doc.moveDown(1.5);
    doc.fontSize(8).fillColor('#6b7280').text(proposal.company_name || orgName, 50);

    doc.fontSize(8).fillColor('#6b7280').text('Client Acceptance:', 310);
    doc.moveDown(0.3);
    doc.moveTo(310, doc.y + 10).lineTo(562, doc.y + 10).strokeColor('#9ca3af').stroke();
    doc.moveDown(1.5);
    doc.fontSize(8).fillColor('#6b7280').text(proposal.client_name || 'Client', 310);

    renderFooter(doc, proposal.id);
    doc.end();
  });
}
