import PDFDocument from 'pdfkit';
import { db } from "../db";
import {
  employees,
  payrollRuns,
  payrollEntries,
  payrollDeductions,
  workspaces,
  employeePayrollInfo
} from '@shared/schema';
import { eq, and, gte, lte, inArray, sql } from "drizzle-orm";
import { startOfYear, endOfYear, startOfQuarter, endOfQuarter } from "date-fns";
import { getTaxRules } from './tax/taxRulesRegistry';
import { createLogger } from '../lib/logger';
import { employeeTaxForms } from '@shared/schema';
import { saveToVault } from './documents/businessFormsVaultService';
const log = createLogger('taxFormGeneratorService');


const PLATFORM_DISCLAIMER = [
  'IMPORTANT: This document was auto-generated by CoAIleague AI-powered middleware.',
  'AI systems can make errors. It is the sole responsibility of the organization',
  'representative or owner to review and verify all figures before filing or submission.',
  'CoAIleague is not a financial institution, CPA firm, or tax preparer. CoAIleague',
  'provides workforce management middleware services only. CoAIleague is not responsible',
  'for errors, omissions, or inaccuracies unless directly caused by a verifiable defect',
  'in the CoAIleague processing engine. Consult a qualified tax professional or CPA',
  'before filing any tax documents with the IRS or state agencies.',
];

const PLATFORM_DISCLAIMER_SHORT = 'AI-generated. Verify all figures before filing. CoAIleague is middleware only — not a CPA, tax preparer, or financial institution. Organization is solely responsible for accuracy.';

function addPDFDisclaimer(doc: PDFKit.PDFDocument) {
  doc.moveDown(1);
  doc.fontSize(7).font('Helvetica-Bold').fillColor('#CC0000');
  doc.text('DISCLAIMER', { align: 'center' });
  doc.fontSize(6).font('Helvetica').fillColor('#333333');
  for (const line of PLATFORM_DISCLAIMER) {
    doc.text(line, { align: 'center' });
  }
  doc.moveDown(0.3);
  doc.fontSize(6).fillColor('gray');
  doc.text(`Generated by CoAIleague on ${new Date().toLocaleString()}`, { align: 'center' });
}

interface W2Box12Entry {
  code: string;
  amount: number;
}

interface W2Data {
  employerEIN: string;
  employerName: string;
  employerAddress: string;
  employeeSSN: string;
  employeeName: string;
  employeeAddress: string;
  taxYear: number;
  wages: number;
  federalTaxWithheld: number;
  socialSecurityWages: number;
  socialSecurityTaxWithheld: number;
  medicareWages: number;
  medicareTaxWithheld: number;
  stateTaxWithheld: number;
  stateWages: number;
  state: string;
  box12Entries?: W2Box12Entry[];
}

interface Form1099Data {
  payerEIN: string;
  payerName: string;
  payerAddress: string;
  recipientTIN: string;
  recipientName: string;
  recipientAddress: string;
  taxYear: number;
  nonemployeeCompensation: number;
  federalTaxWithheld: number;
}

interface Form940Data {
  employerEIN: string;
  employerName: string;
  employerAddress: string;
  taxYear: number;
  totalPayments: number;
  exemptPayments: number;
  taxableFUTAWages: number;
  futaTaxRate: number;
  futaTaxBeforeAdjustments: number;
  stateUnemploymentContributions: number;
  futaTaxAfterCredit: number;
  quarterlyLiabilities: { q1: number; q2: number; q3: number; q4: number };
  totalDeposited: number;
  balanceDue: number;
  numberOfEmployees: number;
  perEmployeeWageCap: number;
}

function maskSSN(ssn: string): string {
  if (!ssn || ssn.length < 4) return '***-**-****';
  const last4 = ssn.replace(/\D/g, '').slice(-4);
  return `***-**-${last4}`;
}

function formatCurrency(amount: number): string {
  return amount.toFixed(2);
}

interface Form941Data {
  employerEIN: string;
  employerName: string;
  employerAddress: string;
  quarter: number;
  taxYear: number;
  line1_numberOfEmployees: number;
  line2_wagesTipsCompensation: number;
  line3_federalIncomeTaxWithheld: number;
  line5a_taxableSocialSecurityWages: number;
  line5a_tax: number;
  line5b_taxableSocialSecurityTips: number;
  line5b_tax: number;
  line5c_taxableMedicareWages: number;
  line5c_tax: number;
  line5d_taxableMedicareWagesOverLimit: number;
  line5d_tax: number;
  line5e_totalSocialSecurityMedicareTaxes: number;
  line6_totalTaxesBeforeAdjustments: number;
  line10_totalTaxesAfterAdjustments: number;
  line11_totalDepositsForQuarter: number;
  line14_balanceDueOrOverpayment: number;
  employerSSRate: number;
  employerMedicareRate: number;
}

export class TaxFormGeneratorService {
  async aggregatePayrollDataForYear(
    employeeId: string,
    workspaceId: string,
    taxYear: number
  ): Promise<{
    totalWages: number;
    federalTaxWithheld: number;
    socialSecurityWages: number;
    socialSecurityTaxWithheld: number;
    medicareWages: number;
    medicareTaxWithheld: number;
    stateTaxWithheld: number;
  }> {
    const yearStart = startOfYear(new Date(taxYear, 0, 1));
    const yearEnd = endOfYear(new Date(taxYear, 0, 1));

    const result = await db
      .select({
        totalWages: sql<string>`COALESCE(SUM(CAST(${payrollEntries.grossPay} AS NUMERIC)), 0)`,
        federalTax: sql<string>`COALESCE(SUM(CAST(${payrollEntries.federalTax} AS NUMERIC)), 0)`,
        socialSecurity: sql<string>`COALESCE(SUM(CAST(${payrollEntries.socialSecurity} AS NUMERIC)), 0)`,
        medicare: sql<string>`COALESCE(SUM(CAST(${payrollEntries.medicare} AS NUMERIC)), 0)`,
        stateTax: sql<string>`COALESCE(SUM(CAST(${payrollEntries.stateTax} AS NUMERIC)), 0)`,
      })
      .from(payrollEntries)
      .innerJoin(payrollRuns, eq(payrollEntries.payrollRunId, payrollRuns.id))
      .where(
        and(
          eq(payrollEntries.employeeId, employeeId),
          eq(payrollEntries.workspaceId, workspaceId),
          gte(payrollRuns.periodEnd, yearStart),
          lte(payrollRuns.periodEnd, yearEnd),
          inArray(payrollRuns.status, ['approved', 'processed', 'paid', 'completed'])
        )
      );

    const row = result[0];
    const totalWages = parseFloat(row?.totalWages || '0');
    const federalTaxWithheld = parseFloat(row?.federalTax || '0');
    const ssTax = parseFloat(row?.socialSecurity || '0');
    const medicareTax = parseFloat(row?.medicare || '0');
    const stateTaxWithheld = parseFloat(row?.stateTax || '0');

    return {
      totalWages,
      federalTaxWithheld,
      socialSecurityWages: totalWages,
      socialSecurityTaxWithheld: ssTax,
      medicareWages: totalWages,
      medicareTaxWithheld: medicareTax,
      stateTaxWithheld,
    };
  }

  async generateW2ForEmployee(
    employeeId: string,
    workspaceId: string,
    taxYear: number
  ): Promise<{ success: boolean; pdfBuffer?: Buffer; taxFormId?: string; error?: string }> {
    try {
      const employee = await db.query.employees.findFirst({
        where: and(eq(employees.id, employeeId), eq(employees.workspaceId, workspaceId)),
      });
      if (!employee) return { success: false, error: 'Employee not found' };

      const workspace = await db.query.workspaces.findFirst({
        where: eq(workspaces.id, workspaceId),
      });
      if (!workspace) return { success: false, error: 'Workspace not found' };

      const payrollInfo = await db.query.employeePayrollInfo.findFirst({
        where: and(eq(employeePayrollInfo.employeeId, employeeId), eq(employeePayrollInfo.workspaceId, workspaceId)),
      });

      const aggregated = await this.aggregatePayrollDataForYear(employeeId, workspaceId, taxYear);

      if (aggregated.totalWages === 0) {
        return { success: false, error: 'No payroll data found for this tax year' };
      }

      // F062 fix: Aggregate Box 12 deductions (401k Code D, HSA Code W) for the tax year
      const yearStart = new Date(taxYear, 0, 1);
      const yearEnd = new Date(taxYear, 11, 31, 23, 59, 59);
      const deductionAggRows = await db
        .select({
          deductionType: payrollDeductions.deductionType,
          total: sql<string>`COALESCE(SUM(CAST(${payrollDeductions.amount} AS NUMERIC)), 0)`,
        })
        .from(payrollDeductions)
        .innerJoin(payrollEntries, eq(payrollDeductions.payrollEntryId, payrollEntries.id))
        .innerJoin(payrollRuns, eq(payrollEntries.payrollRunId, payrollRuns.id))
        .where(
          and(
            eq(payrollDeductions.employeeId, employeeId),
            eq(payrollDeductions.workspaceId, workspaceId),
            eq(payrollDeductions.isPreTax, true),
            gte(payrollRuns.periodEnd, yearStart),
            lte(payrollRuns.periodEnd, yearEnd),
            inArray(payrollRuns.status, ['approved', 'processed', 'paid', 'completed'])
          )
        )
        .groupBy(payrollDeductions.deductionType);

      const DEDUCTION_TYPE_TO_W2_CODE: Record<string, string> = {
        '401k': 'D',
        'hsa': 'W',
        '403b': 'E',
        'simple_401k': 'S',
      };

      const box12Entries: W2Box12Entry[] = deductionAggRows
        .map(row => ({
          code: DEDUCTION_TYPE_TO_W2_CODE[row.deductionType.toLowerCase()] || '',
          amount: parseFloat(row.total || '0'),
        }))
        .filter(entry => entry.code !== '' && entry.amount > 0);

      const w2Data: W2Data = {
        employerEIN: (workspace as any).taxId || (workspace as any).ein || 'XX-XXXXXXX',
        employerName: (workspace as any).companyName || workspace.name || 'Employer',
        employerAddress: (workspace as any).address || '',
        employeeSSN: maskSSN(payrollInfo?.ssn || (employee as any).ssn || ''),
        employeeName: `${(employee as any).firstName || ''} ${(employee as any).lastName || ''}`.trim(),
        employeeAddress: (employee as any).address || '',
        taxYear,
        wages: aggregated.totalWages,
        federalTaxWithheld: aggregated.federalTaxWithheld,
        socialSecurityWages: aggregated.socialSecurityWages,
        socialSecurityTaxWithheld: aggregated.socialSecurityTaxWithheld,
        medicareWages: aggregated.medicareWages,
        medicareTaxWithheld: aggregated.medicareTaxWithheld,
        stateTaxWithheld: aggregated.stateTaxWithheld,
        stateWages: aggregated.totalWages,
        state: payrollInfo?.stateOfResidence || (employee as any).state || '',
        box12Entries,
      };

      const pdfBuffer = await this.generateW2PDF(w2Data);

      const [taxForm] = await db.insert(employeeTaxForms).values({
        workspaceId,
        employeeId,
        formType: 'w2',
        taxYear,
        wages: String(aggregated.totalWages),
        federalTaxWithheld: String(aggregated.federalTaxWithheld),
        socialSecurityWages: String(aggregated.socialSecurityWages),
        socialSecurityTaxWithheld: String(aggregated.socialSecurityTaxWithheld),
        medicareWages: String(aggregated.medicareWages),
        medicareTaxWithheld: String(aggregated.medicareTaxWithheld),
        stateTaxWithheld: String(aggregated.stateTaxWithheld),
        generatedAt: new Date(),
        isActive: true,
      }).returning();

      // Stamp branded header/footer and save to document vault
      const vaultResult = await saveToVault({
        workspaceId,
        workspaceName: (workspace as any)?.name || workspaceId,
        documentTitle: `W-2 Wage and Tax Statement`,
        category: 'tax',
        formNumber: 'W-2',
        period: String(taxYear),
        relatedEntityType: 'employee',
        relatedEntityId: employeeId,
        rawBuffer: pdfBuffer,
      });
      if (!vaultResult.success) {
        log.warn('[TaxFormGenerator] W-2 vault save failed (non-blocking):', vaultResult.error);
      }

      return {
        success: true,
        pdfBuffer: vaultResult.stampedBuffer || pdfBuffer,
        taxFormId: taxForm.id,
        vaultId: vaultResult.vault?.id,
        documentNumber: vaultResult.vault?.documentNumber,
      };
    } catch (error) {
      log.error('[TaxFormGenerator] W-2 generation failed:', error);
      return { success: false, error: String(error) };
    }
  }

  async generate1099ForEmployee(
    employeeId: string,
    workspaceId: string,
    taxYear: number
  ): Promise<{ success: boolean; pdfBuffer?: Buffer; taxFormId?: string; error?: string }> {
    try {
      const employee = await db.query.employees.findFirst({
        where: and(eq(employees.id, employeeId), eq(employees.workspaceId, workspaceId)),
      });
      if (!employee) return { success: false, error: 'Employee not found' };

      const workspace = await db.query.workspaces.findFirst({
        where: eq(workspaces.id, workspaceId),
      });
      if (!workspace) return { success: false, error: 'Workspace not found' };

      const payrollInfo = await db.query.employeePayrollInfo.findFirst({
        where: and(eq(employeePayrollInfo.employeeId, employeeId), eq(employeePayrollInfo.workspaceId, workspaceId)),
      });

      const aggregated = await this.aggregatePayrollDataForYear(employeeId, workspaceId, taxYear);

      if (aggregated.totalWages === 0) {
        return { success: false, error: 'No payroll data found for this tax year' };
      }

      const form1099Data: Form1099Data = {
        payerEIN: (workspace as any).taxId || (workspace as any).ein || 'XX-XXXXXXX',
        payerName: (workspace as any).companyName || workspace.name || 'Payer',
        payerAddress: (workspace as any).address || '',
        recipientTIN: maskSSN(payrollInfo?.ssn || (employee as any).ssn || ''),
        recipientName: `${(employee as any).firstName || ''} ${(employee as any).lastName || ''}`.trim(),
        recipientAddress: (employee as any).address || '',
        taxYear,
        nonemployeeCompensation: aggregated.totalWages,
        federalTaxWithheld: aggregated.federalTaxWithheld,
      };

      const pdfBuffer = await this.generate1099PDF(form1099Data);

      const [taxForm] = await db.insert(employeeTaxForms).values({
        workspaceId,
        employeeId,
        formType: '1099',
        taxYear,
        wages: String(aggregated.totalWages),
        federalTaxWithheld: String(aggregated.federalTaxWithheld),
        generatedAt: new Date(),
        isActive: true,
      }).returning();

      // Stamp + save to vault
      const vaultResult1099 = await saveToVault({
        workspaceId,
        workspaceName: (workspace as any)?.name || workspaceId,
        documentTitle: '1099-NEC Nonemployee Compensation',
        category: 'tax',
        formNumber: '1099-NEC',
        period: String(taxYear),
        relatedEntityType: 'employee',
        relatedEntityId: employeeId,
        rawBuffer: pdfBuffer,
      });
      if (!vaultResult1099.success) log.warn('[TaxFormGenerator] 1099 vault save failed:', vaultResult1099.error);

      return {
        success: true,
        pdfBuffer: vaultResult1099.stampedBuffer || pdfBuffer,
        taxFormId: taxForm.id,
        vaultId: vaultResult1099.vault?.id,
        documentNumber: vaultResult1099.vault?.documentNumber,
      };
    } catch (error) {
      log.error('[TaxFormGenerator] 1099-NEC generation failed:', error);
      return { success: false, error: String(error) };
    }
  }

  private async generateW2PDF(data: W2Data): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'LETTER', margin: 40 });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(16).font('Helvetica-Bold').text(`Form W-2 Wage and Tax Statement`, { align: 'center' });
      doc.fontSize(10).font('Helvetica').text(`Tax Year ${data.taxYear}`, { align: 'center' });
      doc.moveDown(1.5);

      const boxWidth = 250;
      const leftX = 40;
      const rightX = 300;
      let y = doc.y;

      doc.rect(leftX, y, boxWidth, 60).stroke();
      doc.fontSize(7).text('a  Employee\'s social security number', leftX + 5, y + 3);
      doc.fontSize(11).text(data.employeeSSN, leftX + 5, y + 18);

      doc.rect(rightX, y, boxWidth, 60).stroke();
      doc.fontSize(7).text('b  Employer identification number (EIN)', rightX + 5, y + 3);
      doc.fontSize(11).text(data.employerEIN, rightX + 5, y + 18);

      y += 65;
      doc.rect(leftX, y, boxWidth, 60).stroke();
      doc.fontSize(7).text('c  Employer\'s name, address, and ZIP code', leftX + 5, y + 3);
      doc.fontSize(9).text(data.employerName, leftX + 5, y + 16);
      doc.fontSize(8).text(data.employerAddress, leftX + 5, y + 30);

      doc.rect(rightX, y, boxWidth, 60).stroke();
      doc.fontSize(7).text('e  Employee\'s name and address', rightX + 5, y + 3);
      doc.fontSize(9).text(data.employeeName, rightX + 5, y + 16);
      doc.fontSize(8).text(data.employeeAddress, rightX + 5, y + 30);

      y += 70;
      const boxH = 45;
      const halfBox = boxWidth / 2;

      const drawBox = (x: number, yPos: number, w: number, h: number, label: string, value: string) => {
        doc.rect(x, yPos, w, h).stroke();
        doc.fontSize(7).text(label, x + 3, yPos + 3, { width: w - 6 });
        doc.fontSize(11).text(value, x + 5, yPos + 18);
      };

      drawBox(leftX, y, halfBox, boxH, '1  Wages, tips, other compensation', `$${formatCurrency(data.wages)}`);
      drawBox(leftX + halfBox, y, halfBox, boxH, '2  Federal income tax withheld', `$${formatCurrency(data.federalTaxWithheld)}`);
      drawBox(rightX, y, halfBox, boxH, '3  Social security wages', `$${formatCurrency(data.socialSecurityWages)}`);
      drawBox(rightX + halfBox, y, halfBox, boxH, '4  Social security tax withheld', `$${formatCurrency(data.socialSecurityTaxWithheld)}`);

      y += boxH + 2;
      drawBox(leftX, y, halfBox, boxH, '5  Medicare wages and tips', `$${formatCurrency(data.medicareWages)}`);
      drawBox(leftX + halfBox, y, halfBox, boxH, '6  Medicare tax withheld', `$${formatCurrency(data.medicareTaxWithheld)}`);
      drawBox(rightX, y, halfBox, boxH, '7  Social security tips', '$0.00');
      drawBox(rightX + halfBox, y, halfBox, boxH, '8  Allocated tips', '$0.00');

      y += boxH + 2;
      drawBox(leftX, y, halfBox, boxH, '9  (Blank)', '');
      drawBox(leftX + halfBox, y, halfBox, boxH, '10  Dependent care benefits', '$0.00');
      drawBox(rightX, y, halfBox, boxH, '11  Nonqualified plans', '$0.00');

      // F062 fix: Render Box 12 with actual pre-tax deduction codes (401k=D, HSA=W, etc.)
      const box12Labels = ['12a', '12b', '12c', '12d'];
      const box12Y = y;
      const box12W = halfBox;
      doc.rect(rightX + halfBox, box12Y, box12W, boxH).stroke();
      doc.fontSize(7).text('12  See instructions for box 12', rightX + halfBox + 3, box12Y + 3);
      if (data.box12Entries && data.box12Entries.length > 0) {
        data.box12Entries.slice(0, 4).forEach((entry, idx) => {
          const lineY = box12Y + 13 + idx * 8;
          doc.fontSize(8).font('Helvetica-Bold').text(
            `${box12Labels[idx]}  ${entry.code}  $${formatCurrency(entry.amount)}`,
            rightX + halfBox + 5, lineY, { width: box12W - 10 }
          );
        });
        doc.font('Helvetica');
      } else {
        doc.fontSize(8).text('None', rightX + halfBox + 5, box12Y + 18);
      }

      y += boxH + 10;
      drawBox(leftX, y, boxWidth, boxH, '15  State / Employer\'s state ID number', data.state);
      drawBox(rightX, y, halfBox, boxH, '16  State wages, tips, etc.', `$${formatCurrency(data.stateWages)}`);
      drawBox(rightX + halfBox, y, halfBox, boxH, '17  State income tax', `$${formatCurrency(data.stateTaxWithheld)}`);

      doc.moveDown(3);
      addPDFDisclaimer(doc);

      doc.end();
    });
  }

  async generate940Report(
    workspaceId: string,
    year: number
  ): Promise<{ success: boolean; pdfBuffer?: Buffer; data?: Form940Data; error?: string }> {
    try {
      const workspace = await db.query.workspaces.findFirst({
        where: eq(workspaces.id, workspaceId),
      });
      if (!workspace) return { success: false, error: 'Workspace not found' };

      const yearStart = startOfYear(new Date(year, 0, 1));
      const yearEnd = endOfYear(new Date(year, 0, 1));

      const taxRules = getTaxRules(year);
      const FUTA_WAGE_CAP = taxRules.futa.wageBase;
      const FUTA_GROSS_RATE = taxRules.futa.grossRate;
      const SUTA_CREDIT_RATE = taxRules.futa.maxSUTACredit;
      const FUTA_NET_RATE = taxRules.futa.netRate;

      const employeeWages = await db
        .select({
          employeeId: payrollEntries.employeeId,
          totalWages: sql<string>`COALESCE(SUM(CAST(${payrollEntries.grossPay} AS NUMERIC)), 0)`,
        })
        .from(payrollEntries)
        .innerJoin(payrollRuns, eq(payrollEntries.payrollRunId, payrollRuns.id))
        .where(
          and(
            eq(payrollEntries.workspaceId, workspaceId),
            gte(payrollRuns.periodEnd, yearStart),
            lte(payrollRuns.periodEnd, yearEnd),
            inArray(payrollRuns.status, ['approved', 'processed', 'paid', 'completed'])
          )
        )
        .groupBy(payrollEntries.employeeId);

      if (employeeWages.length === 0) {
        return { success: false, error: 'No payroll data found for this tax year' };
      }

      let totalPayments = 0;
      let taxableFUTAWages = 0;

      for (const emp of employeeWages) {
        const wages = parseFloat(emp.totalWages || '0');
        totalPayments += wages;
        taxableFUTAWages += Math.min(wages, FUTA_WAGE_CAP);
      }

      const exemptPayments = totalPayments - taxableFUTAWages;
      const futaTaxBeforeAdjustments = taxableFUTAWages * FUTA_GROSS_RATE;
      const stateUnemploymentContributions = taxableFUTAWages * SUTA_CREDIT_RATE;
      const futaTaxAfterCredit = taxableFUTAWages * FUTA_NET_RATE;

      const quarterlyLiabilities = { q1: 0, q2: 0, q3: 0, q4: 0 };
      for (let q = 0; q < 4; q++) {
        const qStart = startOfQuarter(new Date(year, q * 3, 1));
        const qEnd = endOfQuarter(new Date(year, q * 3, 1));

        const qWages = await db
          .select({
            employeeId: payrollEntries.employeeId,
            totalWages: sql<string>`COALESCE(SUM(CAST(${payrollEntries.grossPay} AS NUMERIC)), 0)`,
          })
          .from(payrollEntries)
          .innerJoin(payrollRuns, eq(payrollEntries.payrollRunId, payrollRuns.id))
          .where(
            and(
              eq(payrollEntries.workspaceId, workspaceId),
              gte(payrollRuns.periodEnd, qStart),
              lte(payrollRuns.periodEnd, qEnd),
              inArray(payrollRuns.status, ['approved', 'processed', 'paid', 'completed'])
            )
          )
          .groupBy(payrollEntries.employeeId);

        let qTaxable = 0;
        for (const emp of qWages) {
          const wages = parseFloat(emp.totalWages || '0');
          qTaxable += Math.min(wages, FUTA_WAGE_CAP);
        }

        const qKey = `q${q + 1}` as keyof typeof quarterlyLiabilities;
        quarterlyLiabilities[qKey] = qTaxable * FUTA_NET_RATE;
      }

      const form940Data: Form940Data = {
        employerEIN: (workspace as any).taxId || (workspace as any).ein || 'XX-XXXXXXX',
        employerName: (workspace as any).companyName || workspace.name || 'Employer',
        employerAddress: (workspace as any).address || '',
        taxYear: year,
        totalPayments,
        exemptPayments,
        taxableFUTAWages,
        futaTaxRate: FUTA_NET_RATE,
        futaTaxBeforeAdjustments,
        stateUnemploymentContributions,
        futaTaxAfterCredit,
        quarterlyLiabilities,
        totalDeposited: 0,
        balanceDue: futaTaxAfterCredit,
        numberOfEmployees: employeeWages.length,
        perEmployeeWageCap: FUTA_WAGE_CAP,
      };

      const pdfBuffer = await this.generate940PDF(form940Data);

      // Stamp + save to vault
      const workspace940 = await db.query.workspaces?.findFirst?.({ where: (w: any, { eq: e }: any) => e(w.id, workspaceId) });
      const vaultResult940 = await saveToVault({
        workspaceId,
        workspaceName: (workspace940 as any)?.name || workspaceId,
        documentTitle: 'Form 940 Employer Annual FUTA Tax Return',
        category: 'tax',
        formNumber: '940',
        relatedEntityType: 'workspace',
        relatedEntityId: workspaceId,
        rawBuffer: pdfBuffer,
      });
      if (!vaultResult940.success) log.warn('[TaxFormGenerator] 940 vault save failed:', vaultResult940.error);

      return {
        success: true,
        pdfBuffer: vaultResult940.stampedBuffer || pdfBuffer,
        data: form940Data,
        vaultId: vaultResult940.vault?.id,
        documentNumber: vaultResult940.vault?.documentNumber,
      };
    } catch (error) {
      log.error('[TaxFormGenerator] 940 generation failed:', error);
      return { success: false, error: String(error) };
    }
  }

  private async generate940PDF(data: Form940Data): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'LETTER', margin: 40 });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(16).font('Helvetica-Bold').text('Form 940', { align: 'center' });
      doc.fontSize(10).font('Helvetica').text("Employer's Annual Federal Unemployment (FUTA) Tax Return", { align: 'center' });
      doc.fontSize(10).text(`Tax Year ${data.taxYear}`, { align: 'center' });
      doc.moveDown(1);

      doc.fontSize(8).text('Department of the Treasury - Internal Revenue Service', { align: 'center' });
      doc.moveDown(1.5);

      const leftX = 40;
      const rightX = 300;
      const boxW = 250;
      let y = doc.y;

      const drawBox = (x: number, yPos: number, w: number, h: number, label: string, value: string) => {
        doc.rect(x, yPos, w, h).stroke();
        doc.fontSize(7).fillColor('black').text(label, x + 3, yPos + 3, { width: w - 6 });
        doc.fontSize(11).text(value, x + 5, yPos + 20);
      };

      drawBox(leftX, y, boxW, 50, 'Employer Identification Number (EIN)', data.employerEIN);
      drawBox(rightX, y, boxW, 50, 'Name (not your trade name)', data.employerName);

      y += 55;
      drawBox(leftX, y, boxW * 2 + 10, 40, 'Trade name (if any) and Address', data.employerAddress);

      y += 50;
      doc.fontSize(12).font('Helvetica-Bold').fillColor('black').text('Part 1: Tell us about your return', leftX, y);
      y += 20;

      const lineH = 30;
      const fullW = boxW * 2 + 10;
      const labelW = fullW * 0.7;
      const valW = fullW * 0.3;

      const drawLine = (yPos: number, lineNum: string, label: string, value: string) => {
        doc.rect(leftX, yPos, labelW, lineH).stroke();
        doc.rect(leftX + labelW, yPos, valW, lineH).stroke();
        doc.fontSize(8).font('Helvetica').fillColor('black').text(`${lineNum}  ${label}`, leftX + 3, yPos + 5, { width: labelW - 6 });
        doc.fontSize(10).font('Helvetica-Bold').text(value, leftX + labelW + 5, yPos + 8);
      };

      drawLine(y, '3', 'Total payments to all employees', `$${formatCurrency(data.totalPayments)}`);
      y += lineH;
      drawLine(y, '4', 'Payments exempt from FUTA tax', `$${formatCurrency(data.exemptPayments)}`);
      y += lineH;
      drawLine(y, '5', `Total of payments made to each employee in excess of $${data.perEmployeeWageCap.toLocaleString()}`, `$${formatCurrency(data.exemptPayments)}`);
      y += lineH;
      drawLine(y, '7', 'Total taxable FUTA wages (Line 3 - Line 4 - Line 5)', `$${formatCurrency(data.taxableFUTAWages)}`);
      y += lineH;
      drawLine(y, '8', `FUTA tax before adjustments (Line 7 x 0.006)`, `$${formatCurrency(data.futaTaxAfterCredit)}`);

      y += lineH + 10;
      doc.fontSize(12).font('Helvetica-Bold').fillColor('black').text('Part 2: Determine your FUTA tax before adjustments', leftX, y);
      y += 20;

      drawLine(y, '9', 'FUTA tax before adjustments (gross rate 6.0%)', `$${formatCurrency(data.futaTaxBeforeAdjustments)}`);
      y += lineH;
      drawLine(y, '10', 'State unemployment tax credit (5.4%)', `$${formatCurrency(data.stateUnemploymentContributions)}`);
      y += lineH;
      drawLine(y, '12', 'Total FUTA tax after adjustments (0.6% net rate)', `$${formatCurrency(data.futaTaxAfterCredit)}`);

      y += lineH + 10;
      doc.fontSize(12).font('Helvetica-Bold').fillColor('black').text('Part 3: Determine your FUTA tax liability by quarter', leftX, y);
      y += 20;

      drawLine(y, '16a', 'Q1 liability (Jan 1 - Mar 31)', `$${formatCurrency(data.quarterlyLiabilities.q1)}`);
      y += lineH;
      drawLine(y, '16b', 'Q2 liability (Apr 1 - Jun 30)', `$${formatCurrency(data.quarterlyLiabilities.q2)}`);
      y += lineH;
      drawLine(y, '16c', 'Q3 liability (Jul 1 - Sep 30)', `$${formatCurrency(data.quarterlyLiabilities.q3)}`);
      y += lineH;
      drawLine(y, '16d', 'Q4 liability (Oct 1 - Dec 31)', `$${formatCurrency(data.quarterlyLiabilities.q4)}`);
      y += lineH;

      const totalQuarterly = data.quarterlyLiabilities.q1 + data.quarterlyLiabilities.q2 + data.quarterlyLiabilities.q3 + data.quarterlyLiabilities.q4;
      drawLine(y, '17', 'Total tax liability for the year', `$${formatCurrency(totalQuarterly)}`);

      y += lineH + 10;
      doc.fontSize(12).font('Helvetica-Bold').fillColor('black').text('Part 5: Report your FUTA tax liability', leftX, y);
      y += 20;

      drawLine(y, '13', 'Total FUTA tax deposited for the year', `$${formatCurrency(data.totalDeposited)}`);
      y += lineH;
      drawLine(y, '14', 'Balance due (if Line 12 > Line 13)', `$${formatCurrency(data.balanceDue)}`);

      doc.moveDown(3);
      doc.fontSize(7).font('Helvetica').fillColor('gray');
      doc.text(`Number of employees who received wages: ${data.numberOfEmployees}`, { align: 'center' });
      addPDFDisclaimer(doc);

      doc.end();
    });
  }

  private async generate1099PDF(data: Form1099Data): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'LETTER', margin: 40 });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(16).font('Helvetica-Bold').text('Form 1099-NEC', { align: 'center' });
      doc.fontSize(10).font('Helvetica').text('Nonemployee Compensation', { align: 'center' });
      doc.fontSize(10).text(`Tax Year ${data.taxYear}`, { align: 'center' });
      doc.moveDown(1.5);

      const leftX = 40;
      const rightX = 300;
      const boxW = 250;
      let y = doc.y;

      const drawBox = (x: number, yPos: number, w: number, h: number, label: string, value: string) => {
        doc.rect(x, yPos, w, h).stroke();
        doc.fontSize(7).fillColor('black').text(label, x + 3, yPos + 3, { width: w - 6 });
        doc.fontSize(11).text(value, x + 5, yPos + 20);
      };

      drawBox(leftX, y, boxW, 55, "PAYER'S name, address, and TIN", `${data.payerName}\n${data.payerAddress}\nEIN: ${data.payerEIN}`);
      drawBox(rightX, y, boxW, 55, "PAYER'S TIN", data.payerEIN);

      y += 60;
      drawBox(leftX, y, boxW, 55, "RECIPIENT'S name and address", `${data.recipientName}\n${data.recipientAddress}`);
      drawBox(rightX, y, boxW, 55, "RECIPIENT'S TIN", data.recipientTIN);

      y += 65;
      drawBox(leftX, y, boxW, 50, '1  Nonemployee compensation', `$${formatCurrency(data.nonemployeeCompensation)}`);
      drawBox(rightX, y, boxW, 50, '2  (Reserved)', '');

      y += 55;
      drawBox(leftX, y, boxW, 50, '3  (Reserved)', '');
      drawBox(rightX, y, boxW, 50, '4  Federal income tax withheld', `$${formatCurrency(data.federalTaxWithheld)}`);

      y += 55;
      drawBox(leftX, y, boxW, 50, '5  State tax withheld', '$0.00');
      drawBox(rightX, y, boxW, 50, '6  State/Payer\'s state no.', '');

      doc.moveDown(3);
      addPDFDisclaimer(doc);

      doc.end();
    });
  }

  async generate941Report(
    workspaceId: string,
    quarter: number,
    year: number
  ): Promise<{ success: boolean; pdfBuffer?: Buffer; taxFormId?: string; data?: Form941Data; error?: string }> {
    try {
      if (quarter < 1 || quarter > 4) {
        return { success: false, error: 'Quarter must be between 1 and 4' };
      }

      const workspace = await db.query.workspaces.findFirst({
        where: eq(workspaces.id, workspaceId),
      });
      if (!workspace) return { success: false, error: 'Workspace not found' };

      const quarterStartMonth = (quarter - 1) * 3;
      const quarterStart = new Date(year, quarterStartMonth, 1);
      const quarterEnd = new Date(year, quarterStartMonth + 3, 0, 23, 59, 59);

      const aggregated = await db
        .select({
          totalWages: sql<string>`COALESCE(SUM(CAST(${payrollEntries.grossPay} AS NUMERIC)), 0)`,
          federalTax: sql<string>`COALESCE(SUM(CAST(${payrollEntries.federalTax} AS NUMERIC)), 0)`,
          socialSecurity: sql<string>`COALESCE(SUM(CAST(${payrollEntries.socialSecurity} AS NUMERIC)), 0)`,
          medicare: sql<string>`COALESCE(SUM(CAST(${payrollEntries.medicare} AS NUMERIC)), 0)`,
          stateTax: sql<string>`COALESCE(SUM(CAST(${payrollEntries.stateTax} AS NUMERIC)), 0)`,
          employeeCount: sql<string>`COUNT(DISTINCT ${payrollEntries.employeeId})`,
        })
        .from(payrollEntries)
        .innerJoin(payrollRuns, eq(payrollEntries.payrollRunId, payrollRuns.id))
        .where(
          and(
            eq(payrollEntries.workspaceId, workspaceId),
            gte(payrollRuns.periodEnd, quarterStart),
            lte(payrollRuns.periodEnd, quarterEnd),
            inArray(payrollRuns.status, ['approved', 'processed', 'paid', 'completed'])
          )
        );

      const row = aggregated[0];
      const totalWages = parseFloat(row?.totalWages || '0');
      const federalTaxWithheld = parseFloat(row?.federalTax || '0');
      const employeeSS = parseFloat(row?.socialSecurity || '0');
      const employeeMedicare = parseFloat(row?.medicare || '0');
      const numberOfEmployees = parseInt(row?.employeeCount || '0');

      const SS_RATE = 0.062;
      const MEDICARE_RATE = 0.0145;
      const ADDITIONAL_MEDICARE_RATE = 0.009;

      // F060 fix: Calculate Additional Medicare Tax (line 5d) from actual withheld amounts.
      // The stored medicare column includes both regular (1.45%) and additional (0.9%) medicare.
      // Regular expected = totalWages * 1.45%; difference = additional medicare withheld.
      const regularMedicareExpected = totalWages * MEDICARE_RATE;
      const additionalMedicareWithheld = Math.max(0, employeeMedicare - regularMedicareExpected);
      const additionalMedicareWages = additionalMedicareWithheld > 0
        ? Math.round((additionalMedicareWithheld / ADDITIONAL_MEDICARE_RATE) * 100) / 100
        : 0;

      const employerSS = totalWages * SS_RATE;
      const employerMedicare = totalWages * MEDICARE_RATE;
      const totalSSTax = employeeSS + employerSS;
      // Line 5c tax = regular employee + employer medicare (additional medicare is employee-only, reported on 5d)
      const regularEmployeeMedicare = employeeMedicare - additionalMedicareWithheld;
      const totalMedicareTax = regularEmployeeMedicare + employerMedicare;
      // Line 5d tax = additional medicare (employee-only, 0.9%)
      const additionalMedicareTax = additionalMedicareWithheld;
      const totalSSMedicareTaxes = totalSSTax + totalMedicareTax + additionalMedicareTax;
      const totalTaxesBeforeAdjustments = federalTaxWithheld + totalSSMedicareTaxes;
      const totalTaxesAfterAdjustments = totalTaxesBeforeAdjustments;
      const balanceDue = totalTaxesAfterAdjustments;

      const form941Data: Form941Data = {
        employerEIN: (workspace as any).taxId || (workspace as any).ein || 'XX-XXXXXXX',
        employerName: (workspace as any).companyName || workspace.name || 'Employer',
        employerAddress: (workspace as any).address || '',
        quarter,
        taxYear: year,
        line1_numberOfEmployees: numberOfEmployees,
        line2_wagesTipsCompensation: totalWages,
        line3_federalIncomeTaxWithheld: federalTaxWithheld,
        line5a_taxableSocialSecurityWages: totalWages,
        line5a_tax: totalSSTax,
        line5b_taxableSocialSecurityTips: 0,
        line5b_tax: 0,
        line5c_taxableMedicareWages: totalWages,
        line5c_tax: totalMedicareTax,
        line5d_taxableMedicareWagesOverLimit: additionalMedicareWages,
        line5d_tax: additionalMedicareTax,
        line5e_totalSocialSecurityMedicareTaxes: totalSSMedicareTaxes,
        line6_totalTaxesBeforeAdjustments: totalTaxesBeforeAdjustments,
        line10_totalTaxesAfterAdjustments: totalTaxesAfterAdjustments,
        line11_totalDepositsForQuarter: 0,
        line14_balanceDueOrOverpayment: balanceDue,
        employerSSRate: SS_RATE,
        employerMedicareRate: MEDICARE_RATE,
      };

      const pdfBuffer = await this.generate941PDF(form941Data);

      let taxFormId: string | undefined;
      try {
        const allEmps = await db
          .select({ id: employees.id })
          .from(employees)
          .where(eq(employees.workspaceId, workspaceId))
          .limit(1);

        if (allEmps.length > 0) {
          const [taxForm] = await db.insert(employeeTaxForms).values({
            workspaceId,
            employeeId: allEmps[0].id,
            formType: '941',
            taxYear: year,
            wages: String(totalWages),
            federalTaxWithheld: String(federalTaxWithheld),
            socialSecurityWages: String(totalWages),
            socialSecurityTaxWithheld: String(employeeSS + employerSS),
            medicareWages: String(totalWages),
            medicareTaxWithheld: String(employeeMedicare + employerMedicare),
            stateTaxWithheld: String(0),
            generatedAt: new Date(),
            isActive: true,
          }).returning();
          taxFormId = taxForm.id;
        }
      } catch (storageErr) {
        log.warn('[TaxFormGenerator] Could not store 941 record (enum may need migration):', storageErr);
      }

      // Stamp + save to vault
      const workspace941 = await db.query.workspaces?.findFirst?.({ where: (w: any, { eq: e }: any) => e(w.id, workspaceId) });
      const vaultResult941 = await saveToVault({
        workspaceId,
        workspaceName: (workspace941 as any)?.name || workspaceId,
        documentTitle: `Form 941 Employer Quarterly Federal Tax Return — Q${quarter} ${year}`,
        category: 'tax',
        formNumber: '941',
        period: `Q${quarter} ${year}`,
        relatedEntityType: 'workspace',
        relatedEntityId: workspaceId,
        rawBuffer: pdfBuffer,
      });
      if (!vaultResult941.success) log.warn('[TaxFormGenerator] 941 vault save failed:', vaultResult941.error);

      return {
        success: true,
        pdfBuffer: vaultResult941.stampedBuffer || pdfBuffer,
        taxFormId,
        data: form941Data,
        vaultId: vaultResult941.vault?.id,
        documentNumber: vaultResult941.vault?.documentNumber,
      };
    } catch (error) {
      log.error('[TaxFormGenerator] 941 generation failed:', error);
      return { success: false, error: String(error) };
    }
  }

  private async generate941PDF(data: Form941Data): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'LETTER', margin: 40 });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const quarterNames = ['', 'January - March', 'April - June', 'July - September', 'October - December'];

      doc.fontSize(16).font('Helvetica-Bold').text('Form 941', { align: 'center' });
      doc.fontSize(11).font('Helvetica').text("Employer's QUARTERLY Federal Tax Return", { align: 'center' });
      doc.fontSize(10).text(`Quarter ${data.quarter} (${quarterNames[data.quarter]}) - Tax Year ${data.taxYear}`, { align: 'center' });
      doc.moveDown(1);

      doc.fontSize(9).font('Helvetica-Bold').text('Department of the Treasury - Internal Revenue Service', { align: 'center' });
      doc.moveDown(1);

      const leftX = 40;
      const rightX = 320;
      const fullWidth = 530;
      const halfWidth = 250;
      let y = doc.y;

      const drawBox = (x: number, yPos: number, w: number, h: number, label: string, value: string) => {
        doc.rect(x, yPos, w, h).stroke();
        doc.fontSize(7).font('Helvetica').fillColor('black').text(label, x + 4, yPos + 3, { width: w - 8 });
        doc.fontSize(10).font('Helvetica-Bold').text(value, x + 4, yPos + 16, { width: w - 8 });
      };

      drawBox(leftX, y, halfWidth, 50, 'Employer identification number (EIN)', data.employerEIN);
      drawBox(rightX, y, halfWidth + 10, 50, 'Name (not your trade name)', data.employerName);

      y += 55;
      drawBox(leftX, y, fullWidth, 40, 'Trade name (if any) and Address', data.employerAddress);

      y += 50;
      doc.fontSize(11).font('Helvetica-Bold').fillColor('black').text('Part 1: Answer these questions for this quarter.', leftX, y);
      y += 20;

      const lineH = 30;
      const labelW = 360;
      const valueW = fullWidth - labelW;

      const drawLine = (yPos: number, label: string, value: string) => {
        doc.rect(leftX, yPos, labelW, lineH).stroke();
        doc.rect(leftX + labelW, yPos, valueW, lineH).stroke();
        doc.fontSize(8).font('Helvetica').fillColor('black').text(label, leftX + 4, yPos + 5, { width: labelW - 8 });
        doc.fontSize(10).font('Helvetica-Bold').text(value, leftX + labelW + 4, yPos + 8, { width: valueW - 8, align: 'right' });
      };

      drawLine(y, '1  Number of employees who received wages, tips, or other compensation for the pay period including: ' + quarterNames[data.quarter], String(data.line1_numberOfEmployees));
      y += lineH;

      drawLine(y, '2  Wages, tips, and other compensation', `$${formatCurrency(data.line2_wagesTipsCompensation)}`);
      y += lineH;

      drawLine(y, '3  Federal income tax withheld from wages, tips, and other compensation', `$${formatCurrency(data.line3_federalIncomeTaxWithheld)}`);
      y += lineH;

      drawLine(y, '4  If no wages, tips, and other compensation are subject to social security or Medicare tax', 'N/A');
      y += lineH;

      doc.fontSize(9).font('Helvetica-Bold').text('5  Taxable social security and Medicare wages and tips:', leftX, y + 2);
      y += 18;

      const colW1 = 180;
      const colW2 = 100;
      const colW3 = 80;
      const colW4 = fullWidth - colW1 - colW2 - colW3;

      const drawSubLine = (yPos: number, label: string, wages: string, rate: string, tax: string) => {
        doc.rect(leftX, yPos, colW1, lineH).stroke();
        doc.rect(leftX + colW1, yPos, colW2, lineH).stroke();
        doc.rect(leftX + colW1 + colW2, yPos, colW3, lineH).stroke();
        doc.rect(leftX + colW1 + colW2 + colW3, yPos, colW4, lineH).stroke();
        doc.fontSize(7).font('Helvetica').text(label, leftX + 3, yPos + 4, { width: colW1 - 6 });
        doc.fontSize(9).font('Helvetica-Bold').text(wages, leftX + colW1 + 3, yPos + 8, { width: colW2 - 6, align: 'right' });
        doc.fontSize(8).font('Helvetica').text(rate, leftX + colW1 + colW2 + 3, yPos + 8, { width: colW3 - 6, align: 'center' });
        doc.fontSize(9).font('Helvetica-Bold').text(tax, leftX + colW1 + colW2 + colW3 + 3, yPos + 8, { width: colW4 - 6, align: 'right' });
      };

      drawSubLine(y, 'Column 1', 'Column 2', 'Rate', 'Column 2 x Rate');
      y += lineH;
      drawSubLine(y, '5a Taxable social security wages', `$${formatCurrency(data.line5a_taxableSocialSecurityWages)}`, `${(data.employerSSRate * 2 * 100).toFixed(1)}%`, `$${formatCurrency(data.line5a_tax)}`);
      y += lineH;
      drawSubLine(y, '5b Taxable social security tips', `$${formatCurrency(data.line5b_taxableSocialSecurityTips)}`, `${(data.employerSSRate * 2 * 100).toFixed(1)}%`, `$${formatCurrency(data.line5b_tax)}`);
      y += lineH;
      drawSubLine(y, '5c Taxable Medicare wages & tips', `$${formatCurrency(data.line5c_taxableMedicareWages)}`, `${(data.employerMedicareRate * 2 * 100).toFixed(1)}%`, `$${formatCurrency(data.line5c_tax)}`);
      y += lineH;
      drawSubLine(y, '5d Taxable wages & tips over $200,000 (Additional Medicare)', `$${formatCurrency(data.line5d_taxableMedicareWagesOverLimit)}`, '0.9%', `$${formatCurrency(data.line5d_tax)}`);
      y += lineH;

      drawLine(y, '5e Total social security and Medicare taxes (add 5a through 5d)', `$${formatCurrency(data.line5e_totalSocialSecurityMedicareTaxes)}`);
      y += lineH;

      drawLine(y, '6  Total taxes before adjustments (add lines 3 and 5e)', `$${formatCurrency(data.line6_totalTaxesBeforeAdjustments)}`);
      y += lineH;

      drawLine(y, '7  Current quarter adjustment for fractions of cents', '$0.00');
      y += lineH;

      drawLine(y, '8  Current quarter adjustment for sick pay', '$0.00');
      y += lineH;

      drawLine(y, '9  Current quarter adjustments for tips and group-term life insurance', '$0.00');
      y += lineH;

      drawLine(y, '10  Total taxes after adjustments (combine lines 6 through 9)', `$${formatCurrency(data.line10_totalTaxesAfterAdjustments)}`);
      y += lineH;

      drawLine(y, '11  Total deposits for this quarter', `$${formatCurrency(data.line11_totalDepositsForQuarter)}`);
      y += lineH;

      drawLine(y, '12  Balance due (if line 10 is more than line 11, enter difference)', `$${formatCurrency(Math.max(0, data.line14_balanceDueOrOverpayment))}`);
      y += lineH;

      drawLine(y, '13  Overpayment (if line 11 is more than line 10, enter difference)', `$${formatCurrency(Math.max(0, -data.line14_balanceDueOrOverpayment))}`);
      y += lineH + 10;

      addPDFDisclaimer(doc);

      doc.end();
    });
  }
}

export const taxFormGeneratorService = new TaxFormGeneratorService();
