/**
 * Workspace ID Index Bootstrap
 *
 * Per TRINITY.md §9 (Schema Completeness):
 * "All workspace_id columns indexed."
 *
 * Phase I audit (2026-04-07) found 507 multi-tenant tables that
 * declare a workspace_id column but lack a leading workspaceId index
 * in the Drizzle schema. Without it, every per-workspace lookup falls
 * back to a sequential scan, which becomes a tail-latency cliff at
 * scale and a noisy-neighbour vector that lets one workspace degrade
 * query performance for the rest.
 *
 * This module installs `<table>_workspace_idx` on every such table at
 * boot, idempotently. The full list is generated mechanically from
 * the Drizzle schema and pasted in below — keep it in sync when you
 * add new per-tenant tables.
 *
 * Each statement is `CREATE INDEX IF NOT EXISTS` and skips tables
 * that don't yet exist in the live DB. Failures are logged but never
 * block boot — these are performance indexes, not correctness invariants.
 *
 * 🟡 Long-term fix: declare these indexes in the Drizzle schema files
 * directly so SchemaParityService can manage them. This bootstrap is
 * the transitional shim while the per-domain schema files are updated.
 */

import { pool } from '../db';
import { createLogger } from '../lib/logger';

const log = createLogger('workspaceIndexBootstrap');

// Tables with workspace_id but no leading workspaceId index.
// Generated by Phase I audit (2026-04-07) — see TRINITY.md §9.
const TABLES_NEEDING_WORKSPACE_INDEX: readonly string[] = [
  "automation_triggers", "leader_actions", "audit_logs", "report_templates",
  "report_submissions", "report_workflow_configs", "report_approval_steps", "locked_report_records",
  "report_attachments", "customer_report_access", "kpi_alerts", "kpi_alert_triggers",
  "benchmark_metrics", "employer_ratings", "employer_benchmark_scores", "webhook_deliveries",
  "auto_reports", "search_queries", "metrics_snapshots", "user_platform_update_views",
  "audit_proof_packs", "rate_throttle_logs", "oversight_events", "platform_scan_snapshots",
  "platform_change_events", "feature_usage_events", "api_usage_events", "supervisor_telemetry",
  "officer_score_events", "auditor_accounts", "auditor_followups", "saved_reports",
  "universal_audit_trail", "report_audit_trail", "activities", "sra_audit_sessions",
  "sra_audit_log", "sra_findings", "sra_enforcement_documents", "analytics_daily_snapshots",
  "analytics_client_health_scores", "analytics_scheduled_reports", "api_keys", "role_templates",
  "integration_api_keys", "idempotency_keys", "oauth_states", "external_identifiers",
  "id_sequences", "session_checkpoints", "session_recovery_requests", "user_automation_consents",
  "workspace_api_keys", "api_key_usage_logs", "managed_api_keys", "users",
  "external_cost_log", "labor_cost_forecast", "seat_cost_breakdown", "voice_usage",
  "invoice_proposals", "invoices", "invoice_line_items", "payment_records",
  "org_ledger", "exchange_rates", "subscriptions", "platform_revenue",
  "cost_variance_predictions", "expense_categories", "expenses", "expense_receipts",
  "budgets", "budget_line_items", "budget_variances", "disputes",
  "billing_addons", "ai_token_wallets", "subscription_invoices", "subscription_line_items",
  "subscription_payments", "billing_audit_log", "workspace_rate_history", "quickbooks_migration_runs",
  "quickbooks_onboarding_flows", "quickbooks_api_usage", "billing_policy_profiles", "usage_aggregates",
  "commitment_ledger", "quickbooks_sync_receipts", "billing_services", "location_pnl_snapshots",
  "reconciliation_findings", "reconciliation_runs", "financial_snapshots", "client_profitability",
  "financial_alerts", "org_subscriptions", "account_freezes", "freeze_appeals",
  "org_finance_settings", "financial_processing_fees", "platform_invoices", "usage_caps",
  "invoice_reminders", "invoice_payments", "invoice_adjustments", "client_billing_settings",
  "trinity_credit_failures", "cron_run_log", "state_tax_overrides", "workspace_usage_tracking",
  "token_usage_log", "token_usage_monthly", "client_concerns", "client_satisfaction_records",
  "post_order_version_acknowledgments", "post_order_versions", "site_margin_scores", "subcontractor_companies",
  "client_message_threads", "client_messages", "contract_documents", "client_portal_invite_tokens",
  "clients", "sub_clients", "client_rates", "contacts",
  "partner_connections", "partner_sync_logs", "sites", "site_contacts",
  "business_locations", "client_contracts", "client_contract_access_tokens", "client_portal_reports",
  "site_briefings", "client_collections_log", "client_service_requests", "chat_messages",
  "message_reactions", "typing_indicators", "dm_audit_requests", "dm_access_logs",
  "conversation_encryption_keys", "chat_participants", "blocked_contacts", "email_templates",
  "email_sends", "email_sequences", "sequence_sends", "motd_messages",
  "motd_acknowledgment", "organization_chat_rooms", "organization_chat_channels", "organization_room_members",
  "notifications", "push_subscriptions", "user_notification_preferences", "internal_email_folders",
  "internal_emails", "internal_email_recipients", "mascot_motion_profiles", "external_emails_sent",
  "email_drafts", "contractor_communications", "inbound_emails", "inbound_email_log",
  "channel_bridges", "bridge_conversations", "bridge_messages", "trinity_email_conversations",
  "broadcasts", "broadcast_feedback", "tracked_notifications", "mascot_sessions",
  "mascot_interactions", "mascot_tasks", "email_deliveries", "chat_bot_commands",
  "regulatory_rules", "employee_i9_records", "security_incidents", "document_signatures",
  "company_policies", "policy_acknowledgments", "document_access_logs", "governance_approvals",
  "custom_forms", "custom_form_submissions", "form_signatures", "terms_acknowledgments", "compliance_reports",
  "dar_reports", "compliance_documents", "compliance_approvals", "compliance_expirations",
  "compliance_alerts", "regulator_access", "compliance_scores", "officer_readiness",
  "officer_complaints", "officer_grievances", "state_license_verifications", "document_templates",
  "document_instances", "signatures", "document_vault", "incident_reports",
  "rms_cases", "abuse_violations", "training_certifications", "employee_compliance_records",
  "compliance_audit_packets", "compliance_audit_trail", "compliance_regulator_access", "compliance_score_history",
  "regulatory_violations", "auditor_verification_requests", "sms_consent", "sms_attempt_log",
  "emergency_events", "post_requirements", "incident_patterns", "assets",
  "asset_schedules", "asset_usage_logs", "maintenance_alerts", "maintenance_acknowledgments",
  "dispatch_incidents", "dispatch_assignments", "unit_statuses", "dispatch_logs",
  "equipment_items", "equipment_assignments", "equipment_maintenance_logs", "weapon_checkouts",
  "guard_tour_checkpoints", "guard_tour_scans", "vehicles", "vehicle_assignments",
  "vehicle_maintenance", "panic_alerts", "lone_worker_sessions", "lost_found_items",
  "cad_calls", "cad_units", "cad_dispatch_log", "geofence_zones",
  "geofence_departure_log", "escalation_chains", "key_control_logs", "evidence_items",
  "evidence_custody_log", "incident_report_activity", "trespass_notices", "daily_activity_reports",
  "sla_breach_log", "anonymous_reports", "orchestrated_swap_requests", "platform_exceptions",
  "welfare_checks", "work_orders", "patrol_tours", "celebration_templates",
  "milestone_tracker", "tenant_onboarding_progress", "workspace_cost_summary", "workspace_credit_balance",
  "user_onboarding", "workspace_members", "onboarding_invites", "onboarding_applications",
  "onboarding_workflow_templates", "feature_flags", "integration_marketplace", "integration_connections",
  "webhook_subscriptions", "onboarding_templates", "onboarding_tasks", "organization_onboarding",
  "organization_room_onboarding", "workspace_addons", "org_invitations", "interactive_onboarding_state",
  "org_documents", "workspace_service_catalog", "org_features", "workspace_themes",
  "workspace_invites", "onboarding_checklists", "workspace_role_labels", "workspace_onboarding_states",
  "tos_agreements", "workspace_permissions", "employee_benefits", "payroll_proposals",
  "off_cycle_payroll_runs", "payroll_runs", "payroll_entries", "employee_payroll_info",
  "employee_rate_history", "labor_law_rules", "worker_tax_classification_history", "multi_state_compliance_windows",
  "pay_stubs", "deduction_configs", "payroll_provider_connections", "payroll_deductions",
  "payroll_garnishments", "employee_tax_forms", "bid_analytics", "contract_health_scores",
  "contract_renewal_tasks", "leads", "deals", "rfps",
  "proposals", "deal_tasks", "client_prospects", "pipeline_deals",
  "rfp_documents", "sales_leads", "sales_proposals", "schedules",
  "shift_requests", "shift_offers", "shifts", "custom_scheduler_intervals",
  "recurring_shift_patterns", "shift_acknowledgments", "service_coverage_requests", "published_schedules",
  "schedule_proposals", "shift_templates", "smart_schedule_usage", "shift_orders",
  "shift_order_acknowledgments", "internal_bids", "bid_applications", "capacity_alerts",
  "shift_actions", "shift_chatrooms", "shift_chatroom_members", "shift_chatroom_messages",
  "shift_coverage_requests", "staged_shifts", "automated_shift_offers", "staffing_claim_tokens",
  "shift_coverage_claims", "shift_coverage_offers", "on_call_schedule", "replacement_cascade_logs",
  "faq_entries", "faq_notifications", "support_sessions", "support_tickets",
  "helpos_faqs", "faq_versions", "faq_gap_events", "faq_search_history",
  "help_os_queue", "support_rooms", "support_ticket_access", "knowledge_articles",
  "knowledge_queries", "support_registry", "helpos_ai_transcript_entries", "helpai_action_log",
  "helpai_safety_codes", "support_interventions", "knowledge_gap_logs", "trinity_helpai_command_bus",
  "pto_requests", "time_entries", "time_entry_audit_events", "gps_locations",
  "scheduled_breaks", "evv_visit_records", "manual_clockin_overrides", "time_entry_breaks",
  "time_entry_discrepancies", "time_off_requests", "timesheet_edit_requests", "mileage_logs",
  "agent_registry", "agent_task_logs", "agent_tasks", "ai_usage_log",
  "counterfactual_simulations", "curiosity_queue", "incubation_queue", "social_entities",
  "social_relationships", "somatic_pattern_library", "temporal_entity_arcs", "trinity_ai_usage_log",
  "trinity_autonomous_tasks", "trinity_cognitive_state", "trinity_hypothesis_sessions", "trinity_memory_service",
  "trinity_narrative", "trinity_peripheral_surfaced", "trinity_thinking_sessions", "workspace_ai_usage",
  "custom_rules", "rule_execution_logs", "ai_insights", "ai_usage_events",
  "ai_usage_daily_rollups", "exception_triage_queue", "scoring_weight_profiles", "ai_suggestions",
  "orchestration_runs", "trinity_access_control", "subagent_telemetry", "automation_action_ledger",
  "trinity_conversation_sessions", "trinity_conversation_turns", "ai_approvals", "automation_governance",
  "trinity_user_confidence_stats", "trinity_org_stats", "orchestration_overlays", "ai_gap_findings",
  "trinity_self_awareness", "ai_brain_live_events", "automation_executions", "trinity_automation_settings",
  "trinity_automation_requests", "trinity_automation_receipts", "trinity_buddy_settings", "trinity_metacognition_log",
  "trinity_decision_log", "trinity_requests", "trinity_usage_analytics", "trinity_recommendations",
  "ai_task_queue", "pending_configurations", "trinity_anomaly_log", "meta_cognition_logs",
  "durable_job_queue", "trinity_credit_transactions", "trinity_meeting_recordings", "ai_brain_action_logs",
  "ai_workboard_tasks", "trinity_workspace_pauses", "workspace_phone_numbers", "voice_call_sessions",
  "voice_call_actions", "voice_verification_log", "voice_support_cases", "voice_support_agents",
  "applicant_interviews", "applicants", "employee_onboarding_progress", "employee_training_records",
  "interview_question_sets", "interview_sessions", "job_postings", "offer_letters",
  "officer_performance_scores", "onboarding_documents", "training_attempts", "training_certificates",
  "training_requirements", "training_scheduled_sessions", "employee_profiles", "contractor_pool",
  "contractor_skills", "contractor_assignments", "performance_reviews", "manager_assignments",
  "employee_documents", "turnover_risk_scores", "skill_gap_analyses", "pulse_survey_templates",
  "pulse_survey_responses", "anonymous_suggestions", "employee_health_scores", "offboarding_sessions",
  "exit_interview_responses", "employee_availability", "satisfaction_surveys", "leaderboard_cache",
  "coaileague_employee_profiles", "employee_event_log", "employee_score_snapshots", "ai_decision_audit",
  "feedback_votes", "flex_contractors", "flex_availability", "flex_gigs",
  "flex_gig_ratings", "known_contractors", "employee_invitations", "employees",
  "training_scenarios", "training_runs", "training_courses", "training_enrollments",
  "employee_recognition", "employee_behavior_scores", "employee_certifications", "employee_bank_accounts",
  "hiring_pipeline", "performance_notes", "disciplinary_records",
  // Phase 8: P&L Revenue Recognition tables (2026-04)
  "revenue_recognition_schedule", "deferred_revenue", "processed_revenue_events", "contract_revenue_mapping",
];

export async function ensureWorkspaceIndexes(): Promise<void> {
  log.info(`[workspaceIndex] Ensuring workspace_id indexes on ${TABLES_NEEDING_WORKSPACE_INDEX.length} tables`);

  let installed = 0;
  let alreadyPresent = 0;
  let skipped = 0;
  let failed = 0;

  for (const table of TABLES_NEEDING_WORKSPACE_INDEX) {
    // Defense-in-depth: validate identifier even though list is hardcoded
    if (!/^[a-z0-9_]+$/.test(table)) {
      log.warn(`[workspaceIndex] Skipping invalid table name: ${table}`);
      continue;
    }
    const indexName = `${table}_workspace_idx`;
    if (indexName.length > 63) {
      log.warn(`[workspaceIndex] Index name too long, skipping: ${indexName}`);
      continue;
    }
    try {
      // Check the table actually exists before trying to index it.
      // Some tables in the list may belong to features not yet deployed
      // in this environment.
      const { rows: tableExists } = await pool.query(
        `SELECT 1 FROM information_schema.tables
         WHERE table_schema = current_schema() AND table_name = $1`,
        [table]
      );
      if (tableExists.length === 0) {
        skipped++;
        continue;
      }
      // Verify the column actually exists too
      const { rows: colExists } = await pool.query(
        `SELECT 1 FROM information_schema.columns
         WHERE table_schema = current_schema() AND table_name = $1 AND column_name = 'workspace_id'`,
        [table]
      );
      if (colExists.length === 0) {
        skipped++;
        continue;
      }
      // Idempotent: pg_indexes lookup avoids the noise of CREATE IF NOT EXISTS
      const { rows: idxExists } = await pool.query(
        `SELECT 1 FROM pg_indexes
         WHERE schemaname = current_schema() AND indexname = $1`,
        [indexName]
      );
      if (idxExists.length > 0) {
        alreadyPresent++;
        continue;
      }
      await pool.query(`CREATE INDEX IF NOT EXISTS "${indexName}" ON "${table}" ("workspace_id")`);
      installed++;
    } catch (err: unknown) {
      failed++;
      log.warn(`[workspaceIndex] ${table}: ${err?.message}`);
    }
  }

  log.info(
    `[workspaceIndex] Complete: ${installed} installed, ${alreadyPresent} already present, ${skipped} skipped (table missing), ${failed} failed`
  );
}
